#!/bin/bash -e

# =============================================================================
#
# NAME: JEVS_CAM_PREP
# CONTRIBUTOR(S): Marcel Caron, marcel.caron@noaa.gov, NOAA/NWS/NCEP/EMC-VPPPGB
# PURPOSE: Use ECF environment variables to define and run an EVS job
# DEPENDENCIES: $EVS_HOME_DIR/ecf/cam/prep/jevs_$MODELNAME_$VERIF_CASE_prep.ecf
#
# =============================================================================

set -xa

echo "BEGIN: $(basename ${BASH_SOURCE[0]})"

# Shell Processing Variables
export PS4='$SECONDS + '
date

# LSF id (jobid) and Temp Directories
export pid=$$
# in production, the following will be set to DATAROOT
#export DATA_IN=${DATA_IN:-$DATAROOT}
export DATA_IN=${DATA_IN:-$DATAROOTtmp}
export DATA=$DATA_IN/${jobid}
rm -rf $DATA
mkdir -p $DATA
cd $DATA

# General I/O Settings
export pgmout="OUTPUT.${pid}"
export VDATE=$(date -d "today -1 day" +"%Y%m%d")
export COMIN=${COMIN:-$(compath.py -o $NET/$evs_ver)}
export COMINccpa=${COMINccpa:-$(compath.py prod/ccpa/$ccpa_ver)}
export COMINmrms=$DCOMROOT/ldmdata/obs/upperair/mrms/alaska/MultiSensorQPE
export COMINnam=${COMINnam:-$(compath.py ${envir}/com/nam/${nam_ver})}
export COMINhiresw=${COMINhiresw:-$(compath.py ${envir}/com/hiresw/${hiresw_ver})}
export COMINhrrr=${COMINhrrr:-$(compath.py ${envir}/com/hrrr/${hrrr_ver})}
# in production, the following will be set to the approp. COMOUT dir
#export COMOUT=${COMOUT:-$(compath.py -o $NET/$evs_ver/$STEP/$COMPONENT/$RUN)}
export COMOUT=/lfs/h2/emc/ptmp/marcel.caron/EVS_out/com/$NET/$evs_ver/$STEP/$COMPONENT/$RUN

# Subdirectories to EVS Home Directory
export EVS_PARM_DIR=$EVS_HOME_DIR/parm
export EVS_USH_DIR=$EVS_HOME_DIR/ush
export EVS_EXEC_DIR=$EVS_HOME_DIR/exec
export EVS_FIX_DIR=$EVS_HOME_DIR/fix
export EVS_SCRIPTS_DIR=$EVS_HOME_DIR/scripts
export MET_PLUS_CONF="${EVS_PARM_DIR}/metplus_config/cam/precip/stats"

# Execute the Script
$EVS_SCRIPTS_DIR/$COMPONENT/$STEP/exevs_${MODELNAME}_${VERIF_CASE}_${STEP}.sh
export err=$?; err_chk

# Clean Up
cat $pgmout
msg="JOB $job HAS COMPLETED NORMALLY."
postmsg "$jlogfile" "$msg"
if [ "$KEEPDATA" != "YES" ] ; then
  cd $DATA_IN
  rm -rf $DATA
fi

echo "END: $(basename ${BASH_SOURCE[0]})"
