#!/bin/ksh
#  JOB card cerated for running METPlus-based Global enesmble verifications
#   By Binbin Zhou, IMSG@EMC/NCEP
#   Feb 2, 2022
#
set -xa
#######################################################
#######################################################

export cycle=t${cyc}z

export DATA_IN=${DATA_IN:-$DATAROOT}
export pid=$$
jobid=evs_${RUN}_${COMPONENT}_${STEP}.$$
export DATA=$DATA_IN/$jobid
mkdir -p $DATA
cd $DATA

# Run setpdy and initialize PDY variables
setpdy.sh
. $DATA/PDY

if [ $RUN = atmos ] ; then
  export INITDATE=${INITDATE:-$PDYm2}
fi


export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-YES}
export SENDECF=${SENDECF:-YES}

export COMIN=${COMIN:-$(compath.py $envir/com/$NET/$evs_ver)}
export COMINspsoutlook=${COMINspsoutlook:-$(compath.py $envir/com/$NET/$evs_ver)}
export COMOUT=${COMOUT:-$(compath.py -o $envir/com/$NET/${evs_ver})/$step/$component/href}
mkdir $COMOUT

export HOMEevs=${HOMEevs:-${PACKAGEROOT}/evs_gens.${evs_ver}}
export EXECevs=$HOMEevs/exec
export PARMevs=$HOMEevs/parm
export USHevs=$HOMEevs/ush
export SCRIPTerf=$HOMEevs/scripts
export FIXevs=${FIXevs:-$HOMEevs/fix}

####################################
# Determine Job Output Name on System
####################################
export outid="LL$job"
export jobid="${outid}.o${pid}"
export pgmout="OUTPUT.${pid}"


sh $HOMEevs/scripts/${COMPONENT}/${STEP}/exevs_${MODELNAME}_${VERIF_CASE}_${STEP}.sh

msg="JOB $job HAS COMPLETED NORMALLY."
postmsg "$msg"

if [ "$KEEPDATA" != "YES" ] ; then
  cd $DATAROOT
  rm -rf $DATA
fi

date

