#!/bin/bash

########################################
# Preliminary data setup step
########################################
set -xa


####################################
# SET SHELL PROCESSING VARIABLES
####################################
export PS4='$SECONDS + '
date


###########################################################
# obtain unique LSF id (jobid) and make temp directories
###########################################################
export pid=$$
export DATA=${DATA:-${DATAROOT:?}/${jobid:?}}
rm -rf $DATA
mkdir -p $DATA
cd $DATA


####################################
# Determine Job Output Name on System
####################################
export pgmout="OUTPUT.${pid}"


####################################
# Set EVS directories
####################################
export HOMEevs=${HOMEevs:-${PACKAGEROOT}/evs.${evs_ver}}
export EXECevs=${EXECevs:-$HOMEevs/exec}
export FIXevs=${FIXevs:-$HOMEevs/fix}
export PARMevs=${PARMevs:-$HOMEevs/parm}
export SCRIPTSevs=${SCRIPTSevs:-$HOMEevs/scripts}
export USHevs=${USHevs:-$HOMEevs/ush}
export MET_PLUS_CONF="${PARMevs}/metplus_config/${COMPONENT}/${VERIF_CASE}/${STEP}"


####################################
# Run setpdy and initialize PDY variables
####################################
export cycle=${cycle:-t${cyc}z}
setpdy.sh 8
. ./PDY

if [ $VERIF_CASE = precip ] ; then
   # LD: can use setpdy.sh instead to match convention of rest of EVS  
   # export VDATE=${VDATE:-$PDYm1}
   export VDATE=$(date -d "today -1 day" +"%Y%m%d")
elif [ $VERIF_CASE = radar ] ; then
   export VDATE=${VDATE:-$PDYm1}
elif [ $VERIF_CASE = severe ] ; then

   # Set verification date
   export VDATE=${VDATE:-$PDYm7}
  
   # Set correct date for SPC report data 
   export REP_DATE=${REP_DATE:-$(date -d "$VDATE -1 day" +"%Y%m%d")}

   # Set initialization date (only for forecast prep step)
   export IDATE=${IDATE:-$PDYm1}

fi


####################################
# Define NET/RUN variables
####################################
export NET=${NET:-evs}
export STEP=${STEP:-prep}
export COMPONENT=${COMPONENT:-cam}
export RUN=${RUN:-atmos}


####################################
# Define COMIN/COMOUT variables
####################################
export COMIN=${COMIN:-$(compath.py $NET/$evs_ver)}
export COMINccpa=${COMINccpa:-$(compath.py prod/ccpa/$ccpa_ver)}
export COMINhiresw=${COMINhiresw:-$(compath.py ${envir}/com/hiresw/${hiresw_ver})}
export COMINhrrr=${COMINhrrr:-$(compath.py ${envir}/com/hrrr/${hrrr_ver})}
export COMINmrms=$DCOMROOT/ldmdata/obs/upperair/mrms
export COMINnam=${COMINnam:-$(compath.py ${envir}/com/nam/${nam_ver})}
export COMINspc=${COMINspc:-$DCOMROOT}

export COMOUT=${COMOUT:-$(compath.py -o $NET/$evs_ver/$STEP/$COMPONENT/$RUN)}
export COMOUTmrms=${COMOUT}/mrms.${VDATE}

if [ $VERIF_CASE = severe ] ; then
   export COMOUTspc=${COMOUT}/spc.${REP_DATE}
fi

####################################
# Execute the script 
####################################
$HOMEevs/scripts/$COMPONENT/$STEP/exevs_${MODELNAME}_${VERIF_CASE}_${STEP}.sh
export err=$?; err_chk

if [ -e "$pgmout" ]; then
   cat $pgmout
fi

msg="JOB $job HAS COMPLETED NORMALLY."
postmsg "$msg"

if [ "$KEEPDATA" != "YES" ] ; then
   if [ $VERIF_CASE = precip ] ; then
      cd $DATA_IN
   else
      cd $DATAROOT
   fi
   rm -rf $DATA
fi

date
