#!/bin/bash 
date
export PS4=' $SECONDS + '
set -x

####################################
# obtain unique process id (pid) and make temp directory
####################################
export jobid=${jobid:-$job.o$$}
export DATA=${DATA:-${DATAROOT:?}/${jobid}}
mkdir -p $DATA
cd $DATA
export cycle=t${cyc}z

####################################
# File To Log Msgs
####################################
export jlogfile=${jlogfile:-${DATA}/jlogfile.${jobid}}

####################################
# Specify NET and RUN Name and model
####################################
export NET=${NET:-evs}
export COMPONENT=${COMPONENT:-define_in_ecf}
export RUN=${RUN:-define_in_ecf}
export STEP=${STEP:-stats}

####################################
# Determine Job Output Name on System
####################################
export pgmout="OUTPUT.$$"
export pgmerr=errfile

####################################
# SENDECF  - Flag Events on ecFLOW
# SENDCOM  - Copy Files From TMPDIR to $COMOUT
# SENDDBN  - Issue DBNet Client Calls
####################################
export SENDECF=${SENDECF:-NO}
export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-NO}

####################################
# Specify Execution Areas
####################################
export HOMEevs=${HOMEevs:-${PACKAGEHOME}}
export SCRIPTSevs=${SCRIPTSevs:-$HOMEevs/scripts/hurricane/stats}
export PARMevs=${PARMevs:-$HOMEevs/parm/metplus_config/hurricane/stats}

# Run setpdy and initialize PDY variables
##############################
#setpdy.sh
#. ./PDY

##############################################
# Define COM directories
##############################################
if [ ${COMPONENT} = "hurricane_global_det" -a ${RUN} = "tropcyc" ]; then
#setpdy.sh
#. ./PDY
export PDY=20221231
export YYYY=`echo ${PDY} | cut -c1-4`
export YY22=`echo ${PDY} | cut -c3-4`

export COMINvit=${COMINvit:-/your/TC/vitals/file}
export COMINtrack=${COMINtrack:-your/TC/track/file}
export COMINbdeckNHC=${COMINbdeckNHC:-/your/NHC/bdeck/data/dir}
export COMINbdeckJTWC=${COMINbdeckJTWC:-/your/JTWC/bdeck/data/dir}

elif [ ${COMPONENT} = "hurricane_global_ens" -a ${RUN} = "tropcyc" ]; then
#setpdy.sh
#. ./PDY
export PDY=20221231
export YYYY=`echo ${PDY} | cut -c1-4`
export YY22=`echo ${PDY} | cut -c3-4`

export COMINvit=${COMINvit:-/your/TC/vitals/file}
export COMINtrack=${COMINtrack:-your/TC/track/file}
export COMINbdeckNHC=${COMINbdeckNHC:-/your/NHC/bdeck/data/dir}
export COMINbdeckJTWC=${COMINbdeckJTWC:-/your/JTWC/bdeck/data/dir}

elif [ ${COMPONENT} = "hurricane_global_det" -a ${RUN} = "tcgen" ]; then
#setpdy.sh
#. ./PDY
export PDY=20221231

export YYYY=`echo ${PDY} | cut -c1-4`
#export YY22=`echo ${PDY} | cut -c3-4`
export COMINgenesis=${COMINgenesis:-/your/TC/genesis/data/dir}
export COMINadeckNHC=${COMINadeckNHC:-/your/NHC/adeck/data/dir}
export COMINbdeckNHC=${COMINbdeckNHC:-/your/NHC/bdeck/data/dir}
export COMINadeckJTWC=${COMINadeckJTWC:-/your/JTWC/adeck/data/dir}
export COMINbdeckJTWC=${COMINbdeckJTWC:-/your/JTWC/bdeck/data/dir}

elif [ ${COMPONENT} = "hurricane_regional" -a ${RUN} = "tropcyc" ]; then
setpdy.sh
. ./PDY 
export YYYY=`echo ${PDY} | cut -c1-4`
export YY22=`echo ${PDY} | cut -c3-4`

export COMINvit=${COMINvit:-/your/TC/vitals/file}
export COMINtrack=${COMINtrack:-your/TC/track/file}
export COMINbdeckNHC=${COMINbdeckNHC:-/your/NHC/bdeck/data/dir}
export COMINbdeckJTWC=${COMINbdeckJTWC:-/your/JTWC/bdeck/data/dir}

else
echo "Job failed: unknown ${COMPONENT} and ${RUN}"
err_exit "FAILED ${jobid} - ERROR IN unknown ${COMPONENT} and ${RUN} - ABNORMAL EXIT"

fi

#export COMOUT=${COMOUT:-$(compath.py -o ${NET}/${evs_ver})/${COMPONENT}/${RUN}/${STEP}}
export COMOUT=${COMOUT:-${COMROOT}/${NET}/${evs_ver}/${COMPONENT}/${RUN}/${STEP}}
mkdir -m 775 -p $COMOUT 

msg="HAS BEGUN on `hostname`"
postmsg "$jlogfile" "$msg"

#env

#############################################################
# Execute the script
${SCRIPTSevs}/exevs_${COMPONENT}_${RUN}_stats.sh
export err=$?; err_chk

#############################################################

msg="JOB COMPLETED NORMALLY"
postmsg "$jlogfile" "$msg"

##############################
# Remove the Temporary working directory
##############################
if [[ $KEEPDATA != "YES" ]]; then
  rm -rf $DATA
fi

date
