#!/bin/bash
##############################################################################
#Jobb Name: JEVS_GLWU_PLOTS
# Purpose: To create plots for GLWU verification using MET/METplus.
# Author: Samira Ardani (samira.ardani@noaa.gov)
###############################################################################

set -x

########################################
# Preliminary data setup step
########################################

export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-YES}
export SENDECF=${SENDECF:-YES}

# ###################################
# SET SHELL PROCESSING VARIABLES
# ###################################
export PS4='$SECONDS + '
date

###########################################################
# obtain unique LSF id (jobid) and make temp directories
###########################################################
export pid=$$

export DATA=${DATA:-${DATAROOT:?}/${jobid:?}}
rm -rf $DATA
mkdir -p $DATA
cd $DATA

# Determine Job Output Name on System
####################################
export pgmout="OUTPUT.${pid}"

export cycle=t00z

##################################
# Set EVS directories
####################################
export HOMEevs=${HOMEevs:-${PACKAGEROOT}/evs.${evs_ver}}
export EXECevs=${EXECevs:-$HOMEevs/exec}
export FIXevs=${FIXevs:-$HOMEevs/fix}
export PARMevs=${PARMevs:-$HOMEevs/parm}
export SCRIPTSevs=${SCRIPTSevs:-$HOMEevs/scripts}
export USHevs=${USHevs:-$HOMEevs/ush}
export MASKS=${MASKS:-$FIXevs/masks}

# Run setpdy and initialize PDY variables
setpdy.sh
. ./PDY

export VDATE=${VDATE:-$PDYm1}


# set up paths
export CONFIGevs=${CONFIGevs:-$HOMEevs/parm/metplus_config/$COMPONENT}

# define COMIN/COMOUT variables
export COMIN=${COMIN:-$(compath.py $envir/com/$NET/${evs_ver})}
export COMINstats=${COMINstats:-$COMIN/stats/$COMPONENT}
export COMOUT=${COMOUT:-$(compath.py $NET/${evs_ver})}
export COMOUTplots=${COMOUTplots:-$COMOUT/$STEP/$COMPONENT/$COMPONENT.$VDATE}
export COMOUTplotsheadline=${COMOUTplotsheadline:-$COMOUT/$STEP/$COMPONENT/headline.$VDATE}

mkdir -p $COMOUT $COMOUTplots $COMOUTplotsheadline
mkdir -p $DATA/$STEP/$COMPONENT/$COMPONENT.$VDATE

# make plots; run scripts for each RUN;
# RUN is the validation source: for now, I know ndbc. But the other validation sources is added here.
for rcase in ndbc; do
  export RUN=$rcase

  if [ $RUN = 'ndbc' ] ; then
    export OBTYPE=NDBC_STANDARD
    export VAR=htsgw
    export VERIF_CASE=grid2obs
    export FLVL=Z0
    export OLVL=Z0
  fi

  $HOMEevs/scripts/$COMPONENT/$STEP/exevs_${COMPONENT}_seasfc_${STEP}.sh
done


export RUN=headline
$HOMEevs/scripts/$COMPONENT/$STEP/exevs_${COMPONENT}_headline_${STEP}.sh
mkdir $COMOUTplots

if [ -e "$pgmout" ]; then
	    cat $pgmout
fi

msg="JOB $job HAS COMPLETED NORMALLY."
postmsg "$msg"

if [ "$KEEPDATA" != "YES" ] ; then
  cd $DATAROOT
  rm -rf $DATA
fi

date


################################# END OF JOB ##################################
