#!/bin/ksh

########################################
# Preliminary data setup step
########################################
set -xa

# ###################################
# SET SHELL PROCESSING VARIABLES
# ###################################
export PS4='$SECONDS + '
date

###########################################################
# obtain unique LSF id (jobid) and make temp directories
###########################################################
export pid=$$
#export DATA_IN=${DATA_IN:-$DATAROOT}
#export DATA=$DATA_IN/${jobid}

export DATA=/lfs/h2/emc/ptmp/perry.shafran/EVS/${cyc}_${MODELNAME}

rm -rf $DATA
mkdir -p $DATA
cd $DATA

####################################
# Determine Job Output Name on System
####################################
export pgmout="OUTPUT.${pid}"

export cycle=t${cyc}z

##################################################
# SAVEGES  - Copy Files From TMPDIR to $GESdir
# SENDECF  - Flag Events on ecFLOW
# SENDCOM  - Copy Files From TMPDIR to $COMOUT
# SENDDBN  - Issue DBNet Client Calls
##################################################
export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-YES}
export SENDECF=${SENDECF:-YES}

export DCOMROOT=${DCOMROOT:-/lfs/h1/ops/$envir/dcom}
export EXECevs=${EXECevs:-$HOMEevs/exec}
export FIXvevs=${FIXevs:-$HOMEevs/fix}
export PARMevs=${PARMevs:-$HOMEevs/parm}
export USHevs=${USHevs:-$HOMEevs/ush}

# Run setpdy and initialize PDY variables
setpdy.sh
. ./PDY

export VDATE=$PDYm1

# Define COMIN/COMOUT variables:

echo $COMPATH

export COMIN=${COMIN:-$(compath.py -o ${envir}/com/${NET}/$evs_ver)}
export COMINfcst=${COMINfcst:-$(compath.py ${envir}/com/${modsys}/${mod_ver})}
export COMINobs=${COMINobs:-$(compath.py ${envir}/com/obsproc/${obsproc_ver})}
export COMOUT=/lfs/h2/emc/vpppg/noscrub/perry.shafran/${NET}/${evs_ver}/${STEP}/${COMPONENT}
export COMOUTsmall=$COMOUT/${RUN}.${VDATE}/$MODELNAME/$VERIF_CASE
export COMOUTfinal=$COMOUT/${MODELNAME}.${VDATE}

#######################################################################
# Execute the script.
#######################################################################

$HOMEevs/scripts/${COMPONENT}/${STEP}/exevs_${MODELNAME}_${STEP}.sh

cat $pgmout

msg="JOB $job HAS COMPLETED NORMALLY."
postmsg "$jlogfile" "$msg"

#if [ "$KEEPDATA" != "YES" ] ; then
#  cd $DATAROOT
#  rm -rf $DATA
#fi

