#!/bin/ksh

########################################
# Preliminary data setup step
########################################

# ###################################
# SET SHELL PROCESSING VARIABLES
# ###################################
date
export PS4='$SECONDS + '
set -xa

###########################################################
# obtain unique LSF id (jobid) and make temp directories
###########################################################
export pid=$$

export DATA=${DATA:-${DATAROOT:?}/${jobid:?}}
mkdir -p $DATA
cd $DATA

export cycle=${cycle:-t${cyc}z}
setpdy.sh 31
. ./PDY 

####################################
# Determine Job Output Name on System
####################################
export pgmout="OUTPUT.${pid}"

##################################################
# SAVEGES  - Copy Files From TMPDIR to $GESdir
# SENDECF  - Flag Events on ecFLOW
# SENDCOM  - Copy Files From TMPDIR to $COMOUT
# SENDDBN  - Issue DBNet Client Calls
##################################################
export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-YES}
export SENDECF=${SENDECF:-YES}

export envir=${envir:-prod}
export DCOMROOT=${DCOMROOT:-/lfs/h1/ops/$envir/dcom}

export HOMEevs=${HOMEevs:-${PACKAGEROOT}/evs.${evs_ver}}
export EXECevs=${EXECevs:-$HOMEevs/exec}
export FIXvevs=${FIXevs:-$HOMEevs/fix}
export PARMevs=${PARMevs:-$HOMEevs/parm}
export SCRIPTSevs=${SCRIPTSevs:-$HOMEevs/scripts}
export USHevs=${USHevs:-$HOMEevs/ush}

# Define COMIN/COMOUT variables:

echo $COMPATH

export NET=${NET:-evs}
export STEP=${STEP:-plots}
export COMPONENT=${COMPONENT:-aqm}
export RUN=${RUN:-atmos}
export VERIF_CASE=${VERIF_CASE:-grid2obs}
export MODELNAME=${MODELNAME:-aqm}
export modsys=${modsys:-aqm}
export mod_ver=${mod_ver:-${aqm_ver}}

export MET_bin_exec=${MET_bin_exec:-bin}

export VDATE=${VDATE:-${PDYm3}}

export COMIN=${COMIN:-$(compath.py ${envir}/com/${NET}/${evs_ver}/)}
export COMINaqm=${COMINaqm:-$(compath.py ${envir}/com/${NET}/${evs_ver}/stats/${COMPONENT}/${MODELNAME})}
export COMOUT=${COMOUT:-${COMIN}/${STEP}/${COMPONENT}}
export COMOUTplots=${COMOUTplots:-${COMOUT}/${RUN}.${VDATE}}
mkdir -m 775 -p $COMOUT

vfcst_ver=$(echo ${mod_ver} | cut -c1-2 )
export fcst_input_ver=${fcst_input_ver:-${vfcst_ver}}
 
export KEEPDATA=${KEEPDATA:-YES}

#######################################################################
# Execute the script.
#######################################################################

$HOMEevs/scripts/${COMPONENT}/${STEP}/exevs_${MODELNAME}_${VERIF_CASE}_${STEP}.sh

if [ -e "$pgmout" ]; then
    cat $pgmout
fi

msg="JOB $job HAS COMPLETED NORMALLY."
postmsg "$msg"

if [ "$KEEPDATA" != "YES" ] ; then
    cd $DATAROOT
    rm -rf $DATA
fi


