#!/bin/sh

set -xa

export PS4='$SECONDS + '
date

############################################
# Working Directory                                                                                                                                      
############################################
export DATA=${DATA:-${DATAROOT}/${jobid:?}}
mkdir -p $DATA
cd $DATA

############################################
# Determine Job Output Name on System
############################################
export pid=$$
export pgmout=OUTPUT.${pid}

############################################
# Initialize PDY variables
############################################
export cyc=${cyc:-00}
export cycle=t${cyc}z

#It needs $DATA and $cycle to be set
setpdy.sh
. ./PDY

# Don't specify $VDATE to be flexible to both data preparation and MET stat input
export VDATE=${VDATE:-$PDYm1}

############################################
# Set up the NET and RUN                                                                                                                         
############################################
export NET=${NET:-evs}
export STEP=${STEP:-stats} # prep stats plot
export COMPONENT=${COMPONENT:-global_det}
export RUN=${RUN:-aviation}
export VERIF_CASE=${VERIF_CASE:-grid2grid}

# WAFS is the general MODELNAME for data structure
# while the center (us/uk/blend or gfs) will be the actual MODEL
# parm/metplus_config/global_det/aviation/stats/GridStat_fcstWAFS_obsGCIP.conf
# parm/metplus_config/global_det/aviation/stats/StatAnalysis_fcstWAFS_obsGCIP_GatherbyDay.conf
export MODELNAME=${MODELNAME:-wafs}

############################################
# Set up the INPUT and OUTPUT directories
############################################

# COMIN folder of analysis and forecast grib2 data
# gfs_ver defined in versions/run.ver
export COMIN=${COMIN:-$(compath.py ${envir}/com/${NET}/${evs_ver})}
export COMINuk=${COMINuk:-$DCOMROOT} # $VDATE/wgrbbul/ukmet_wafs}
export COMINgfs=${COMINgfs:-$(compath.py gfs/${gfs_ver})}
export COMINobs=$COMINgfs

# COMOUT folder
# evs_ver defined in versions/run.ver
export COMOUT=${COMOUT:-$(compath.py ${envir}/com/${NET}/${evs_ver})}
export COMOUTsmall=$COMOUT/$STEP/$COMPONENT/$RUN.$VDATE/$MODELNAME/$VERIF_CASE
export COMOUTfinal=$COMOUT/$STEP/$COMPONENT/$MODELNAME.$VDATE

mkdir -p $COMOUTsmall $COMOUTfinal

############################################
# Specify HOME Directory
############################################

export HOMEevs=${HOMEevs:-$PACKAGEROOT/evs.$evs_ver}
export EXECevs=${EXECevs:-$HOMEevs/exec}
export FIXevs=${FIXevs:-$HOMEevs/fix}
export SCRIPTSevs=${SCRIPTSevs:-$HOMEevs/scripts/$COMPONENT} # step
export JOBSevs=${JOBSevs:-$HOMEevs/jobs/$COMPONENT} # step
export PARMevs=${PARMevs:-$HOMEevs/parm/metplus_config/$COMPONENT/$RUN} # step
export USHevs=${USHevs:-$HOMEevs/ush/$COMPONENT} # all pool

export MACHINE_CONF=$HOMEevs/parm/metplus_config/machine.conf

export MASKS=${MASKS:-$FIXevs/masks}

############################################
# Execute the script.
############################################
export MPIRUN=${MPIRUN:-"mpiexec -np 2 -cpu-bind verbose,core cfp"}

rm wafs_stat.cmdfile
if [ `echo $MPIRUN | cut -d " " -f1` = 'srun' ] ; then
    echo 0 $SCRIPTSevs/stats/exevs_global_det_aviation_stats.sh GCIP  >> wafs_stat.cmdfile
    echo 1 $SCRIPTSevs/stats/exevs_global_det_aviation_stats.sh GFS >> wafs_stat.cmdfile
else
    echo $SCRIPTSevs/stats/exevs_global_det_aviation_stats.sh GCIP  >> wafs_stat.cmdfile
    echo $SCRIPTSevs/stats/exevs_global_det_aviation_stats.sh GFS >> wafs_stat.cmdfile
    export MP_PGMMODEL=mpmd
fi

$MPIRUN wafs_stat.cmdfile

export err=$?; err_chk

msg="JOB $job HAS COMPLETED NORMALLY."
echo $msg

if [ "$KEEPDATA" != "YES" ] ; then
  rm -rf $DATA
fi

date
exit
