#!/bin/sh

########################################
# Preliminary data setup step
########################################
set -xa

####################################
# SET SHELL PROCESSING VARIABLES
####################################
export PS4='$SECONDS + '
date

###########################################################
# obtain unique LSF id (jobid) and make temp directories
###########################################################
export pid=$$
export DATA=${DATA:-${DATAROOT:?}/${jobid:?}}
mkdir -p $DATA
cd $DATA

####################################
# Determine Job Output Name on System
####################################
export pgmout="OUTPUT.${pid}"

####################################
# Set EVS directories
####################################
export HOMEevs=${HOMEevs:-${PACKAGEROOT}/evs.${model_ver}}
export EXECevs=${EXECevs:-$HOMEevs/exec}
export FIXevs=${FIXevs:-$HOMEevs/fix}
export PARMevs=${PARMevs:-$HOMEevs/parm}
export USHevs=${USHevs:-$HOMEevs/ush}

####################################
# Run setpdy and initialize PDY variables
####################################
export cycle=${cycle:-t${cyc}z}
setpdy.sh
. ./PDY
export VDATE=$PDYm1

####################################
# Define NET/RUN variables
####################################
export NET=${NET:-evs}
export STEP=${STEP:-stats}
export COMPONENT=${COMPONENT:-global_det}
export RUN=${RUN:-atmos}

####################################
# Define COMIN/COMOUT variables
####################################
##export COMIN=${COMIN:-$(compath.py -o $NET/$evs_ver)}
export COMINcfs=${COMINcfs:-$(compath.py -o prod/cfs/$cfs_ver)}
export COMINgfs=${COMINgfs:-$(compath.py prod/gfs/$gfs_ver)}
##export COMINcmc=${COMINcmc:-$(compath.py $NET/$evs_ver/prep/$COMPONENT/$RUN)}
##export COMINcmc_regional=${COMINcmc_regional:-$(compath.py $NET/$evs_ver/prep/$COMPONENT/$RUN)}
##export COMINdwd=${COMINdwd:-$(compath.py $NET/$evs_ver/prep/$COMPONENT/$RUN)}
##export COMINecmwf=${COMINecmwf:-$(compath.py $NET/$evs_ver/prep/$COMPONENT/$RUN)}
##export COMINfnmoc=${COMINfnmoc:-$(compath.py $NET/$evs_ver/prep/$COMPONENT/$RUN)}
##export COMINimd=${COMINimd:-$(compath.py $NET/$evs_ver/prep/$COMPONENT/$RUN)}
##export COMINjma=${COMINjma:-$(compath.py $NET/$evs_ver/prep/$COMPONENT/$RUN)}
##export COMINmetfra=${COMINmetfra:-$(compath.py $NET/$evs_ver/prep/$COMPONENT/$RUN)}
##export COMINukmet=${COMINukmet:-$(compath.py $NET/$evs_ver/prep/$COMPONENT/$RUN)}
export COMROOT=/lfs/h2/emc/vpppg/save/mallory.row/verification/global/evs_test/prod
export COMIN=/lfs/h2/emc/vpppg/save/mallory.row/verification/global/evs_test/$envir/com/$NET/$evs_ver
export COMINcmc=${COMINcmc:-$COMIN/prep/$COMPONENT/$RUN)}
export COMINcmc_regional=${COMINcmc_regional:-$COMIN/prep/$COMPONENT/$RUN}
export COMINdwd=${COMINdwd:-$COMIN/prep/$COMPONENT/$RUN}
export COMINecmwf=${COMINecmwf:-$COMIN/prep/$COMPONENT/$RUN}
export COMINfnmoc=${COMINfnmoc:-$COMIN/prep/$COMPONENT/$RUN}
export COMINimd=${COMINimd:-$COMIN/prep/$COMPONENT/$RUN}
export COMINjma=${COMINjma:-$COMIN/prep/$COMPONENT/$RUN}
export COMINmetfra=${COMINmetfra:-$COMIN/prep/$COMPONENT/$RUN}
export COMINukmet=${COMINukmet:-$COMIN/prep/$COMPONENT/$RUN}
##export COMOUT=${COMOUT:-$(compath.py -o $NET/$evs_ver/$STEP/$COMPONENT)}
export COMOUT=/lfs/h2/emc/vpppg/save/mallory.row/verification/global/evs_test/$envir/com/$NET/$evs_ver/$STEP/$COMPONENT
export COMOUTsmall=$COMOUT/$RUN.$VDATE/$MODELNAME/$VERIF_CASE
export COMOUTfinal=$COMOUT/$MODELNAME.$VDATE
mkdir -p $COMOUT $COMOUTsmall $COMOUTfinal

#######################################################################
# Execute the script
#######################################################################
env

if [ $RUN = atmos ]; then
    $HOMEevs/scripts/global_det/stats/exevs_global_det_${RUN}_${VERIF_CASE}_stats.sh
else
    $HOMEevs/scripts/global_det/stats/exevs_global_det_${RUN}_stats.sh
fi
export err=$?; err_chk

cat $pgmout

msg="JOB $job HAS COMPLETED NORMALLY."
postmsg "$jlogfile" "$msg"

if [ "$KEEPDATA" != "YES" ] ; then
  cd $DATAROOT
  rm -rf $DATA
fi

date
