#!/bin/bash
###############################################################################
# Job Name: JEVS_RTOFS_HEADLINE_PLOTS
# Purpose: To create headline score plots for RTOFS forecast verifications
#    using MET/METplus.
# Author: L. Gwen Chen (lichuan.chen@noaa.gov)
###############################################################################

set -x

# set up paths
export FIXevs=${FIXevs:-$HOMEevs/fix/logos}
export USHevs=${USHevs:-$HOMEevs/ush/$COMPONENT}
export CONFIGevs=${CONFIGevs:-$HOMEevs/parm/metplus_config/$COMPONENT}

# define COMIN/COMOUT variables
export COMIN=${COMIN:-$(compath.py $envir/com/$NET/${evs_ver})}
export COMINstats=${COMINstats:-$COMIN/stats/$COMPONENT}
export COMOUT=${COMOUT:-$(compath.py $NET/${evs_ver})}
export COMOUTplots=${COMOUTplots:-$COMOUT/$STEP/$COMPONENT/$COMPONENT.$VDATE}
export DATA=${DATA:-$DATAROOT/$NET/${evs_ver}}

mkdir -p $COMOUT $COMOUTplots
mkdir -p $DATA/$STEP/$COMPONENT/$COMPONENT.$VDATE

# make headline score plots
$HOMEevs/scripts/$COMPONENT/$STEP/exevs_${COMPONENT}_headline_${STEP}.sh

################################# END OF JOB ##################################
