#!/bin/bash
###############################################################################
# Job Name: JEVS_RTOFS_PLOTS
# Purpose: To create plots for RTOFS forecast verification using MET/METplus.
# Author: L. Gwen Chen (lichuan.chen@noaa.gov)
###############################################################################

set -x

# set up paths
export FIXevs=${FIXevs:-$EVS/fix/logos}
export USHevs=${USHevs:-$EVS/ush/$COMPONENT}
export CONFIGevs=${CONFIGevs:-$EVS/parm/metplus_config/$COMPONENT}

# define COMIN/COMOUT variables
export COMIN=${COMIN:-$(compath.py $envir/com/$NET/${evs_ver})}
export COMOUT=${COMOUT:-$(compath.py $NET/${evs_ver})}
export COMOUTfinal=${COMOUTfinal:-$COMOUT/stats/$COMPONENT/$COMPONENT.$VDATE}
export COMOUTplots=${COMOUTplots:-$COMOUT/$STEP/$COMPONENT/$COMPONENT.$VDATE}

# make plots; run scripts for each RUN;
# RUN is the validation source: ghrsst, smos, smap etc.
for rcase in ghrsst smos smap aviso buoys; do
  export RUN=$rcase

  if [ $RUN = 'ghrsst' ] ; then
    export OBTYPE=GHRSST
    export VAR=SST
    export VERIF_CASE=grid2grid
  fi

  if [ $RUN = 'smos' ] ; then
    export OBTYPE=SMOS
    export VAR=SSS
    export VERIF_CASE=grid2grid
  fi

  if [ $RUN = 'smap' ] ; then
    export OBTYPE=SMAP
    export VAR=SSS
    export VERIF_CASE=grid2grid
  fi

  if [ $RUN = 'aviso' ] ; then
    export OBTYPE=AVISO
    export VAR=SSH
    export VERIF_CASE=grid2grid
  fi

  if [ $RUN = 'buoys' ] ; then
    export OBTYPE=SFCSHP
    export VAR=SST
    export VERIF_CASE=grid2obs
  fi

  $EVS/scripts/$COMPONENT/$STEP/exevs_${COMPONENT}_seasfc_${STEP}.sh
done

for rcase in osisaf; do
  export RUN=$rcase
  export OBTYPE=OSISAF
  export VAR=SIC
  export VERIF_CASE=grid2grid

  $EVS/scripts/$COMPONENT/$STEP/exevs_${COMPONENT}_seaice_${STEP}.sh
done

################################# END OF JOB ##################################
