#!/bin/bash
###############################################################################
# Job Name: JEVS_RTOFS_PREP
# Purpose: To pre-process RTOFS forecast data into the same spatial and
#          temporal scales as validation data.
# Author: L. Gwen Chen (lichuan.chen@noaa.gov)
###############################################################################

set -x

########################################
# Preliminary data setup step
########################################

export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-YES}
export SENDECF=${SENDECF:-YES}

# ###################################
# SET SHELL PROCESSING VARIABLES
# ###################################
export PS4='$SECONDS + '
date

###########################################################
# obtain unique LSF id (jobid) and make temp directories
###########################################################
export pid=$$

export DATA=${DATA:-${DATAROOT:?}/${jobid:?}}
rm -rf $DATA
mkdir -p $DATA
cd $DATA

# Determine Job Output Name on System
####################################
export pgmout="OUTPUT.${pid}"

export cycle=t00z

###################################
# Set EVS directories
####################################
export HOMEevs=${HOMEevs:-${PACKAGEROOT}/evs.${evs_ver}}
export EXECevs=${EXECevs:-$HOMEevs/exec}
export FIXevs=${FIXevs:-$HOMEevs/fix}
export PARMevs=${PARMevs:-$HOMEevs/parm}
export SCRIPTSevs=${SCRIPTSevs:-$HOMEevs/scripts}
export USHevs=${USHevs:-$HOMEevs/ush}
export MASKS=${MASKS:-$FIXevs/masks}

# Run setpdy and initialize PDY variables
setpdy.sh
. ./PDY

export VDATE=${VDATE:-$PDYm1}

# set up paths
export FIXevs=${FIXevs:-$HOMEevs/fix/cdo_grids}
export USHevs=${USHevs:-$HOMEevs/ush/$COMPONENT}
export CONFIGevs=${CONFIGevs:-$HOMEevs/parm/metplus_config/$COMPONENT}

# define COMIN/COMOUT variables
export COMIN=${COMIN:-$(compath.py $envir/com/$NET/${evs_ver})}
export COMINobs=${DCOMROOT:-"/lfs/h1/ops/dev/dcom"}
export COMINrtofs=${COMINrtofs:-$(compath.py $envir/com/$COMPONENT/${rtofs_ver})}
export COMOUT=${COMOUT:-$(compath.py $NET/${evs_ver})}
export COMOUTprep=${COMOUTprep:-$COMOUT/$STEP/$COMPONENT}
export DATA=${DATA:-$DATAROOT/$NET/${evs_ver}}

mkdir -d $COMOUT $COMOUTprep

# run scripts
#  get RTOFS production data from /com
$HOMEevs/scripts/$COMPONENT/$STEP/exevs_${COMPONENT}_${STEP}.sh

#  convert RTOFS forecast data into lat-lon grids for each RUN;
#  RUN is the validation source: ghrsst, smos, smap etc.
for rcase in ghrsst smos smap aviso osisaf ndbc argo; do
  export RUN=$rcase
  $HOMEevs/scripts/$COMPONENT/$STEP/exevs_${COMPONENT}_fcst_${STEP}.sh
done

#  process obs data
$HOMEevs/scripts/$COMPONENT/$STEP/exevs_${COMPONENT}_obs_${STEP}.sh

export err=$?; err_chk

if [ -e "$pgmout" ]; then
    cat $pgmout
fi

msg="JOB $job HAS COMPLETED NORMALLY."
postmsg "$msg"

if [ "$KEEPDATA" != "YES" ] ; then
  cd $DATAROOT
  rm -rf $DATA
fi

date

################################# END OF JOB ##################################
