#!/bin/ksh
#  JOB card cerated for running METPlus-based NARRE verifications
#   By Binbin Zhou, IMSG@EMC/NCEP
#   June 2, 2022
#
set -xa
#######################################################
#######################################################


export RUN_ENVIR=${RUN_ENVIR:-nco}
export SENDECF=${SENDECF:-YES}

###############################
# Specify RUN name
###############################
export NET=evs
export RUN=narre

###############################################################
# This block can be modified for different Production test
# environment. This is used for operational testings
###############################################################
if [ "$RUN_ENVIR" = nco -o "$RUN_ENVIR" = para ] ; then
  if [ $envir != "prod" ] ; then
    export SENDDBN=${SENDDBN:-NO}
    export DBNLOG=${DBNLOG:-YES}
    export DATA_IN=${DATA_IN:-$DATAROOT}
  fi
fi


#####################################################################################
# This block is for Developer's test run:
# Run config file to get input parameters
# This config file should define the following variables
# DATA_IN: Location of working directory, default to $DATAROOT
# SENDECF: If the job is to be running using ecFlow, default to YES
# SENDDBN: Set to NO for developers, default to YES
# COM_IN:  Directory for input files, default to /com/$NET/${envir}
# COM_OUT: Directory for output file, default to /com/$NET/${envir}
# gespath: Directory for the guess or restart files, default to /nwges/${envir}
#####################################################################################
if [ "$RUN_ENVIR" = dev ] ; then   ### For Developers
  . $HOMEevs/parm/evs_config_dev/narre/config.evs.standalone
else
  . $HOMEevs/parm/evs_config/narre/config.evs.prod
fi

# ###################################
# SET SHELL PROCESSING VARIABLES
# ###################################
export PS4='$SECONDS + '
date

###########################################################
# obtain unique process id (pid) and make temp directories
###########################################################
export pid=$$
export COM_IN=${COM_IN:-$COMROOT/evs/${evs_ver}}
export COM_OUT=${COM_IN}
export DATA_IN=${DATA_IN:-$DATAROOT}
export DATA=$DATA_IN/evs-narre-g2o_stats_${envir}.$$
mkdir -p $DATA
#export DATA=$DATA_IN/evs-NARRE-g2o_stats_${envir}

cd $DATA
####################################
# File To Log Msgs
####################################
export jlogfile=${jlogfile:-${DATA}/jlogfile}

####################################
# Determine Job Output Name on System
####################################
export outid="LL$job"
export jobid="${outid}.o${pid}"
export pgmout="OUTPUT.${pid}"

export cycle=t${cyc}z

##################################################
# SAVEGES  - Copy Files From TMPDIR to $GESdir
# SENDECF  - Flag Events on ECF
# SENDCOM  - Copy Files From TMPDIR to $COMOUT
# SENDDBN  - Issue DBNet Client Calls
##################################################
export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-YES}
export SENDECF=${SENDECF:-YES}

####################################
# Specify codes and scripts locaton
####################################

# Run setpdy and initialize PDY variables
setpdy.sh
. $DATA/PDY

export vday=${vday:-$PDYm1}


##################################
# Define COMIN/COMOUT variables
##################################
#export COM_IN=${COM_IN:-$COMROOT/evs/${envir}}

export GATHER_STAT=${COM_OUT}/stats/narre/narre.${vday}
export SMALL_STAT=${COM_OUT}/stats/narre/grid2obs.${vday}

mkdir -p $GATHER_STAT $SMALL_STAT

export GRID2OBS_CONF=$PARMevs/metplus_config/narre/grid2obs/stats
export MET_CONFIG=${METPLUS_BASE}/parm/met_config
export maskpath=$MASKS

export JLOGFILE="${output_base}/logs/metplus_jlogfile_narre"
#export maskpath=$FIXevs/vx_masks


sh $HOMEevs/scripts/narre/stats/exevs_narre_stats.sh 

msg="JOB $job HAS COMPLETED NORMALLY."
postmsg "$jlogfile" "$msg"

#if [ "$KEEPDATA" != "YES" ] ; then
#  cd $DATAROOT
#  rm -rf $DATA
#fi

#date

