#!/bin/ksh
#  JOB card cerated for running METPlus-based NARRE verifications
#   By Binbin Zhou, IMSG@EMC/NCEP
#   June 2, 2022
#
set -xa
#######################################################
#######################################################

export cyc=${cyc:-"00"}
export cycle=${cycle:-t${cyc}z}

export pid=$$
export DATA=${DATA:-${DATAROOT}/${jobid:?}}
mkdir -p $DATA
cd $DATA

# Run setpdy and initialize PDY variables
setpdy.sh
. $DATA/PDY

export VDATE=${VDATE:-$PDYm1}


##################################################
# SAVEGES  - Copy Files From TMPDIR to $GESdir
# SENDECF  - Flag Events on ECF
# SENDCOM  - Copy Files From TMPDIR to $COMOUT
# SENDDBN  - Issue DBNet Client Calls
##################################################
export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-YES}
export SENDECF=${SENDECF:-YES}


export COMIN=${COMIN:-$(compath.py  $envir/com/$NET/$evs_ver)}
export COMINnarre=${COMINnarre:-$(compath.py  $envir/com/narre/$narre_ver)}
export COMINobs=${COMINobs:-$(compath.py  $envir/com/obsproc/$obsproc_ver)}
export COMOUT=${COMOUT:-$(compath.py -o $envir/com/$NET/${evs_ver})}/${STEP}/${COMPONENT}
mkdir -p $COMOUT

export COMOUTfinal=${COMOUT}/${MODELNAME}.${VDATE}
export COMOUTsmall=${COMOUT}/${RUN}.${VDATE}/${MODELNAME}/${VERIF_CASE}
mkdir -p $COMOUTfinal $COMOUTsmall

export HOMEevs=${HOMEevs:-${PACKAGEROOT}/evs.${evs_ver}}
export EXECevs=$HOMEevs/exec
export PARMevs=$HOMEevs/parm
export USHevs=$HOMEevs/ush
export FIXevs=${FIXevs:-$HOMEevs/fix}
export MASKS=$FIXevs/masks


###########################################################
# obtain unique process id (pid) and make temp directories
###########################################################


####################################
# File To Log Msgs
####################################
export jlogfile=${jlogfile:-${DATA}/jlogfile}

####################################
# Determine Job Output Name on System
####################################
export outid="LL$job"
export jobid="${outid}.o${pid}"
export pgmout="OUTPUT.${pid}"

####################################
# Specify codes and scripts locaton
####################################


$HOMEevs/scripts/${COMPONENT}/${STEP}/exevs_${MODELNAME}_${STEP}.sh 

msg="JOB $job HAS COMPLETED NORMALLY."
postmsg "$jlogfile" "$msg"

if [ "$KEEPDATA" != "YES" ] ; then
  cd $DATAROOT
  rm -rf $DATA
fi

#date

