#!/bin/ksh
#  JOB card cerated for running METPlus-based Global enesmble verifications
#   By Binbin Zhou, IMSG@EMC/NCEP
#   Feb 2, 2022
#
set -xa
#######################################################
#######################################################

export cycle=t${cyc}z

export pid=$$
export DATA=${DATA:-${DATAROOT:?}/${jobid:?}}
rm -rf $DATA
mkdir -p $DATA
cd $DATA


# Run setpdy and initialize PDY variables
setpdy.sh
. $DATA/PDY

if [ $RUN = atmos ] ; then
  export INITDATE=${INITDATE:-$PDYm2}
fi


export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-YES}
export SENDECF=${SENDECF:-YES}

export COMIN=${COMIN:-$(compath.py $envir/com/$NET/$evs_ver)}
export COMINgfsanl=${COMINgfs:-$(compath.py $envir/com/gfs/${gfs_ver})}
export COMINgefs=${COMINgefs:-$(compath.py $envir/com/gefs/${gefs_ver})}
export COMINnaefs=${COMINnaefs:-$(compath.py $envir/com/naefs/${naefs_ver})}
export DCOMIN=${DCOMIN:-${DCOMROOT}}
export COMINccpa=${COMINccpa:-$(compath.py $envir/com/ccpa/${ccpa_ver})}
export COMINcmce=$COMINnaefs
export COMINprepbufr=${COMINprepbufe:-$(compath.py $envir/com/obsproc/${obsproc_ver})}
export COMINsnow=${DCOMIN}
export COMINosi_saf=${COMINosi_saf:-/lfs/h1/ops/dev/dcom}
export COMINsst=${COMINsst:-/lfs/h1/ops/dev/dcom} 

export COMINgefs_bc=${COMINgefs_bc:-$COMINnaefs}
export COMINcmce_bc=${DCOMIN}
export COMIN_gefs=${COMIN_gefs:-${COMIN}/${STEP}/${COMPONENT}/atmos.${INITDATE}/gefs}
export COMIN_gefs_bc=${COMIN_gefs_bc:-${COMIN}/${STEP}/${COMPONENT}/atmos.${INITDATE}/gefs_bc}
export COMIN_cmce=${COMIN_cmce:-${COMIN}/${STEP}/${COMPONENT}/atmos.${INITDATE}/cmce}
export COMIN_cmce_bc=${COMIN_cmce_bc:-${COMIN}/${STEP}/${COMPONENT}/atmos.${INITDATE}/cmce_bc}


export COMOUT=${COMOUT:-$(compath.py -o $envir/com/$NET/${evs_ver})}/$STEP/${COMPONENT}
mkdir -p $COMOUT

export COMOUT_gefs=${COMOUT_gefs:-${COMOUT}/${RUN}.${INITDATE}/gefs}
export COMOUT_cmce=${COMOUT_cmce:-${COMOUT}/${RUN}.${INITDATE}/cmce}
export COMOUT_ecme=${COMOUT_ecme:-${COMOUT}/${RUN}.${INITDATE}/ecme}
export COMOUT_naefs=${COMOUT}
export COMOUT_osi_saf=${COMOUT_osi_saf:-${COMOUT}/${RUN}.${INITDATE}/osi_saf}
export COMOUT_gefs_bc=${COMOUT_gefs_bc:-${COMOUT}/${RUN}.${INITDATE}/gefs_bc}
export COMOUT_cmce_bc=${COMOUT_cmce_bc:-${COMOUT}/${RUN}.${INITDATE}/cmce_bc}

mkdir -p $COMOUT_gefs $COMOUT_cmce $COMOUT_ecme $COMOUT_osi_saf $COMOUT_gefs_bc $COMOUT_cmce_bc

export HOMEevs=${HOMEevs:-${PACKAGEROOT}/evs_gens.${evs_ver}}
export EXECevs=$HOMEevs/exec
export PARMevs=$HOMEevs/parm
export USHevs=$HOMEevs/ush
export SCRIPTerf=$HOMEevs/scripts
export FIXevs=${FIXevs:-$HOMEevs/fix}

####################################
# Determine Job Output Name on System
####################################
export outid="LL$job"
export jobid="${outid}.o${pid}"
export pgmout="OUTPUT.${pid}"


#$HOMEevs/scripts/global_ens/${STEP}/exevs_${COMPONENT}_${RUN}_${STEP}.sh
$HOMEevs/scripts/global_ens/${STEP}/exevs_${COMPONENT}_${MODELNAME}_${RUN}_${STEP}.sh

msg="JOB $job HAS COMPLETED NORMALLY."
postmsg "$msg"

if [ "$KEEPDATA" != "YES" ] ; then
  cd $DATAROOT
  rm -rf $DATA
fi

date

