#!/bin/bash

#################################
# SET SHELL PROCESSING VARIABLES 
#################################
set -x
export PS4='+ $SECONDS + '
date

#########################################################
# obtain unique LSF id (jobid) and make temp directories 
#########################################################
export DATA=${DATA:-${DATAROOT:?}/${jobid:?}}
mkdir -p $DATA
cd $DATA

##########################################
# Run setpdy and initialize PDY variables 
##########################################
export cycle=${cycle:-t00z}
setpdy.sh 20
. ./PDY
export INITDATE=${INITDATE:-${PDYm1}}
export NEXTDATE=${NEXTDATE:-${PDY}}

####################################
# Set data directives
####################################
export SENDECF=${SENDECF:-YES}
export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-NO}

####################################
# Set EVS directories               
####################################
export HOMEevs=${HOMEevs:-${PACKAGEROOT}/evs.${model_ver}}
export EXECevs=${EXECevs:-$HOMEevs/exec}
export FIXevs=${FIXevs:-$HOMEevs/fix}
export PARMevs=${PARMevs:-$HOMEevs/parm}
export USHevs=${USHevs:-$HOMEevs/ush}

####################################
# Define NET/RUN variables          
####################################
export NET=${NET:-evs}
export MODEL=${MODEL:-evs}
export STEP=${STEP:-prep}
export COMPONENT=${COMPONENT:-global_ens}
export MODELNAME=${MODELNAME:-gefs}
export MODNAM=echo $MODELNAME | tr '[a-z]' '[A-Z]'
export OBTYPE=${OBTYPE:-GDAS}
export RUN=${RUN:-wave}
export VERIF_CASE=${VERIF_CASE:-grid2obs}

####################################
# Define COMIN/COMOUT variables     
####################################
export COMIN=${COMIN:-$(compath.py ${envir}/com/${NET}/${evs_ver})}
export COMINmodel=${COMINmodel:-$(compath.py ${envir}/com/${MODELNAME}/${gefs_ver})} 
export COMINgdas=${COMINgdas:-$(compath.py ${envir}/com/obsproc/${obsproc_ver}/gdas)}

export COMOUT=${COMOUT:-${COMIN}/${STEP}/${COMPONENT}/${RUN}}
export ARCgefs=${COMOUT}.${INITDATE}/${MODELNAME}/${VERIF_CASE}

# make the directory where the ARCgefs and gdasnc will be kept
mkdir -p ${COMOUT}.${INITDATE}/${MODELNAME}/${VERIF_CASE}

export jlogfile=${DATA}/${MODELNAME}_${RUN}_PB2NC.log

####################################
# Execute the script                
####################################
$HOMEevs/scripts/global_ens/prep/exevs_global_ens_wave_grid2obs_prep.sh
export err=$?; err_chk

msg="JOB $job HAS COMPLETED NORMALLY."
postmsg "$jlogfile" "$msg"

if [ "$KEEPDATA" != "YES" ] ; then
  rm -rf $DATA
fi

date
