#!/bin/ksh

########################################
# Preliminary data setup step
########################################
set -xa

export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-YES}
export SENDECF=${SENDECF:-YES}

export cycle=t${cyc}z 
export DATA_IN=${DATA_IN:-$DATAROOT}
jobid=evs_${MODELNAME}_${VERIF_CASE}_${STEP}.$$

export DATA=${DATA:-$DATA_IN/${jobid}}
mkdir -p $DATA
cd $DATA

setpdy.sh
. $DATA/PDY

if [ $MODELNAME = sref ] ; then
  export VDATE=${VDATE:-$PDYm2}
fi


export COMIN=${COMIN:-$(compath.py  $NET/$evs_ver)}/prep/$COMPONENT/$RUN
export COMINsref=${COMINsref:-$(compath.py  sref/$sref_ver)}
export COMINprepbufr=${COMINprepbufr:-$(compath.py  obsproc/${obsproc_ver})}
export COMINccpa=${COMINccpa:-$(compath.py  ccpa/${ccpa_ver})}
export COMINsrefmean=${COMINsrefmean:-$(compath.py  $NET/$evs_ver)}/prep/$COMPONENT

export COMOUT=${COMOUT:-$(compath.py -o ${NET}/${evs_ver})}/$STEP/$COMPONENT
mkdir -p $COMOUT


export COMOUTfinal=${COMOUT}/${MODELNAME}.${VDATE}
export COMOUTsmall=${COMOUT}/${RUN}.${VDATE}/${MODELNAME}/${VERIF_CASE}
mkdir -p $COMOUTfinal $COMOUTsmall


export HOMEevs=${HOMEevs:-${PACKAGEROOT}/evs.${evs_ver}}
export EXECevs=${EXECevs:-$HOMEevs/exec}
export PARMevs=${PARMevs:-$HOMEevs/parm}
export USHevs=${USHevs:-$HOMEevs/ush}
export FIXevs=${FIXevs:-/lfs/h1/ops/prod/packages/evs.${evs_ver}/fix}
export MASKS=$FIXevs/masks

export pid=$$


# ###################################
# SET SHELL PROCESSING VARIABLES
# ###################################
export PS4='$SECONDS + '
date


####################################
# Determine Job Output Name on System
####################################
export pgmout="OUTPUT.${pid}"


# STEP->prep/stats, MODELNAME->sref, COMPONENT->mesoscale, VERIF_CASE->grid2grid/grid2obs/precip
$HOMEevs/scripts/${COMPONENT}/${STEP}/exevs_${MODELNAME}_${VERIF_CASE}_${STEP}.sh

cat $pgmout

msg="JOB $job HAS COMPLETED NORMALLY."
postmsg "$jlogfile" "$msg"

if [ "$KEEPDATA" != "YES" ] ; then
  cd $DATAROOT
  rm -rf $DATA
fi

