#!/bin/sh

########################################
# Preliminary data setup step
########################################
set -xa

####################################
# SET SHELL PROCESSING VARIABLES
####################################
export PS4='$SECONDS + '
date

###########################################################
# obtain unique LSF id (jobid) and make temp directories
###########################################################
export pid=$$
export DATA=${DATA:-${DATAROOT:?}/${jobid:?}}
mkdir -p $DATA
cd $DATA

####################################
# Determine Job Output Name on System
####################################
export pgmout="OUTPUT.${pid}"

####################################
# Set EVS directories
####################################
export HOMEevs=${HOMEevs:-${PACKAGEROOT}/evs.${model_ver}}
export EXECevs=${EXECevs:-$HOMEevs/exec}
export FIXevs=${FIXevs:-$HOMEevs/fix}
export PARMevs=${PARMevs:-$HOMEevs/parm}
export USHevs=${USHevs:-$HOMEevs/ush}

####################################
# Run setpdy and initialize PDY variables
####################################
export cycle=${cycle:-t${cyc}z}
setpdy.sh
. ./PDY
export INITDATE=$PDYm1

####################################
# Define NET/RUN variables
####################################
export NET=${NET:-evs}
export STEP=${STEP:-prep}
export COMPONENT=${COMPONENT:-global_det}
export RUN=${RUN:-atmos}

####################################
# Define COMIN/COMOUT variables
####################################
export COMIN=$COMROOT
#export COMOUT=$COMROOT/$NET/$evs_ver/$STEP/$COMPONENT/$RUN
export COMOUT=/lfs/h2/emc/stmp/$USER/evs_output/$envir/com/$NET/$evs_ver/$STEP/$COMPONENT/$RUN
mkdir -p $COMOUT.${INITDATE}

#######################################################################
# Execute the script
#######################################################################
env
$HOMEevs/scripts/global_det/prep/exevs_global_det_${RUN}_prep.sh
export err=$?; err_chk

cat $pgmout

msg="JOB $job HAS COMPLETED NORMALLY."
postmsg "$jlogfile" "$msg"

if [ "$KEEPDATA" != "YES" ] ; then
  cd $DATAROOT
  rm -rf $DATA
fi

date
