#!/usr/bin/env python3
"""
cam_plots_headline_graphx_defs.py
CONTRIBUTORS: Marcel Caron, marcel.caron@noaa.gov, NOAA/NWS/NCEP/EMC-VPPPGB
----------------------
Graphics definitions for the CAM Headline Plots jobs, used by the cam
component for headline plotting and job configuration.

Environment Variables (Inputs):
    (None required directly; see dependent scripts for context)

Outputs:
    - Provides the 'graphics' dictionary for CAM Headline plotting jobs.

This module is intended to be imported and used as part of the cam component's
plotting and job generation workflow for headline plots.
"""
graphics = {
    'cam':{
        'headline':{
            'metar':{
                'set1, rap?shift=-3, rrfs, rrfsmem1, rrfsmem2, rrfsmem3, rrfsmem4, rrfsmem5, hrrr': {
                    'lead_average':{
                        'DATE_TYPE':'INIT',
                        'VALID_BEG':'',
                        'VALID_END':'',
                        'INIT_BEG':'',
                        'INIT_END':'',
                        'VX_MASK_LIST':'CONUS_East,CONUS_Central,CONUS_South',
                        'EVAL_PERIODS':['last90days'],
                        'FCST_VALID_HOURS':[''],
                        'FCST_INIT_HOURS':['0'],
                        'VARIABLES':{
                            'sl1l2':{
                                'TMP2m':{
                                    'STATSs':['bcrmse,me'],
                                    'FCST_LEADS':['0,3,6,9,12,15,18,21,24'],
                                    'FCST_LEVEL':'Z2',
                                    'OBS_LEVEL':'Z2',
                                    'FCST_THRESHs':[''],
                                    'OBS_THRESHs':[''],
                                    'CONFIDENCE_INTERVALS':'False',
                                    'INTERP':'BILIN',
                                    'INTERP_PNTSs':[''],
                                },
                                'DPT2m':{
                                    'STATSs':['bcrmse,me'],
                                    'FCST_LEADS':['0,3,6,9,12,15,18,21,24'],
                                    'FCST_LEVEL':'Z2',
                                    'OBS_LEVEL':'Z2',
                                    'FCST_THRESHs':['',''],
                                    'OBS_THRESHs':['','>=283.15'],
                                    'CONFIDENCE_INTERVALS':'False',
                                    'INTERP':'BILIN',
                                    'INTERP_PNTSs':[''],
                                },
                            },
                            'vl1l2':{
                                'UGRD_VGRD10m':{
                                    'STATSs':['bcrmse,me'],
                                    'FCST_LEADS':['0,3,6,9,12,15,18,21,24'],
                                    'FCST_LEVEL':'Z10',
                                    'OBS_LEVEL':'Z10',
                                    'FCST_THRESHs':[''],
                                    'OBS_THRESHs':[''], 
                                    'CONFIDENCE_INTERVALS':'False',
                                    'INTERP':'BILIN',
                                    'INTERP_PNTSs':[''],
                                }
                            },
                        }
                    },
                },
                'set2, rap?shift=-3, rrfs, rrfsmem1, rrfsmem2, rrfsmem3, rrfsmem4, rrfsmem5, hrrr': {
                    'lead_average':{
                        'DATE_TYPE':'INIT',
                        'VALID_BEG':'',
                        'VALID_END':'',
                        'INIT_BEG':'',
                        'INIT_END':'',
                        'VX_MASK_LIST':'CONUS_West',
                        'EVAL_PERIODS':['last90days'],
                        'FCST_VALID_HOURS':[''],
                        'FCST_INIT_HOURS':['0'],
                        'VARIABLES':{
                            'sl1l2':{
                                'TMP2m':{
                                    'STATSs':['bcrmse,me'],
                                    'FCST_LEADS':['0,3,6,9,12,15,18,21,24'],
                                    'FCST_LEVEL':'Z2',
                                    'OBS_LEVEL':'Z2',
                                    'FCST_THRESHs':[''],
                                    'OBS_THRESHs':[''],
                                    'CONFIDENCE_INTERVALS':'False',
                                    'INTERP':'BILIN',
                                    'INTERP_PNTSs':[''],
                                },
                                'DPT2m':{
                                    'STATSs':['bcrmse,me'],
                                    'FCST_LEADS':['0,3,6,9,12,15,18,21,24'],
                                    'FCST_LEVEL':'Z2',
                                    'OBS_LEVEL':'Z2',
                                    'FCST_THRESHs':['',''],
                                    'OBS_THRESHs':['','>=277.594'],
                                    'CONFIDENCE_INTERVALS':'False',
                                    'INTERP':'BILIN',
                                    'INTERP_PNTSs':[''],
                                },
                            },
                            'vl1l2':{
                                'UGRD_VGRD10m':{
                                    'STATSs':['bcrmse,me'],
                                    'FCST_LEADS':['0,3,6,9,12,15,18,21,24'],
                                    'FCST_LEVEL':'Z10',
                                    'OBS_LEVEL':'Z10',
                                    'FCST_THRESHs':[''],
                                    'OBS_THRESHs':[''], 
                                    'CONFIDENCE_INTERVALS':'False',
                                    'INTERP':'BILIN',
                                    'INTERP_PNTSs':[''],
                                }
                            },
                        }
                    },
                },
                'set3, rap?shift=-3, rrfs, rrfsmem1, rrfsmem2, rrfsmem3, rrfsmem4, rrfsmem5, hrrr': {
                    'lead_average':{
                        'DATE_TYPE':'INIT',
                        'VALID_BEG':'',
                        'VALID_END':'',
                        'INIT_BEG':'',
                        'INIT_END':'',
                        'VX_MASK_LIST':'Alaska',
                        'EVAL_PERIODS':['last90days'],
                        'FCST_VALID_HOURS':[''],
                        'FCST_INIT_HOURS':['6'],
                        'VARIABLES':{
                            'sl1l2':{
                                'TMP2m':{
                                    'STATSs':['bcrmse,me'],
                                    'FCST_LEADS':['0,3,6,9,12,15,18,21,24'],
                                    'FCST_LEVEL':'Z2',
                                    'OBS_LEVEL':'Z2',
                                    'FCST_THRESHs':[''],
                                    'OBS_THRESHs':[''],
                                    'CONFIDENCE_INTERVALS':'False',
                                    'INTERP':'BILIN',
                                    'INTERP_PNTSs':[''],
                                },
                                'DPT2m':{
                                    'STATSs':['bcrmse,me'],
                                    'FCST_LEADS':['0,3,6,9,12,15,18,21,24'],
                                    'FCST_LEVEL':'Z2',
                                    'OBS_LEVEL':'Z2',
                                    'FCST_THRESHs':['',''],
                                    'OBS_THRESHs':['','>=272.039'],
                                    'CONFIDENCE_INTERVALS':'False',
                                    'INTERP':'BILIN',
                                    'INTERP_PNTSs':[''],
                                },
                            },
                            'vl1l2':{
                                'UGRD_VGRD10m':{
                                    'STATSs':['bcrmse,me'],
                                    'FCST_LEADS':['0,3,6,9,12,15,18,21,24'],
                                    'FCST_LEVEL':'Z10',
                                    'OBS_LEVEL':'Z10',
                                    'FCST_THRESHs':[''],
                                    'OBS_THRESHs':[''], 
                                    'CONFIDENCE_INTERVALS':'False',
                                    'INTERP':'BILIN',
                                    'INTERP_PNTSs':[''],
                                }
                            },
                        }
                    },
                },
                'set4, rrfs, rrfsmem1, rrfsmem2, rrfsmem3, rrfsmem4, rrfsmem5': {
                    'lead_average':{
                        'DATE_TYPE':'INIT',
                        'VALID_BEG':'',
                        'VALID_END':'',
                        'INIT_BEG':'',
                        'INIT_END':'',
                        'VX_MASK_LIST':'Hawaii',
                        'EVAL_PERIODS':['last90days'],
                        'FCST_VALID_HOURS':[''],
                        'FCST_INIT_HOURS':['0'],
                        'VARIABLES':{
                            'sl1l2':{
                                'TMP2m':{
                                    'STATSs':['bcrmse,me'],
                                    'FCST_LEADS':['0,3,6,9,12,15,18,21,24'],
                                    'FCST_LEVEL':'Z2',
                                    'OBS_LEVEL':'Z2',
                                    'FCST_THRESHs':[''],
                                    'OBS_THRESHs':[''],
                                    'CONFIDENCE_INTERVALS':'False',
                                    'INTERP':'BILIN',
                                    'INTERP_PNTSs':[''],
                                },
                                'DPT2m':{
                                    'STATSs':['bcrmse,me'],
                                    'FCST_LEADS':['0,3,6,9,12,15,18,21,24'],
                                    'FCST_LEVEL':'Z2',
                                    'OBS_LEVEL':'Z2',
                                    'FCST_THRESHs':['',''],
                                    'OBS_THRESHs':['','>=288.706'],
                                    'CONFIDENCE_INTERVALS':'False',
                                    'INTERP':'BILIN',
                                    'INTERP_PNTSs':[''],
                                },
                            },
                            'vl1l2':{
                                'UGRD_VGRD10m':{
                                    'STATSs':['bcrmse,me'],
                                    'FCST_LEADS':['0,3,6,9,12,15,18,21,24'],
                                    'FCST_LEVEL':'Z10',
                                    'OBS_LEVEL':'Z10',
                                    'FCST_THRESHs':[''],
                                    'OBS_THRESHs':[''], 
                                    'CONFIDENCE_INTERVALS':'False',
                                    'INTERP':'BILIN',
                                    'INTERP_PNTSs':[''],
                                }
                            },
                        }
                    },
                },
            }
        }
    },
}
