generate_stats_jobs_dict = {
    'WEASD': {
        'nohrsc': {
            'hireswarw': {
                'var1_fcst_name': 'HGT',
                'var1_fcst_levels': 'Z0',
                'var1_fcst_thresholds': '',
                'var1_fcst_options': '',
                'var1_obs_name': 'ASNOW',
                'var1_obs_levels': 'Z0',
                'var1_obs_thresholds': '',
                'var1_obs_options': '',
            },
            'hireswarwmem2': {
                'var1_fcst_name': 'HGT',
                'var1_fcst_levels': 'Z0',
                'var1_fcst_thresholds': '',
                'var1_fcst_options': '',
                'var1_obs_name': 'HGT',
                'var1_obs_levels': 'Z0',
                'var1_obs_thresholds': '',
                'var1_obs_options': '',
            },
            'hireswfv3': {
                'var1_fcst_name': 'HGT',
                'var1_fcst_levels': 'Z0',
                'var1_fcst_thresholds': '',
                'var1_fcst_options': '',
                'var1_obs_name': 'HGT',
                'var1_obs_levels': 'Z0',
                'var1_obs_thresholds': '',
                'var1_obs_options': '',
            },
            'hrrr': {
                'var1_fcst_name': 'HGT',
                'var1_fcst_levels': 'Z0',
                'var1_fcst_thresholds': '',
                'var1_fcst_options': '',
                'var1_obs_name': 'HGT',
                'var1_obs_levels': 'Z0',
                'var1_obs_thresholds': '',
                'var1_obs_options': '',
            },
            'namnest': {
                'var1_fcst_name': 'HGT',
                'var1_fcst_levels': 'Z0',
                'var1_fcst_thresholds': '',
                'var1_fcst_options': '',
                'var1_obs_name': 'HGT',
                'var1_obs_levels': 'Z0',
                'var1_obs_thresholds': '',
                'var1_obs_options': '',
            },
            'output_types': {
                'CTC': 'NONE',
                'SL1L2': 'STAT',
                'VL1L2': 'NONE',
                'CNT': 'NONE',
                'VCNT': 'NONE',
                'NBRCNT': 'NONE',
            }
        },
    },
}
