import os
from datetime import datetime
graphics = {
    'cam':{
        'precip':{
            'ccpa':{
                'namnest, hireswarw, hireswarwmem2, hireswfv3, hrrr':{
                    'threshold_average':{
                        'DATE_TYPE':'INIT',
                        'VALID_BEG':'',
                        'VALID_END':'',
                        'INIT_BEG':'',
                        'INIT_END':'',
                        'VX_MASK_LIST':'CONUS,CONUS_East,CONUS_West,CONUS_Central,CONUS_South',
                        'INTERP':'NEAREST',
                        'EVAL_PERIODS':['LAST31DAYS','LAST90DAYS'],
                        'FCST_VALID_HOURS':[''],
                        'FCST_INIT_HOURS':['0','12'],
                        'VARIABLES':{
                            'ctc':{
                                'APCP_01':{
                                    'STATSs':['fbias','ets'],
                                    'FCST_LEADS':['1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24'],
                                    'FCST_LEVEL':'A1',
                                    'OBS_LEVEL':'A1',
                                    'FCST_THRESHs':['>=0.254,>=1.27,>=2.54,>=6.35,>=12.7,>=19.05,>=25.4'],
                                    'OBS_THRESHs':['>=0.254,>=1.27,>=2.54,>=6.35,>=12.7,>=19.05,>=25.4'],
                                    'CONFIDENCE_INTERVALS':'True',
                                },
                                'APCP_03':{
                                    'STATSs':['fbias','ets'],
                                    'FCST_LEADS':['24','27','30','33','36','39','42','45','48','51','54','57','60'],
                                    'FCST_LEVEL':'A3',
                                    'OBS_LEVEL':'A3',
                                    'FCST_THRESHs':['>=0.254,>=1.27,>=2.54,>=6.35,>=12.7,>=19.05,>=25.4,>=50.8'],
                                    'OBS_THRESHs':['>=0.254,>=1.27,>=2.54,>=6.35,>=12.7,>=19.05,>=25.4,>=50.8'],
                                    'CONFIDENCE_INTERVALS':'True',
                                },
                                'APCP_24':{
                                    'STATSs':['fbias','ets'],
                                    'FCST_LEADS':['24','30','36','42','48','54','60'],
                                    'FCST_LEVEL':'A24',
                                    'OBS_LEVEL':'A24',
                                    'FCST_THRESHs':['>=0.254,>=2.54,>=6.35,>=12.7,>=25.4,>=38.1,>=50.8,>=76.2,>=101.6,>=152.4'],
                                    'OBS_THRESHs':['>=0.254,>=2.54,>=6.35,>=12.7,>=25.4,>=38.1,>=50.8,>=76.2,>=101.6,>=152.4'],
                                    'CONFIDENCE_INTERVALS':'True',
                                },
                            }
                        }
                    },
                    'performance_diagram':{
                        'DATE_TYPE':'INIT',
                        'VALID_BEG':'',
                        'VALID_END':'',
                        'INIT_BEG':'',
                        'INIT_END':'',
                        'VX_MASK_LIST':'CONUS,CONUS_East,CONUS_West,CONUS_Central,CONUS_South',
                        'INTERP':'NEAREST',
                        'EVAL_PERIODS':['LAST31DAYS','LAST90DAYS'],
                        'FCST_VALID_HOURS':[''],
                        'FCST_INIT_HOURS':['0','12'],
                        'VARIABLES':{
                            'ctc':{
                                'APCP_01':{
                                    'STATSs':['sratio,pod,csi'],
                                    'FCST_LEADS':['1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24'],
                                    'FCST_LEVEL':'A1',
                                    'OBS_LEVEL':'A1',
                                    'FCST_THRESHs':['>=0.254,>=1.27,>=2.54,>=6.35,>=12.7,>=19.05,>=25.4'],
                                    'OBS_THRESHs':['>=0.254,>=1.27,>=2.54,>=6.35,>=12.7,>=19.05,>=25.4'],
                                    'CONFIDENCE_INTERVALS':'True',
                                },
                                'APCP_03':{
                                    'STATSs':['sratio,pod,csi'],
                                    'FCST_LEADS':['24','27','30','33','36','39','42','45','48','51','54','57','60'],
                                    'FCST_LEVEL':'A3',
                                    'OBS_LEVEL':'A3',
                                    'FCST_THRESHs':['>=0.254,>=1.27,>=2.54,>=6.35,>=12.7,>=19.05,>=25.4,>=50.8'],
                                    'OBS_THRESHs':['>=0.254,>=1.27,>=2.54,>=6.35,>=12.7,>=19.05,>=25.4,>=50.8'],
                                    'CONFIDENCE_INTERVALS':'True',
                                },
                                'APCP_24':{
                                    'STATSs':['sratio,pod,csi'],
                                    'FCST_LEADS':['24','30','36','42','48','54','60'],
                                    'FCST_LEVEL':'A24',
                                    'OBS_LEVEL':'A24',
                                    'FCST_THRESHs':['>=0.254,>=2.54,>=6.35,>=12.7,>=25.4,>=38.1,>=50.8,>=76.2,>=101.6,>=152.4'],
                                    'OBS_THRESHs':['>=0.254,>=2.54,>=6.35,>=12.7,>=25.4,>=38.1,>=50.8,>=76.2,>=101.6,>=152.4'],
                                    'CONFIDENCE_INTERVALS':'True',
                                },
                            }
                        }
                    },
                }
            }
            'mrms':{
                'namnest, hireswarw, hireswarwmem2, hireswfv3, hrrr':{
                    'threshold_average':{
                        'DATE_TYPE':'INIT',
                        'VALID_BEG':'',
                        'VALID_END':'',
                        'INIT_BEG':'',
                        'INIT_END':'',
                        'VX_MASK_LIST':'Alaska',
                        'INTERP':'NEAREST',
                        'EVAL_PERIODS':['LAST31DAYS','LAST90DAYS'],
                        'FCST_VALID_HOURS':[''],
                        'FCST_INIT_HOURS':['0','12'],
                        'VARIABLES':{
                            'ctc':{
                                'APCP_01':{
                                    'STATSs':['fbias','ets'],
                                    'FCST_LEADS':['1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24'],
                                    'FCST_LEVEL':'A1',
                                    'OBS_LEVEL':'A1',
                                    'FCST_THRESHs':['>=0.254,>=1.27,>=2.54,>=6.35,>=12.7,>=19.05,>=25.4'],
                                    'OBS_THRESHs':['>=0.254,>=1.27,>=2.54,>=6.35,>=12.7,>=19.05,>=25.4'],
                                    'CONFIDENCE_INTERVALS':'True',
                                },
                                'APCP_03':{
                                    'STATSs':['fbias','ets'],
                                    'FCST_LEADS':['24','27','30','33','36','39','42','45','48','51','54','57','60'],
                                    'FCST_LEVEL':'A3',
                                    'OBS_LEVEL':'A3',
                                    'FCST_THRESHs':['>=0.254,>=1.27,>=2.54,>=6.35,>=12.7,>=19.05,>=25.4,>=50.8'],
                                    'OBS_THRESHs':['>=0.254,>=1.27,>=2.54,>=6.35,>=12.7,>=19.05,>=25.4,>=50.8'],
                                    'CONFIDENCE_INTERVALS':'True',
                                },
                                'APCP_24':{
                                    'STATSs':['fbias','ets'],
                                    'FCST_LEADS':['24','30','36','42','48','54','60'],
                                    'FCST_LEVEL':'A24',
                                    'OBS_LEVEL':'A24',
                                    'FCST_THRESHs':['>=0.254,>=2.54,>=6.35,>=12.7,>=25.4,>=38.1,>=50.8,>=76.2,>=101.6,>=152.4'],
                                    'OBS_THRESHs':['>=0.254,>=2.54,>=6.35,>=12.7,>=25.4,>=38.1,>=50.8,>=76.2,>=101.6,>=152.4'],
                                    'CONFIDENCE_INTERVALS':'True',
                                },
                            }
                        }
                    },
                    'performance_diagram':{
                        'DATE_TYPE':'INIT',
                        'VALID_BEG':'',
                        'VALID_END':'',
                        'INIT_BEG':'',
                        'INIT_END':'',
                        'VX_MASK_LIST':'Alaska',
                        'INTERP':'NEAREST',
                        'EVAL_PERIODS':['LAST31DAYS','LAST90DAYS'],
                        'FCST_VALID_HOURS':[''],
                        'FCST_INIT_HOURS':['0','12'],
                        'VARIABLES':{
                            'ctc':{
                                'APCP_01':{
                                    'STATSs':['sratio,pod,csi'],
                                    'FCST_LEADS':['1','2','3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24'],
                                    'FCST_LEVEL':'A1',
                                    'OBS_LEVEL':'A1',
                                    'FCST_THRESHs':['>=0.254,>=1.27,>=2.54,>=6.35,>=12.7,>=19.05,>=25.4'],
                                    'OBS_THRESHs':['>=0.254,>=1.27,>=2.54,>=6.35,>=12.7,>=19.05,>=25.4'],
                                    'CONFIDENCE_INTERVALS':'True',
                                },
                                'APCP_03':{
                                    'STATSs':['sratio,pod,csi'],
                                    'FCST_LEADS':['24','27','30','33','36','39','42','45','48','51','54','57','60'],
                                    'FCST_LEVEL':'A3',
                                    'OBS_LEVEL':'A3',
                                    'FCST_THRESHs':['>=0.254,>=1.27,>=2.54,>=6.35,>=12.7,>=19.05,>=25.4,>=50.8'],
                                    'OBS_THRESHs':['>=0.254,>=1.27,>=2.54,>=6.35,>=12.7,>=19.05,>=25.4,>=50.8'],
                                    'CONFIDENCE_INTERVALS':'True',
                                },
                                'APCP_24':{
                                    'STATSs':['sratio,pod,csi'],
                                    'FCST_LEADS':['24','30','36','42','48','54','60'],
                                    'FCST_LEVEL':'A24',
                                    'OBS_LEVEL':'A24',
                                    'FCST_THRESHs':['>=0.254,>=2.54,>=6.35,>=12.7,>=25.4,>=38.1,>=50.8,>=76.2,>=101.6,>=152.4'],
                                    'OBS_THRESHs':['>=0.254,>=2.54,>=6.35,>=12.7,>=25.4,>=38.1,>=50.8,>=76.2,>=101.6,>=152.4'],
                                    'CONFIDENCE_INTERVALS':'True',
                                },
                            }
                        }
                    },
                }
            }
        },
    }
}
