#!/bin/bash

set -xa

# ###################################
# SET SHELL PROCESSING VARIABLES
# ###################################
export PS4='$SECONDS + ' 
date

export machine="WCOSS2"

###########################################################
# obtain unique LSF id (jobid) and make temp directories
###########################################################
export DATA=${DATA:-${DATAROOT:?}/${jobid:?}}
mkdir -p $DATA
cd $DATA 

################################################################
# SENDCOM=YES--Copy files from TMPDIR to $COMOUT
# SENDECF=YES--Flag events on ecflow
# SENDDBN=YES--Issue DBNet client calls
################################################################
export SENDCOM=${SENDCOM:-NO}
export SENDDBN=${SENDDBN:-NO}       # need to set to NO for testing
export SENDECF=${SENDECF:-NO}
export SENDDBN_NTC=${SENDDBN_NTC:-NO}
################################################################
# Specify Execution Areas
################################################################
export EXECevs=${EXECevs:-$HOMEevs/exec}
export PARMevs=${PARMevs:-$HOMEevs/parm}
export USHevs=${USHevs:-$HOMEevs/ush}
export FIXevs=${FIXevs:-$HOMEevs/fix}

export gefs_members="30"

export cfs_members="4"

# Run setpdy and initialize PDY variables
export cyc=${cyc:-00}
export cycle=${cycle:-t${cyc}z}
setpdy.sh
. ./PDY

export INITDATE=$PDYm2

#################################################
# Set up the INPUT and OUTPUT directories
#################################################
export COMINgefs=${COMINgefs:-$(compath.py ${envir}/com/gefs/${gefs_ver}/gefs.$INITDATE)}
export COMINcfs=${COMINcfs:-$(compath.py ${envir}/com/cfs/${cfs_ver}/cfs.$INITDATE)}
export COMINgfs=${COMINgfs:-$(compath.py ${envir}/com/gfs/${gfs_ver})}
export COMINecmwf=${COMINecmwf:-$DCOMROOT}
export COMINccpa=${COMINccpa:-$(compath.py ${envir}/com/ccpa/${ccpa_ver})}
export COMINmrmsak=$DCOMROOT/ldmdata/obs/upperair/mrms/alaska/MultiSensorQPE
export COMINmrmshi=$DCOMROOT/ldmdata/obs/upperair/mrms/hawaii/MultiSensorQPE
export COMINosi=${COMINosi:-$DCOMROOT}
export COMINghrsst=${COMINghrsst:-$DCOMROOT}
export COMINumd=${COMINumd:-$DCOMROOT}
export COMINnam=${COMINnam:-$(compath.py ${envir}/com/obsproc/${obsproc_ver})}
export COMOUT=${COMOUT:-$(compath.py -o $NET/$evs_ver/$STEP/$COMPONENT/$RUN)}


echo Actual output starts here

################################################
# Run the config file to set up model variables
################################################
. $PARMevs/evs_config/$COMPONENT/config.evs.${COMPONENT}.${PREP_TYPE}.${STEP}

#######################################################################
# Execute the script.
#######################################################################
$HOMEevs/scripts/$COMPONENT/$STEP/exevs_${COMPONENT}_${PREP_TYPE}_${STEP}.sh
export err=$?; err_chk

msg="JOB $job HAS COMPLETED NORMALLY."
postmsg "$jlogfile" "$msg"

if [ "$KEEPDATA" != "YES" ] ; then
  cd $DATAROOT
  rm -rf $DATA
fi

date

