#!/bin/bash 
date
export PS4=' $SECONDS + '
set -x

####################################
# obtain unique process id (pid) and make temp directory
####################################
export jobid=${jobid:-$job.o$$}
export DATA=${DATA:-${DATAROOT:?}/${jobid}}
mkdir -p $DATA
cd $DATA
export cycle=t${cyc}z

####################################
# File To Log Msgs
####################################
export jlogfile=${jlogfile:-${DATA}/jlogfile.${jobid}}

####################################
# Specify NET and RUN Name and model
####################################
export NET=${NET:-tc_verify}
export COMPONENT=${COMPONENT:-global_spread}
export RUN=${RUN:-tropcyc}

####################################
# Determine Job Output Name on System
####################################
export pgmout="OUTPUT.$$"
export pgmerr=errfile

####################################
# SENDECF  - Flag Events on ecFLOW
# SENDCOM  - Copy Files From TMPDIR to $COMOUT
# SENDDBN  - Issue DBNet Client Calls
####################################
export SENDECF=${SENDECF:-NO}
export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-NO}

####################################
# Specify Execution Areas
####################################
export HOMEtc_verify=${HOMEtc_verify:-${PACHAGEHOME}}
export EXECtc_verify=${EXECtc_verify:-$HOMEtc_verify/exec}
export FIXtc_verify=${FIXtc_verify:-$HOMEtc_verify/fix}
export USHtc_verify=${USHtc_verify:-$HOMEtc_verify/ush}
export PARMtc_verify=${PARMtc_verify:-$HOMEtc_verify/parm}
export SCRIPTtc_verify=${SCRIPTtc_verify:-$HOMEtc_verify/scripts}

##############################
# Run setpdy and initialize PDY variables
##############################
#setpdy.sh
#. PDY
export PDY=20230919

export YYYY=`echo ${PDY} | cut -c1-4`
export YY22=`echo ${PDY} | cut -c3-4`
##############################################
# Define COM directories
##############################################
if [[ -d /lfs/h1 ]] ; then
  # We are on NOAA wcoss2
#  export MetOnMachine=/apps/ops/prod/libs/intel/19.1.3.304/met/10.1.2
  export machine="wcoss2"
  export MetOnMachine=/apps/ops/para/libs/intel/19.1.3.304/met/11.1.0-rc1
#  export COMINvit=${COMINvit:-/lfs/h2/emc/vpppg/noscrub/jiayi.peng/MetTCData/TCvital/syndat_tcvitals.${YYYY}}
#  export COMINtrack=${COMINtrack:-/lfs/h2/emc/vpppg/noscrub/jiayi.peng/MetTCData/globalTrack/tracks.atcfunix.${YY22}}
#  export COMINbdeckNHC=${COMINbdeckNHC:-/lfs/h2/emc/vpppg/noscrub/jiayi.peng/MetTCData/bdeck}
#  export COMINbdeckJTWC=${COMINbdeckJTWC:-/lfs/h2/emc/vpppg/noscrub/jiayi.peng/MetTCData/bdeck}
  export COMINvit=${COMINvit:-/lfs/h2/emc/hur/noscrub/jiayi.peng/Jiayi/MetTCData/TCvital/syndat_tcvitals.${YYYY}}
  export COMINtrack=${COMINtrack:-/lfs/h2/emc/hur/noscrub/jiayi.peng/Jiayi/MetTCData/globalTrack/tracks.atcfunix.${YY22}}
  export COMINbdeckNHC=${COMINbdeckNHC:-/lfs/h2/emc/hur/noscrub/jiayi.peng/Jiayi/MetTCData/bdeck}
  export COMINbdeckJTWC=${COMINbdeckJTWC:-/lfs/h2/emc/hur/noscrub/jiayi.peng/Jiayi/MetTCData/bdeck}
elif [[ -d /lfs4/HFIP ]] ; then
  # We are on NOAA Jet
  export MetOnMachine=/misc/contrib/met/10.1.1
  export COMINvit=${COMINvit:-/mnt/lfs4/HFIP/hwrfv3/Jiayi.Peng/MetTCData/TCvital/syndat_tcvitals.${YYYY}}
  export COMINtrack=${COMINtrack:-/mnt/lfs4/HFIP/hwrfv3/Jiayi.Peng/MetTCData/globalTrack/tracks.atcfunix.${YY22}}
  export COMINbdeckNHC=${COMINbdeckNHC:-/mnt/lfs4/HFIP/hwrfv3/Jiayi.Peng/MetTCData/bdeck}
  export COMINbdeckJTWC=${COMINbdeckJTWC:-/mnt/lfs4/HFIP/hwrfv3/Jiayi.Peng/MetTCData/bdeck}
elif [[ -d /scratch2 ]] ; then
  # We are on NOAA Hera
#  export MetOnMachine=/contrib/met/10.1.2
  export machine="hera"
  export MetOnMachine=/contrib/met/${met_ver}
  export MPLCONFIGDIR=/scratch2/NCEPDEV/ensemble/Jiayi.Peng/noscrub/ptmp
  export PYTHONonHERA=/contrib/anaconda/anaconda3/4.4.0/bin/python

  export COMINvit=${COMINvit:-/scratch2/NCEPDEV/ensemble/Jiayi.Peng/noscrub/MetTCData/TCvital/syndat_tcvitals.${YYYY}}
  export COMINtrack=${COMINtrack:-/scratch2/NCEPDEV/ensemble/Jiayi.Peng/noscrub/MetTCData/globalTrack/tracks.atcfunix.${YY22}}
  export COMINbdeckNHC=${COMINbdeckNHC:-/scratch2/NCEPDEV/ensemble/Jiayi.Peng/noscrub/MetTCData/bdeck}
  export COMINbdeckJTWC=${COMINbdeckJTWC:-/scratch2/NCEPDEV/ensemble/Jiayi.Peng/noscrub/MetTCData/bdeck}
elif [[ -d /work ]] ; then
  # We are on MSU Orion
  export MetOnMachine=/apps/contrib/MET/10.1.1
  export COMINvit=${COMINvit:-/your/TC/vitals/file}
  export COMINtrack=${COMINtrack:-your/TC/track/file}
  export COMINbdeckNHC=${COMINbdeckNHC:-/your/NHC/bdeck/data/dir}
  export COMINbdeckJTWC=${COMINbdeckJTWC:-/your/JTWC/bdeck/data/dir}
else
  echo Job failed: unknown platform 1>&2
  err_exit "FAILED ${jobid} - ERROR IN unknown platform - ABNORMAL EXIT"
fi

#export COMOUT=${COMOUT:-$(compath.py -o ${NET}/${tc_verify_ver})/${COMPONENT}/${RUN}}
export COMOUT=${COMOUT:-${COMROOT:?}/${NET}/${tc_verify_ver}/${COMPONENT}/${RUN}}
mkdir -m 775 -p $COMOUT 
msg="HAS BEGUN on `hostname`"
postmsg "$jlogfile" "$msg"

#env

#############################################################
${SCRIPTtc_verify}/exglobal_spread_tropcyc.sh
export err=$?; err_chk

msg="JOB COMPLETED NORMALLY"
postmsg "$jlogfile" "$msg"

##############################
# Remove the Temporary working directory
##############################
if [[ $KEEPDATA != "YES" ]]; then
  rm -rf $DATA
fi

date
