[config]

LOG_METPLUS =

OUTPUT_BASE = {ENV[output_base]}

# List of applications to run - only PB2NC for this case
PROCESS_LIST = PB2NC

# Time looping - options are INIT, VALID, RETRO, and REALTIME
LOOP_BY = VALID

# Format of VALID_BEG and VALID_END using % items
VALID_TIME_FMT = %Y%m%d%H

# Start time for METplus run - must match VALID_TIME_FMT
VALID_BEG = {ENV[vday]}{ENV[vbeg]}

# End time for METplus run - must match VALID_TIME_FMT
VALID_END = {ENV[vday]}{ENV[vbeg]}

# Increment between METplus runs (in seconds if no units are specified)
#   Must be >= 60 seconds
VALID_INCREMENT = 1M

LEAD_SEQ = 0

# Order of loops to process data - Options are times, processes
# Not relevant if only one item is in the PROCESS_LIST
# times = run all wrappers in the PROCESS_LIST for a single run time, then
#   increment the run time and run all wrappers again until all times have
#   been evaluated.
# processes = run the first wrapper in the PROCESS_LIST for all times
#   specified, then repeat for the next item in the PROCESS_LIST until all
#   wrappers have been run
LOOP_ORDER = processes

# Location of MET config file to pass to PB2NC
# References CONFIG_DIR from the [dir] section
PB2NC_CONFIG_FILE = {METPLUS_BASE}/parm/met_config/PB2NCConfig_wrapped

# If set to True, skip run if the output file determined by the output directory and
#   filename template already exists
PB2NC_SKIP_IF_OUTPUT_EXISTS = True

# Time relative to each input file's valid time (in seconds if no units are specified)
#   for data within the file to be considered valid. Values are set in the 'obs_window'
#   dictionary in the PB2NC config file
PB2NC_WINDOW_BEGIN = -1800
PB2NC_WINDOW_END = 1800

PB2NC_GRID = G003
PB2NC_POLY =
PB2NC_STATION_ID =
PB2NC_MESSAGE_TYPE = ADPUPA

PB2NC_LEVEL_RANGE_BEG =  -1000
PB2NC_LEVEL_RANGE_END = 100000

PB2NC_QUALITY_MARK_THRESH = 9

PB2NC_OBS_BUFR_VAR_LIST = ZOB, TOB, UOB, VOB, D_RH
PB2NC_OBS_BUFR_MAP =   { key = "ZOB"; val = "HGT"; }, { key = "TOB"; val = "TMP"; }, { key = "UOB"; val = "UGRD"; }, { key = "VOB"; val = "VGRD"; }, { key = "D_RH"; val = "RH"; } ;

[dir]
CONFIG_DIR = {PARM_BASE}/met_config
PB2NC_INPUT_DIR = {ENV[bufrpath]}
PB2NC_OUTPUT_DIR = {OUTPUT_BASE}/prepbufr_nc
METPLUS_CONF = {OUTPUT_BASE}/final_pb2nc_{ENV[vbeg]}.conf

[filename_templates]
PB2NC_INPUT_TEMPLATE = prepbufr.{da_init?fmt=%Y%m%d}/gdas.t{da_init?fmt=%H}z.prepbufr
PB2NC_OUTPUT_TEMPLATE = gfs.t{da_init?fmt=%H}z.prepbufr_profile.f00.nc

