#!/bin/sh

set -xa

export PS4='$SECONDS + '
date

# Version of MET listed in the metplus .stat files used to create graphics
# Because Python code will convert it to a float variable,
# keep at most one dot(.) and remove extra from MET_VERSION.
export MET_VERSION=`echo $MET_VERSION | sed "s/\([^.]*\.[^.]*\)\..*/\1/g"`

############################################
# Working Directory                                                                                                                                      
############################################
export DATA=${DATA:-${DATAROOT}/${jobid:?}}
mkdir -p $DATA
cd $DATA

############################################
# Determine Job Output Name on System
############################################
export pid=$$
export pgmout=OUTPUT.${pid}

############################################
# Initialize PDY variables
############################################
export cyc=${cyc:-00}
export cycle=t${cyc}z

#It needs $DATA and $cycle to be set
setpdy.sh
. ./PDY

# Don't specify $VDATE to be flexible to both data preparation and MET stat input
export VDATE=${VDATE:-$PDYm1}

############################################
# Set up the NET and RUN                                                                                                                         
############################################
export NET=${NET:-evs}
export STEP=${STEP:-plots} # prep stats plot
export COMPONENT=${COMPONENT:-global_det}
export RUN=${RUN:-aviation}
export VERIF_CASE=${VERIF_CASE:-grid2grid}

# WAFS is the general MODELNAME for data structure
# while the center (us/uk/blend or gfs) will be the actual MODEL
export MODELNAME=${MODELNAME:-wafs}

############################################
# Set up the INPUT and OUTPUT directories
############################################

# COMIN folder of analysis and forecast grib2 data
# gfs_ver defined in versions/run.ver
export COMIN=${COMIN:-$(compath.py ${envir}/com/${NET}/${evs_ver})}
export COMINstat=$COMIN/stats/$COMPONENT  # will be appended with wafs.$VDATE or gfs.$VDATE

# COMOUT folder
# evs_ver defined in versions/run.ver
export COMOUT=${COMOUT:-$COMIN/$STEP/$COMPONENT/$RUN.$VDATE}

mkdir -p $COMOUT

############################################
# Specify HOME Directory
############################################

export HOMEevs=${HOMEevs:-$PACKAGEROOT/evs.$evs_ver}
export EXECevs=${EXECevs:-$HOMEevs/exec}
export FIXevs=${FIXevs:-$HOMEevs/fix}
export SCRIPTSevs=${SCRIPTSevs:-$HOMEevs/scripts/$COMPONENT} # step
export JOBSevs=${JOBSevs:-$HOMEevs/jobs/$COMPONENT} # step
export PARMevs=${PARMevs:-$HOMEevs/parm/metplus_config/$COMPONENT/$RUN} # step
export USHevs=${USHevs:-$HOMEevs/ush/$COMPONENT} # all pool

export MASKS=${MASKS:-$FIXevs/masks}

# To integrate plotting python scripts from Marcel Caron
export USH_DIR=${USH_DIR:-$HOMEevs/ush/$COMPONENT}

############################################
# Execute the script.
############################################
export DAYS_LIST=${DAYS_LIST:-"90 31"}

export DATAplot=$DATA/plot
mkdir -p $DATAplot

export MPIRUN=${MPIRUN:-"mpiexec -np 4 -cpu-bind verbose,core cfp"}

OBSERVATIONS="GCIP GFS"
rm wafs_plots.cmdfile
n=0
for observation in $OBSERVATIONS ; do
    for ndays in $DAYS_LIST ; do
	if [ `echo $MPIRUN | cut -d " " -f1` = 'srun' ] ; then
	    echo $n $SCRIPTSevs/plots/exevs_global_det_aviation_plots.sh $observation $ndays  >> wafs_plots.cmdfile
	else
	    echo $SCRIPTSevs/plots/exevs_global_det_aviation_plots.sh $observation $ndays  >> wafs_plots.cmdfile
	    export MP_PGMMODEL=mpmd
	fi
	n=$(( n + 1 ))
    done
done
$MPIRUN wafs_plots.cmdfile

cd $DATAplot
for ndays in $DAYS_LIST ; do
    eval_period="last${ndays}days"
    tar -cvf $COMOUT/$NET.$STEP.${COMPONENT}.${RUN}.${VERIF_CASE}.$eval_period.v${VDATE}.tar *${eval_period}*png
done

export err=$?; err_chk

msg="JOB $job HAS COMPLETED NORMALLY."
echo $msg

if [ "$KEEPDATA" != "YES" ] ; then
  rm -rf $DATA
fi

date

exit
