#!/bin/bash

#################################
# SET SHELL PROCESSING VARIABLES 
#################################
set -x
export PS4='+ $SECONDS + '
date

#########################################################
# obtain unique LSF id (jobid) and make temp directories 
#########################################################
export pid=$$
export DATA_IN=${DATA_IN:-${DATAROOT}}
export DATA=${DATA_IN}/${jobid:?}
mkdir -p $DATA
cd $DATA

##########################################
# Run setpdy and initialize PDY variables 
##########################################
export cycle=${cycle:-t00z}
setpdy.sh 90
. ./PDY
export PDYm90=${PDYm90:-${PDYm90}}
export VDATE=${VDATE:-${PDYm1}}

######################################
# Determine Job Output Name on System 
######################################
export pgmout="OUTPUT.${pid}"

####################################
# Set EVS directories               
####################################
export HOMEevs=${HOMEevs:-${PACKAGEROOT}/evs.${model_ver}}
export EXECevs=${EXECevs:-$HOMEevs/exec}
export FIXevs=${FIXevs:-$HOMEevs/fix}
export PARMevs=${PARMevs:-$HOMEevs/parm}
export USHevs=${USHevs:-$HOMEevs/ush}

######################################
# Correct MET/METplus roots (Aug 2022)
######################################
# for use with MET/10.1.1 and METplus/4.1.1
#export MET_ROOT=/apps/ops/para/libs/intel/${intel_ver}/met/${met_ver}
#export MET_BASE=${MET_ROOT}/share/met
#export METPLUS_PATH=/apps/ops/para/libs/intel/${intel_ver}/metplus/${metplus_ver}
#export PATH=${METPLUS_PATH}/ush:${MET_ROOT}/bin:${PATH}

####################################
# Define NET/RUN variables          
####################################
export NET=${NET:-evs}
export MODEL=${MODEL:-evs}
export STEP=${STEP:-plots}
export COMPONENT=${COMPONENT:-global_det}
export MODELNAME=${MODELNAME:-gfs}
export MODNAM=$(echo $MODELNAME | tr '[a-z]' '[A-Z]')
export OBTYPE=${OBTYPE:-GDAS}
export RUN=${RUN:-wave}
export VERIF_CASE=${VERIF_CASE:-grid2obs}

####################################
# Define COMIN/COMOUT variables     
####################################
export COMIN=${COMIN:-$(compath.py ${envir}/com/${NET}/${evs_ver})}
export COMOUT=${COMOUT:-$(compath.py ${envir}/com/${NET}/${evs_ver})}
export COMINstats=${COMIN}/stats/${COMPONENT}/${MODELNAME}.${VDATE}
export COMOUTplots=${COMOUT}/${STEP}/${COMPONENT}/${RUN}.${VDATE}

# make the directory where the plots will be kept
mkdir -p ${COMOUTplots}

export jlogfile=${DATA}/${MODELNAME}_${RUN}_plots.log

####################################
# Execute the script                
####################################
env
$HOMEevs/scripts/global_det/plots/exevs_global_det_wave_grid2obs_plots.sh 1>>$pgmout 2>errfile.${pid}
export err=$?; err_chk

cat $pgmout

msg="JOB $job HAS COMPLETED NORMALLY."
postmsg "$jlogfile" "$msg"

if [ "$KEEPDATA" != "YES" ] ; then
  rm -rf $DATA
fi

date
