#!/bin/bash

########################################
# Preliminary data setup step
########################################
set -xa

####################################
# SET SHELL PROCESSING VARIABLES
####################################
export PS4='$SECONDS + '
date

###########################################################
# obtain unique LSF id (jobid) and make temp directories
###########################################################
export pid=$$
export DATA=${DATA:-${DATAROOT:?}/${jobid:?}}
mkdir -p $DATA
cd $DATA

####################################
# Set EVS directories
####################################
export HOMEevs=${HOMEevs:-${PACKAGEROOT}/evs.${model_ver}}
export EXECevs=${EXECevs:-$HOMEevs/exec}
export FIXevs=${FIXevs:-$HOMEevs/fix}
export PARMevs=${PARMevs:-$HOMEevs/parm}
export USHevs=${USHevs:-$HOMEevs/ush}

####################################
# Run setpdy and initialize PDY variables
####################################
export cycle=${cycle:-t${cyc}z}
setpdy.sh
. ./PDY
export VDATEYYYY=${VDATEYYYY:-$(date -d "1 month ago" '+%Y')}
export VDATEmm=${VDATEmm:-$(date -d "1 month ago" '+%m')}

####################################
# Set data directives
####################################
export SENDECF=${SENDECF:-YES}
export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-NO}

####################################
# Define NET/RUN variables
####################################
export NET=${NET:-evs}
export STEP=${STEP:-plots}
export COMPONENT=${COMPONENT:-global_det}
export RUN=${RUN:-long_term}

####################################
# Define COMIN/COMOUT variables
####################################
export COMIN=${COMIN:-$(compath.py -o $NET/$evs_ver)}
export COMINdailystats=${COMINdailystats:-$COMIN/stats/$COMPONENT}
export COMINmonthlystats=${COMINmonthlystats:-$COMIN/stats/$COMPONENT/$RUN/monthly_means}
export COMINyearlystats=${COMINyearlystats:-$COMIN/stats/$COMPONENT/$RUN/yearly_means}
export COMOUT=${COMOUT:-$(compath.py -o $NET/$evs_ver/$STEP/$COMPONENT/$RUN.$PDYm1)}
mkdir -p $COMOUT

#######################################################################
# Execute the script
#######################################################################
env

$HOMEevs/scripts/global_det/plots/exevs_global_det_atmos_${RUN}_plots.sh
export err=$?; err_chk

cat $pgmout

msg="JOB $job HAS COMPLETED NORMALLY."
postmsg "$jlogfile" "$msg"

if [ "$KEEPDATA" != "YES" ] ; then
  cd $DATAROOT
  rm -rf $DATA
fi

date
