#!/bin/sh

set -xa

export PS4='$SECONDS + '
date

############################################
# Working Directory                                                                                                                                      
############################################
export DATA=${DATA:-${DATAROOT}/${jobid:?}}
mkdir -p $DATA
cd $DATA

############################################
# Determine Job Output Name on System
############################################
export pid=$$
export pgmout=OUTPUT.${pid}

############################################
# Initialize PDY variables
############################################
export cyc=${cyc:-00}
export cycle=t${cyc}z

#It needs $DATA and $cycle to be set
setpdy.sh
. ./PDY

# Don't specify $VDATE to be flexible to both data preparation and MET stat input
export VDATE=${VDATE:-$PDYm1}

############################################
# Set up the NET and RUN                                                                                                                         
############################################
export NET=${NET:-evs}
export STEP=${STEP:-plots} # prep stats plot
export COMPONENT=${COMPONENT:-global_det}
export RUN=${RUN:-aviation}
export VERIF_CASE=${VERIF_CASE:-grid2grid}

# WAFS is the general MODELNAME for data structure
# while the center (us/uk/blend or gfs) will be the actual MODEL
export MODELNAME=${MODELNAME:-wafs}

############################################
# Set up the INPUT and OUTPUT directories
############################################

# COMIN folder of analysis and forecast grib2 data
# gfs_ver defined in versions/run.ver
export COMIN=${COMIN:-$(compath.py ${envir}/com/${NET}/${evs_ver})}
export COMINstat=$COMIN/stats/$COMPONENT  # will be appended with wafs.$VDATE or gfs.$VDATE

# COMOUT folder
# evs_ver defined in versions/run.ver
export COMOUT=${COMOUT:-$COMIN/$STEP/$COMPONENT/$RUN.$VDATE}

mkdir -p $COMOUT

############################################
# Specify HOME Directory
############################################

export HOMEevs=${HOMEevs:-$PACKAGEROOT/evs.$evs_ver}
export EXECevs=${EXECevs:-$HOMEevs/exec}
export FIXevs=${FIXevs:-$HOMEevs/fix}
export SCRIPTSevs=${SCRIPTSevs:-$HOMEevs/scripts/$COMPONENT} # step
export JOBSevs=${JOBSevs:-$HOMEevs/jobs/$COMPONENT} # step
export PARMevs=${PARMevs:-$HOMEevs/parm/metplus_config/$COMPONENT/$RUN} # step
export USHevs=${USHevs:-$HOMEevs/ush/$COMPONENT} # all pool

export MASKS=${MASKS:-$FIXevs/masks}

# To integrate plotting python scripts from Marcel Caron
export USH_DIR=${USH_DIR:-$HOMEevs/ush/$COMPONENT}

############################################
# Execute the script.
############################################

export NDAYS=${NDAYS:-90}

$SCRIPTSevs/plots/exevs_global_det_aviation_plots.sh

export err=$?; err_chk

msg="JOB $job HAS COMPLETED NORMALLY."
echo $msg

if [ "$KEEPDATA" != "YES" ] ; then
  rm -rf $DATA
fi

date

exit
