#!/bin/bash

########################################
# Preliminary data setup step
########################################
set -x


##################################################
# SENDMAIL - Send Email Alerts When Missing Data
# SENDECF  - Flag Events on ecFLOW
# SENDCOM  - Copy Files From TMPDIR to $COMOUT
# SENDDBN  - Issue DBNet Client Calls
##################################################
export SENDMAIL=${SENDMAIL:-NO}
export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-YES}
export SENDECF=${SENDECF:-YES}


####################################
# SET SHELL PROCESSING VARIABLES
####################################
export PS4='$SECONDS + '
date


###########################################################
# obtain unique LSF id (jobid) and make temp directories
###########################################################
export pid=$$
export DATA=${DATA:-${DATAROOT:?}/${jobid:?}}
rm -rf $DATA
mkdir -p $DATA
cd $DATA


####################################
# Determine Job Output Name on System
####################################

####################################
# Define NET/RUN variables
####################################
export NET=${NET:-evs}
export STEP=${STEP:-prep}
export COMPONENT=${COMPONENT:-cam}
export RUN=${RUN:-atmos}
export VERIF_CASE=${VERIF_CASE:-precip}
export MODELNAME=${MODELNAME:-cam}

####################################
# Set EVS directories
####################################
export HOMEevs=${HOMEevs:-${PACKAGEROOT}/${NET}.${evs_ver}}
export EXECevs=${EXECevs:-$HOMEevs/exec}
export FIXevs=${FIXevs:-$HOMEevs/fix}
export PARMevs=${PARMevs:-$HOMEevs/parm}
export SCRIPTSevs=${SCRIPTSevs:-$HOMEevs/scripts}
export USHevs=${USHevs:-$HOMEevs/ush}


####################################
# Run setpdy and initialize PDY variables
####################################
export cycle=${cycle:-t${vhr}z}
setpdy.sh 8
. ./PDY

if [ $VERIF_CASE = grid2obs ] ; then
   if [ "${RUN}" == "chem" ]; then
       export INITDATE=${INITDATE:-${PDYm3}}
   else
       export INITDATE=${INITDATE:-$PDYm1}
   fi

elif [ $VERIF_CASE = precip ] ; then
   export INITDATE=${INITDATE:-$PDYm1}

elif [ $VERIF_CASE = radar ] ; then
   export INITDATE=${INITDATE:-$PDYm1}
 
elif [ $VERIF_CASE = severe ] ; then

   # Set initialization date (only for forecast prep step)
   export INITDATE=${INITDATE:-$PDYm1}

   # Set verification date for severe job
   export VDATE=$(finddate.sh $INITDATE d-6)
  
   # Set correct date for SPC report data (must be relative to VDATE) 
   export REP_DATE=$(finddate.sh $VDATE d-1)

   # Set correct date for SPC outlook data 
   export OTLK_DATE=${OTLK_DATE:-$INITDATE}

else

   err_exit "The provided VERIF_CASE, $VERIF_CASE, is not supported for the $COMPONENT $STEP step"

fi


####################################
# Define METplus variables
####################################
export MET_PLUS_CONF="${PARMevs}/metplus_config/${STEP}/${COMPONENT}/${VERIF_CASE}"


####################################
# Define COMIN/COMOUT variables
####################################
export COMIN=${COMIN:-$(compath.py ${envir}/com/$NET/$evs_ver)}

export COMOUT=${COMOUT:-$(compath.py -o $NET/$evs_ver/$STEP/$COMPONENT)}

mkdir -p $COMOUT

if [[ "${RUN}" == "chem" ]]; then
    export DCOMINairnow=${DCOMINairnow:-${DCOMROOT}}
    export DCOMINaeronet=${DCOMINaeronet:-${DCOMROOT}}
    export COMOUTprepmdl=${COMOUTprepmdl:-${COMOUT}/${RUN}.${INITDATE}/${MODELNAME}}
    export COMOUTprepobs=${COMOUTprepobs:-${COMOUT}/${RUN}.${INITDATE}/obs}

    # alternative choice is an option different from aqobs
    export airnow_hourly_type=${airnow_hourly_type:-aqobs}
    export HOURLY_NCOL=${HOURLY_NCOL:-34}
    export restart_mode=${restart_mode:-YES}

else
    export COMINccpa=${COMINccpa:-$(compath.py ${envir}/com/ccpa/$ccpa_ver)}
    export COMINhrrr=${COMINhrrr:-$(compath.py ${envir}/com/hrrr/${hrrr_ver})}
    export COMINrrfs=${COMINrrfs:-$(compath.py ${envir}/com/rrfs/${rrfs_ver})}
    export COMINobsproc=${COMINobsproc:-$(compath.py ${envir}/com/obsproc/${obsproc_ver})}
    export DCOMINmrms=${DCOMINmrms:-$DCOMROOT/ldmdata/obs/upperair/mrms}
    export DCOMINspc=${DCOMINspc:-$DCOMROOT}
    
    export COMOUTmrms=${COMOUT}/${RUN}.${INITDATE}/mrms
    
    if [ $VERIF_CASE = severe ] ; then
       export COMOUTlsr=${COMOUT}/${RUN}.${REP_DATE}/spc_lsr
       export COMOUTotlk=${COMOUT}/${RUN}.${OTLK_DATE}/spc_otlk
    elif [[ "$VERIF_CASE" == "precip" && "$STEP" == "prep" && "$MODELNAME" != "cam" ]]; then
        export COMOUTsmall=${COMOUT}/${RUN}.${INITDATE}
        [[ ! -d $COMOUTsmall ]] && mkdir -p $COMOUTsmall
    fi

fi


####################################
# Execute the script 
####################################
if [[ "${RUN}" == "chem" ]]; then
    ${HOMEevs}/scripts/${STEP}/${COMPONENT}/exevs_${STEP}_${COMPONENT}_${MODELNAME}_${RUN}_${VERIF_CASE}.sh
else
    if [[ "${MODELNAME}" = *"rrfsmem"* ]]; then
       $HOMEevs/scripts/$STEP/$COMPONENT/exevs_${STEP}_rrfsmem_${VERIF_CASE}.sh
    else
       $HOMEevs/scripts/$STEP/$COMPONENT/exevs_${STEP}_${MODELNAME}_${VERIF_CASE}.sh
    fi
fi
export err=$?; err_chk

if [ "$KEEPDATA" != "YES" ]; then
   cd $DATAROOT
   rm -rf $DATA
fi

date
