#!/bin/bash

########################################
# Preliminary data setup step
########################################
set -x


#####################################
# SET SHELL PROCESSING VARIABLES
# ###################################
export PS4='$SECONDS + '
date


###########################################################
# obtain unique LSF id (jobid) and make temp directories
###########################################################
export pid=$$

export DATA=${DATA:-${DATAROOT:?}/${jobid:?}}
rm -rf $DATA
mkdir -p $DATA
cd $DATA


####################################
# Determine Job Output Name on System
####################################

####################################
# Define NET/RUN variables
####################################
export NET=${NET:-evs}
export STEP=${STEP:-plots}
export COMPONENT=${COMPONENT:-cam}
export RUN=${RUN:-atmos}
export VERIF_CASE=${VERIF_CASE:-grid2obs}
export MODELNAME=${MODELNAME:-cam}

####################################
# Set EVS directories
####################################
export HOMEevs=${HOMEevs:-${PACKAGEROOT}/${NET}.${evs_ver}}
export EXECevs=${EXECevs:-$HOMEevs/exec}
export FIXevs=${FIXevs:-$HOMEevs/fix}
export PARMevs=${PARMevs:-$HOMEevs/parm}
export SCRIPTSevs=${SCRIPTSevs:-$HOMEevs/scripts}
export USHevs=${USHevs:-$HOMEevs/ush}


##################################################
# SENDMAIL - Send Email Alerts When Missing Data
# SENDECF  - Flag Events on ecFLOW
# SENDCOM  - Copy Files From TMPDIR to $COMOUT
# SENDDBN  - Issue DBNet Client Calls
##################################################
export SENDMAIL=${SENDMAIL:-NO}
export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-YES}
export SENDECF=${SENDECF:-YES}


####################################
# Run setpdy and initialize PDY variables
####################################
export cycle=${cycle:-t${vhr}z}
setpdy.sh 31
. ./PDY

if [ $MODELNAME = refs ] ; then
    export VDATE=${VDATE:-$PDYm2}
    export INITDATE=${INITDATE:-$PDYm2}
    export eval_period=${EVAL_PERIOD:-last90days}
elif [[ "$MODELNAME" == "rrfs" && "$RUN" == chem* ]]; then
    export VDATE_END=${VDATE_END:-${PDYm4}}
    export NDAYS=${NDAYS:-31}
    export VDATE_START=${VDATE_START:-$(finddate.sh ${VDATE_END} d-$((${NDAYS}-1)))}
elif [ $VERIF_CASE = severe ] ; then
    export VDATE=${VDATE:-$PDYm7}
    export EVAL_PERIOD=${EVAL_PERIOD:-last90days}
elif [ $VERIF_CASE = headline ] ; then
    export VDATE=${VDATE:-$PDYm1}
    export EVAL_PERIOD=${EVAL_PERIOD:-last90days}
else
    export VDATE=${VDATE:-$PDYm2}
    export EVAL_PERIOD=${EVAL_PERIOD:-last90days}
fi


####################################
# Define COMIN/COMOUT variables
####################################
export COMROOT=${COMROOT:-$(compath.py $envir/com)}

if [ $MODELNAME = refs ] ; then
  export EVSINapcp24mean=${COMIN:-$(compath.py $envir/com/$NET/${evs_ver})}/stats/$COMPONENT/${RUN}.${VDATE}/$MODELNAME/precip/precip_mean24
  export COMIN=${COMIN:-$(compath.py $envir/com/$NET/$evs_ver)}/stats/$COMPONENT/$MODELNAME.$VDATE
  export COMOUT=${COMOUT:-$(compath.py -o $NET/${evs_ver})}/$STEP/$COMPONENT/$RUN.$VDATE
  export DATA_IN=${DATA_IN:-$DATAROOT}
  export ush_dir=$USHevs/cam/ush_refs_plot_py
else
  export COMIN=${COMIN:-$(compath.py $envir/com/$NET/$evs_ver)}
  if [[ "$MODELNAME" == "rrfs" && "$RUN" == chem* ]]; then
    export EVSINrrfs=${EVSINrrfs:-${COMIN}/stats/${COMPONENT}}
    export COMOUT=${COMOUT:-$(compath.py -o ${NET}/${evs_ver}/${STEP}/${COMPONENT}/${RUN}.${VDATE_END})}
  else
    export COMOUT=${COMOUT:-$(compath.py -o $NET/$evs_ver/$STEP/$COMPONENT)}
    if [ $VERIF_CASE = headline ] ; then
      export COMOUTplots=${COMOUTplots:-$COMOUT/headline.$VDATE}
    else
      export COMOUTplots=${COMOUTplots:-$COMOUT/$RUN.$VDATE}
    fi
    export EVSINrrfs=${EVSINrrfs:-$COMIN/stats/$COMPONENT/rrfs_$MODELNAME}
    echo $COMPATH
    [[ ! -d $COMOUTplots ]] && mkdir -p $COMOUTplots
  fi
fi

[[ ! -d $COMOUT ]] && mkdir -p $COMOUT

echo $COMPATH

if [[ "$MODELNAME" == "rrfs" && "$RUN" == chem* ]]; then
  export machine=${machine:-WCOSS2}
  export USE_CFP=${USE_CFP:-YES}
  export nproc=${nproc:-128}
  export evs_run_mode=${evs_run_mode:-production}
  export DATA_TYPE=${DATA_TYPE:-hourly}
  export restart_mode=${restart_mode:-YES}
  export fig_name_label=${fig_name_label:-last${NDAYS}days}
  export plot_diff_fig=${plot_diff_fig:-NO}
  export config=${config:-${PARMevs}/evs_config/${COMPONENT}/config.${NET}.${envir}.${STEP}.${COMPONENT}.${MODELNAME}.${RUN}.${VERIF_CASE}.${DATA_TYPE}}
fi


#######################################################################
# Execute the script.
#######################################################################

if [ $MODELNAME = firewxnest ]; then
 $HOMEevs/scripts/${STEP}/${COMPONENT}/exevs_${STEP}_${COMPONENT}_${MODELNAME}_${VERIF_CASE}.sh
elif [[ "$MODELNAME" == "rrfs" && "$RUN" == chem* ]]; then
 $HOMEevs/scripts/${STEP}/${COMPONENT}/exevs_${STEP}_${COMPONENT}_${MODELNAME}_${RUN}_${VERIF_CASE}.sh
else
 $HOMEevs/scripts/${STEP}/${COMPONENT}/exevs_${STEP}_${MODELNAME}_${VERIF_CASE}.sh
fi
export err=$?; err_chk

if [ "$KEEPDATA" != "YES" ] ; then
  cd $DATAROOT
  rm -rf $DATA
fi

