#!/bin/bash
#  JOB card created for global_ens prep jobs
#   By Binbin Zhou, IMSG@EMC/NCEP - Feb 2, 2022
#   Updated by Alicia Bentley, EMC - Aug 27, 2025

########################################
# Preliminary data setup step
########################################
set -x

####################################
# SET SHELL PROCESSING VARIABLES
####################################
export PS4='$SECONDS + '
date

###########################################################
# obtain unique LSF id (jobid) and make temp directories
###########################################################
export pid=$$
export DATA=${DATA:-${DATAROOT:?}/${jobid:?}}
mkdir -p $DATA
cd $DATA

####################################
# Define NET/RUN variables
####################################
export NET=${NET:-evs}
export STEP=${STEP:-prep}
export COMPONENT=${COMPONENT:-global_ens}
export RUN=${RUN:-atmos}
export MODELNAME=${MODELNAME:-gefs}
export MODNAM=echo $MODELNAME | tr '[a-z]' '[A-Z]'
export VERIF_CASE=${VERIF_CASE:-grid2obs}
export OBTYPE=${OBTYPE:-GDAS}

####################################
# Set EVS directories
####################################
export HOMEevs=${HOMEevs:-${PACKAGEROOT}/${NET}.${evs_ver}}
export EXECevs=${EXECevs:-${HOMEevs}/exec}
export PARMevs=${PARMevs:-${HOMEevs}/parm}
export SCRIPTSevs=${SCRIPTSevs:-${HOMEevs}/scripts}
export USHevs=${USHevs:-${HOMEevs}/ush}
export FIXevs=${FIXevs:-${HOMEevs}/fix}

##########################################
# Run setpdy and initialize PDY variables 
##########################################
export vhr=${vhr:-00}
export cycle=${cycle:-t${vhr}z}
setpdy.sh 20
. ./PDY

if [ "${RUN}" == "atmos" ] || [ "${RUN}" == "headline" ]; then
    export INITDATE=${INITDATE:-${PDYm2}}
else 
    export INITDATE=${INITDATE:-${PDYm1}}
    export NEXTDATE=${NEXTDATE:-${PDY}}	
fi

##################################################
### SENDCOM  - Copy Files From TMPDIR to $COMOUT
### SENDDBN  - Issue DBNet Client Calls 
### SENDECF  - Flag Events on ecFLOW
### SENDMAIL - Send email if file is missing
##################################################
export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-YES}
export SENDECF=${SENDECF:-YES}
export SENDMAIL=${SENDMAIL:-NO}

####################################
# Define COMIN/COMOUT variables
####################################
export ECMWF_FILE_EXT=${ECMWF_FILE_EXT:-1}
export COMIN=${COMIN:-$(compath.py ${envir}/com/${NET}/${evs_ver})}
export COMINgefs=${COMINgefs:-$(compath.py ${envir}/com/gefs/${gefs_ver})}
export COMINgfs=${COMINgfs:-$(compath.py $envir/com/gfs/${gfs_ver})}
export COMINnaefs=${COMINnaefs:-$(compath.py $envir/com/naefs/${naefs_ver})}
export DCOMIN=${DCOMIN:-${DCOMROOT}}
export COMINccpa=${COMINccpa:-$(compath.py $envir/com/ccpa/${ccpa_ver})}
export COMINcmce=$COMINnaefs
export COMINobsproc=${COMINobsproc:-$(compath.py $envir/com/obsproc/${obsproc_ver})}
export DCOMINnohrsc=${DCOMINnohrsc:-$DCOMROOT}
export DCOMINosi_saf=${DCOMINosi_saf:-$DCOMROOT}
export DCOMINghrsst=${DCOMINghrsst:-$DCOMROOT}
export DCOMINecmwf=${DCOMINecmwf:-$DCOMROOT}

export COMINgefs_bc=${COMINgefs_bc:-$COMINnaefs}
export DCOMINcmce_bc=${DCOMINcmce_bc:-$DCOMIN}
export EVSINgefs=${COMIN}/${STEP}/${COMPONENT}/atmos.${INITDATE}/gefs
export EVSINgefs_bc=${COMIN}/${STEP}/${COMPONENT}/atmos.${INITDATE}/gefs_bc
export EVSINcmce=${COMIN}/${STEP}/${COMPONENT}/atmos.${INITDATE}/cmce
export EVSINcmce_bc=${COMIN}/${STEP}/${COMPONENT}/atmos.${INITDATE}/cmce_bc

export COMOUT=${COMOUT:-$(compath.py -o $NET/${evs_ver})}/$STEP/${COMPONENT} 
mkdir -p $COMOUT

export COMOUTgefs=${COMOUTgefs:-${COMOUT}/${RUN}.${INITDATE}/gefs}
export COMOUTcmce=${COMOUTcmce:-${COMOUT}/${RUN}.${INITDATE}/cmce}
export COMOUTecme=${COMOUTecme:-${COMOUT}/${RUN}.${INITDATE}/ecme}
export COMOUTnaefs=${COMOUT}
export COMOUTosi_saf=${COMOUTosi_saf:-${COMOUT}/${RUN}.${INITDATE}/osi_saf}
export COMOUTgefs_bc=${COMOUTgefs_bc:-${COMOUT}/${RUN}.${INITDATE}/gefs_bc}
export COMOUTcmce_bc=${COMOUTcmce_bc:-${COMOUT}/${RUN}.${INITDATE}/cmce_bc}
export COMOUTcompleted=${COMOUTcompleted:-${COMOUT}/${RUN}.${INITDATE}/completed}

if [ "${RUN}" == "headline" ]; then
    mkdir -p $COMOUTgefs $COMOUTcmce
elif [ "${RUN}" == "atmos" ]; then
    mkdir -p $COMOUTgefs $COMOUTcmce $COMOUTecme $COMOUTosi_saf $COMOUTcompleted
    if [ "${MODELNAME}" == "naefs" ]; then
        mkdir -p $COMOUTgefs_bc $COMOUTcmce_bc
    fi
elif [ "${RUN}" == "wave" ]; then
    mkdir -p $COMOUTgefs/${VERIF_CASE}
fi

####################################
# Execute the script                
####################################
$HOMEevs/scripts/${STEP}/${COMPONENT}/exevs_${STEP}_${COMPONENT}_${MODELNAME}_${RUN}.sh
export err=$?; err_chk

if [ "${KEEPDATA}" != "YES" ]; then
    cd ${DATAROOT}
    rm -rf ${DATA}
fi

date

