#!/bin/bash

########################################
# Preliminary data setup step  
########################################
set -x

echo "BEGIN: $(basename ${BASH_SOURCE[0]})"

# Shell Processing Variables
export PS4='$SECONDS + '
date

# LSF id (jobid) and Temp Directories
export pid=$$

export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-YES}
export SENDECF=${SENDECF:-YES}
export SENDMAIL=${SENDMAIL:-NO}

export DATA=${DATA:-${DATAROOT:?}/${jobid:?}}
mkdir -p $DATA
cd $DATA

################################
# Define NET/RUN variables
################################
export NET=${NET:-evs}
export STEP=${STEP:-stats}
export COMPONENT=${COMPONENT:-mesoscale}
export RUN=${RUN:-atmos}

export machine=${machine:-WCOSS2}
export MET_PLUS_PATH=${MET_PLUS_PATH:-$METPLUS_PATH}
export MET_PATH=$MET_ROOT
export MET_CONFIG="${MET_PLUS_PATH}/parm/met_config"
export HOMEevs=${HOMEevs:-${PACKAGEROOT}/${NET}.${evs_ver}} 
export EXECevs=${EXECevs:-$HOMEevs/exec}
export PARMevs=${PARMevs:-$HOMEevs/parm}
export USHevs=${USHevs:-$HOMEevs/ush}
export SCRIPTSevs=${SCRIPTSevs:-$HOMEevs/scripts}
export FIXevs=${FIXevs:-$HOMEevs/fix}
export MASKS=$FIXevs/masks
export MET_PLUS_CONF="${PARMevs}/metplus_config/${STEP}/${COMPONENT}/${VERIF_CASE}"
export vhr=${vhr:-00}
export cycle=t${vhr}z
setpdy.sh
. $DATA/PDY

export INITDATE=${INITDATE:-$PDYm1}
export OTLK_DATE=${OTLK_DATE:-$INITDATE}

export COMIN=${COMIN:-$(compath.py $envir/com/$NET/$evs_ver)}
export COMINnam=${COMINnam:-$(compath.py ${envir}/com/nam/${nam_ver})}
export COMINrap=${COMINrap:-$(compath.py ${envir}/com/rap/${rap_ver})}
export COMINobsproc=${COMINobsproc:-$(compath.py ${envir}/com/obsproc/${obsproc_ver})}
export DCOMINspc=${DCOMINspc:-$DCOMROOT}

export COMOUT=${COMOUT:-$(compath.py -o ${NET}/${evs_ver}/${STEP}/${COMPONENT})}
mkdir -p $COMOUT

export COMOUTotlk=${COMOUT}/${RUN}.${OTLK_DATE}/spc_otlk

# Execute the script.
$HOMEevs/scripts/${STEP}/${COMPONENT}/exevs_${COMPONENT}_${VERIF_CASE}_${STEP}.sh
 export err=$?; err_chk

# Clean Up
msg="JOB $job HAS COMPLETED NORMALLY."
if [ "$KEEPDATA" != "YES" ] ; then
  cd $DATA_IN
  rm -rf $DATA
fi

echo "END: $(basename ${BASH_SOURCE[0]})"
