#!/bin/bash
#  JOB card created for running METPlus-based Global ensemble verifications
#   By Binbin Zhou, IMSG@EMC/NCEP
#   Feb 2, 2022
#
#######################################################
set -x
##################################################
### SENDCOM  - Copy Files From TMPDIR to $COMOUT
### SENDDBN  - Issue DBNet Client Calls 
### SENDECF  - Flag Events on ecFLOW
### SENDMAIL - Send email if file is missing
##################################################
export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-YES}
export SENDECF=${SENDECF:-YES}
export SENDMAIL=${SENDMAIL:-NO}

#######################################################
# SET SHELL PROCESSING VARIABLES
#######################################################
date
export PS4='$SECONDS + '

export vhr=${vhr:-00}
export cycle=${cycle:-t${vhr}z}

##########################################################
# obtain unique LSF id (jobid) and make temp directories
##########################################################
export pid=$$
export DATA=${DATA:-${DATAROOT:?}/${jobid:?}}
mkdir -p $DATA
cd $DATA

export envir=${envir:-prod}

# Define COMIN/COMOUT variables:

echo ${COMPATH}

export NET=${NET:-evs}
export STEP=${STEP:-plots}
export COMPONENT=${COMPONENT:-global_ens}
export RUN=${RUN:-atmos}
export VERIF_CASE=${VERIF_CASE:-grid2obs}
export MODELNAME=${MODELNAME:-gefs}
export modsys=${modsys:-gefs}
export mod_ver=${mod_ver:-${gefs_ver}}

setpdy.sh
. ./PDY

########################################
# Set EVS directories
########################################
export HOMEevs=${HOMEevs:-${PACKAGEROOT}/${NET}.${evs_ver}}
export EXECevs=${EXECevs:-${HOMEevs}/exec}
export PARMevs=${PARMevs:-${HOMEevs}/parm}
export SCRIPTSevs=${SCRIPTSevs:-${HOMEevs}/scripts}
export USHevs=${USHevs:-${HOMEevs}/ush}
export FIXevs=${FIXevs:-${HOMEevs}/fix}

if [ "${RUN}" == "atmos" ] || [ "${RUN}" == "wmo" ] || [ "${RUN}" == "headline" ] ; then
    export VDATE=${VDATE:-$PDYm2}
fi

########################################
# Define COMIN/COMOUT variables
########################################
export COMIN=${COMIN:-$(compath.py ${envir}/com/${NET}/${evs_ver})}
export EVSIN=${EVSIN:-$COMIN/stats/$COMPONENT/$MODELNAME.$VDATE}
export EVSINapcp24mean=${EVSINapcp24mean:-$COMIN/stats/$COMPONENT/$RUN.$VDATE/apcp24_mean}
export COMOUT=${COMOUT:-$(compath.py -o $NET/${evs_ver})}/$STEP/$COMPONENT/$RUN.$VDATE
export DATA_IN=${DATA_IN:-$DATAROOT}

export run_mpi=${run_mpi:-yes}
export valid_time=${valid_time:-both}

export ush_dir=$USHevs/global_ens/ush_gens_plot_py

mkdir -p ${COMOUT}

########################################
# Execute the script
########################################
if [ "${valid_time}" == "separate" ] ; then
    $HOMEevs/scripts/${STEP}/${COMPONENT}/exevs_${COMPONENT}_${RUN}_${MODELNAME}_${VERIF_CASE}_separate_${STEP}.sh
else
    $HOMEevs/scripts/${STEP}/${COMPONENT}/exevs_${COMPONENT}_${RUN}_${MODELNAME}_${VERIF_CASE}_${STEP}.sh
fi
export err=$?; err_chk

if [ "${KEEPDATA}" != "YES" ]; then
    cd ${DATAROOT}
    rm -rf ${DATA}
fi

date

