#!/bin/bash

#################################
# SET SHELL PROCESSING VARIABLES 
#################################
set -x
export PS4='+ $SECONDS + '
date

#########################################################
# obtain unique LSF id (jobid) and make temp directories 
#########################################################
export DATA=${DATA:-${DATAROOT:?}/${jobid:?}}
mkdir -p $DATA
cd $DATA

##########################################
# Run setpdy and initialize PDY variables 
##########################################
export vhr=${vhr:-00}
export cycle=${cycle:-t${vhr}z}
setpdy.sh 17
. ./PDY
export VDATE=${VDATE:-${PDYm1}}
export NEXTDATE=${NEXTDATE:-${PDY}}

####################################
# Set data directives
####################################
export SENDECF=${SENDECF:-YES}
export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-YES}
export SENDMAIL=${SENDMAIL:-NO}
####################################
# Set EVS directories               
####################################
export HOMEevs=${HOMEevs:-${PACKAGEROOT}/${NET}.${evs_ver}}
export EXECevs=${EXECevs:-$HOMEevs/exec}
export FIXevs=${FIXevs:-$HOMEevs/fix}
export PARMevs=${PARMevs:-$HOMEevs/parm}
export USHevs=${USHevs:-$HOMEevs/ush}

####################################
# Define NET/RUN variables          
####################################
export NET=${NET:-evs}
export MODEL=${MODEL:-evs}
export STEP=${STEP:-stats}
export COMPONENT=${COMPONENT:-global_ens}
export MODELNAME=${MODELNAME:-gefs}
export MODNAM=$(echo $MODELNAME | tr '[a-z]' '[A-Z]')
export OBTYPE=${OBTYPE:-GDAS}
export RUN=${RUN:-wave}
export VERIF_CASE=${VERIF_CASE:-grid2obs}

####################################
# Define EVSIN/COMOUT variables     
####################################
export COMIN=${COMIN:-$(compath.py ${envir}/com/${NET}/${evs_ver})}
export COMINgefs=${COMINgefs:-$(compath.py ${envir}/com/${MODELNAME}/${gefs_ver})}
export EVSINgefs=${COMIN}/prep/${COMPONENT}
export EVSINgdasnc=${COMIN}/prep/${COMPONENT}

export COMOUT=${COMOUT:-$(compath.py -o ${NET}/${evs_ver})/${STEP}/${COMPONENT}}
export COMOUTsmall=${COMOUT}/${RUN}.${VDATE}/${MODELNAME}/${VERIF_CASE}
export COMOUTfinal=${COMOUT}/${MODELNAME}.${VDATE}

mkdir -p ${COMOUT} ${COMOUTsmall} ${COMOUTfinal} 

####################################
# Execute the script                
####################################
$HOMEevs/scripts/${STEP}/${COMPONENT}/exevs_${COMPONENT}_${RUN}_${VERIF_CASE}_${STEP}.sh 
export err=$?; err_chk

if [ "$KEEPDATA" != "YES" ] ; then
  rm -rf $DATA
fi

date
