#!/bin/ksh

set -xa
#######################################################
#######################################################

export cycle=t${cyc}z

export pid=$$
export DATA=${DATA:-${DATAROOT:?}/${jobid:?}}
rm -rf $DATA
mkdir -p $DATA
cd $DATA

# Run setpdy and initialize PDY variables
setpdy.sh
. $DATA/PDY

if [ $RUN = atmos ] || [ $RUN = wmo ] || [ $RUN = headline ] ; then
	  export VDATE=${VDATE:-$PDYm2}
fi

export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-YES}
export SENDECF=${SENDECF:-YES}

export COMIN=${COMIN:-$(compath.py  $envir/com/$NET/$evs_ver)}/stats/$COMPONENT/$MODELNAME.$VDATE
export COMINapcp24mean=${COMINspatial:-$(compath.py  $envir/com/$NET/$evs_ver)}/stats/$COMPONENT/$RUN.$VDATE/apcp24_mean
export COMINccpa24=${COMINspatial:-$(compath.py  $envir/com/$NET/$evs_ver)}/prep/$COMPONENT/$RUN.$VDATE
export COMOUT=${COMOUT:-$(compath.py -o $envir/com/$NET/${evs_ver})}/$STEP/$COMPONENT/$RUN.$VDATE
export DATA_IN=${DATA_IN:-$DATAROOT}
mkdir -p $COMOUT

export HOMEevs=${HOMEevs:-${PACKAGEROOT}/evs_gens.${evs_ver}}
export EXECevs=$HOMEevs/exec
export PARMevs=$HOMEevs/parm
export USHevs=$HOMEevs/ush
export SCRIPTevs=$HOMEevs/scripts
export FIXevs=${FIXevs:-$HOMEevs/fix}
export cartopyDataDir=${cartopyDataDir:-/apps/ops/prod/data/cartopy}

export run_mpi=${run_mpi:-yes}
export valid_time=${valid_time:-both}

export ush_dir=$USHevs/global_ens/ush_gens_plot_py


if [ $valid_time = separate ] ; then
  $HOMEevs/scripts/${COMPONENT}/${STEP}/exevs_${COMPONENT}_${RUN}_${MODELNAME}_${VERIF_CASE}_separate_${STEP}.sh
else
  $HOMEevs/scripts/${COMPONENT}/${STEP}/exevs_${COMPONENT}_${RUN}_${MODELNAME}_${VERIF_CASE}_${STEP}.sh
fi

msg="JOB $job HAS COMPLETED NORMALLY."
postmsg "$msg"

if [ "$KEEPDATA" != "YES" ] ; then
  cd $DATAROOT
  rm -rf $DATA
fi

date

