#!/bin/ksh

########################################
# Preliminary data setup step
########################################
set -x

##################################################
## SAVEGES  - Copy Files From TMPDIR to $GESdir
## SENDECF  - Flag Events on ecFLOW
## SENDCOM  - Copy Files From TMPDIR to $COMOUT
## SENDDBN  - Issue DBNet Client Calls
###################################################
export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-YES}
export SENDECF=${SENDECF:-YES}
export SENDMAIL=${SENDMAIL:-NO}

# ###################################
# SET SHELL PROCESSING VARIABLES
# ###################################
export PS4='$SECONDS + '
date

###########################################################
# obtain unique LSF id (jobid) and make temp directories
###########################################################
export DATA=${DATA:-${DATAROOT:?}/${jobid:?}}
mkdir -p $DATA
cd $DATA

export HOMEevs=${HOMEevs:-${PACKAGEROOT}/${NET}.${evs_ver}}
export EXECevs=${EXECevs:-$HOMEevs/exec}
export FIXevs=${FIXevs:-$HOMEevs/fix}
export PARMevs=${PARMevs:-$HOMEevs/parm}
export SCRIPTSevs=${SCRIPTSevs:-$HOMEevs/scripts}
export USHevs=${USHevs:-$HOMEevs/ush}

# Run setpdy and initialize PDY variables
 export vhr=${vhr:-00}
 export cycle=t${vhr}z
 setpdy.sh 31
 . ./PDY

export VDATE=${VDATE:-$PDYm2}

####################################
### Define NET/RUN variables
######################################
export NET=${NET:-evs}
export STEP=${STEP:-plots}
export COMPONENT=${COMPONENT:-analyses}
export RUN=${RUN:-atmos}

# Define COMIN/COMOUT variables:

echo $COMPATH

export COMIN=${COMIN:-$(compath.py ${envir}/com/${NET}/${evs_ver})}
export EVSINanl=${EVSINanl:-${COMIN}/stats/${COMPONENT}}
export COMOUT=${COMOUT:-$(compath.py -o ${NET}/${evs_ver})}
export COMOUTplots=${COMOUTplots:-${COMOUT}/${STEP}/${COMPONENT}/${RUN}.${VDATE}}
mkdir -m 775 -p $COMOUTplots

#######################################################################
# Execute the script.
#######################################################################

$HOMEevs/scripts/${STEP}/${COMPONENT}/exevs_${COMPONENT}_${VERIF_CASE}_${STEP}.sh

msg="JOB $job HAS COMPLETED NORMALLY."
postmsg "$msg"

if [ "$KEEPDATA" != "YES" ] ; then
  cd $DATAROOT
  rm -rf $DATA
fi

date
