#!/bin/bash 
date
export PS4=' $SECONDS + '
set -x

####################################
# obtain unique process id (pid) and make temp directory
####################################
export jobid=${jobid:-$job.o$$}
export DATA=${DATA:-${DATAROOT:?}/${jobid}}
mkdir -p $DATA
cd $DATA
export cycle=t${cyc}z

####################################
# File To Log Msgs
####################################
export jlogfile=${jlogfile:-${DATA}/jlogfile.${jobid}}

####################################
# Specify NET and RUN Name and model
####################################
export NET=${NET:-evs}
export COMPONENT=${COMPONENT:-hurricane}
export RUN=${RUN:-global_det} # global_det, global_ens, regional
export STEP=${STEP:-stats}  # plots, stats 
export VERIF_CASE=${VERIF_CASE:-tropcyc}  # tropcyc, tcgen  

####################################
# Determine Job Output Name on System
####################################
export pgmout="OUTPUT.$$"
export pgmerr=errfile

####################################
# SENDECF  - Flag Events on ecFLOW
# SENDCOM  - Copy Files From TMPDIR to $COMOUT
# SENDDBN  - Issue DBNet Client Calls
####################################
export SENDECF=${SENDECF:-NO}
export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-NO}

####################################
# Specify Execution Areas
####################################
export HOMEevs=${HOMEevs:-${PACKAGEHOME}}
export SCRIPTSevs=${SCRIPTSevs:-$HOMEevs/scripts}
export PARMevs=${PARMevs:-$HOMEevs/parm}

# Run setpdy and initialize PDY variables
##############################
echo "PDY=$PDY"
if [ -z $PDY ]; then
  setpdy.sh
  . ./PDY
fi

##############################################
# Define COM directories
# NOTE: All COMIN* variables must be defined in the upstream driver script
##############################################
if [ ${RUN} = "global_det" -a ${VERIF_CASE} = "tropcyc" ]; then
export YYYY=`echo ${PDY} | cut -c1-4`
export YY23=`echo ${PDY} | cut -c3-4`

export COMINvit=${COMINvit:-/your/TC/vitals/file}
export COMINtrack=${COMINtrack:-your/TC/track/file}
export COMINbdeckNHC=${COMINbdeckNHC:-/your/NHC/bdeck/data/dir}
export COMINbdeckJTWC=${COMINbdeckJTWC:-/your/JTWC/bdeck/data/dir}

elif [ ${RUN} = "global_ens" -a ${VERIF_CASE} = "tropcyc" ]; then
export YYYY=`echo ${PDY} | cut -c1-4`
export YY23=`echo ${PDY} | cut -c3-4`

export COMINvit=${COMINvit:-/your/TC/vitals/file}
export COMINtrack=${COMINtrack:-your/TC/track/file}
export COMINbdeckNHC=${COMINbdeckNHC:-/your/NHC/bdeck/data/dir}
export COMINbdeckJTWC=${COMINbdeckJTWC:-/your/JTWC/bdeck/data/dir}

elif [ ${RUN} = "global_det" -a ${VERIF_CASE} = "tcgen" ]; then
export YYYY=`echo ${PDY} | cut -c1-4`
#export YY23=`echo ${PDY} | cut -c3-4`

export COMINgenesis=${COMINgenesis:-/your/TC/genesis/data/dir}
export COMINadeckNHC=${COMINadeckNHC:-/your/NHC/adeck/data/dir}
export COMINbdeckNHC=${COMINbdeckNHC:-/your/NHC/bdeck/data/dir}
export COMINadeckJTWC=${COMINadeckJTWC:-/your/JTWC/adeck/data/dir}
export COMINbdeckJTWC=${COMINbdeckJTWC:-/your/JTWC/bdeck/data/dir}

elif [ ${RUN} = "regional" -a ${VERIF_CASE} = "tropcyc" ]; then
export YYYY=`echo ${PDY} | cut -c1-4`
export YY23=`echo ${PDY} | cut -c3-4`
export COMINvit=${COMINvit:-/your/TC/vitals/file}
export COMINtrack=${COMINtrack:-your/TC/track/file}
export COMINbdeckNHC=${COMINbdeckNHC:-/your/NHC/bdeck/data/dir}
export COMINbdeckJTWC=${COMINbdeckJTWC:-/your/JTWC/bdeck/data/dir}

elif [ ${RUN} = "regional_late" -a ${VERIF_CASE} = "tropcyc_ops" ]; then
export YYYY=`echo ${PDY} | cut -c1-4`
export YY23=`echo ${PDY} | cut -c3-4`
export COMINvit=${COMINvit:-/your/TC/vitals/file}
export COMINtrack=${COMINtrack:-your/TC/track/file}
export COMINbdeckNHC=${COMINbdeckNHC:-/your/NHC/bdeck/data/dir}
export COMINbdeckJTWC=${COMINbdeckJTWC:-/your/JTWC/bdeck/data/dir}

elif [ ${RUN} = "regional_late" -a ${VERIF_CASE} = "tropcyc_legacy" ]; then
export YYYY=`echo ${PDY} | cut -c1-4`
export YY23=`echo ${PDY} | cut -c3-4`
export COMINvit=${COMINvit:-/your/TC/vitals/file}
export COMINtrack=${COMINtrack:-your/TC/track/file}
export COMINbdeckNHC=${COMINbdeckNHC:-/your/NHC/bdeck/data/dir}
export COMINbdeckJTWC=${COMINbdeckJTWC:-/your/JTWC/bdeck/data/dir}

elif [ ${RUN} = "regional_early" -a ${VERIF_CASE} = "tropcyc_ops" ]; then
export YYYY=`echo ${PDY} | cut -c1-4`
export YY23=`echo ${PDY} | cut -c3-4`
export COMINvit=${COMINvit:-/your/TC/vitals/file}
export COMINtrack=${COMINtrack:-your/TC/track/file}
export COMINbdeckNHC=${COMINbdeckNHC:-/your/NHC/bdeck/data/dir}
export COMINbdeckJTWC=${COMINbdeckJTWC:-/your/JTWC/bdeck/data/dir}

elif [ ${RUN} = "regional_early" -a ${VERIF_CASE} = "tropcyc_legacy" ]; then
export YYYY=`echo ${PDY} | cut -c1-4`
export YY23=`echo ${PDY} | cut -c3-4`
export COMINvit=${COMINvit:-/your/TC/vitals/file}
export COMINtrack=${COMINtrack:-your/TC/track/file}
export COMINbdeckNHC=${COMINbdeckNHC:-/your/NHC/bdeck/data/dir}
export COMINbdeckJTWC=${COMINbdeckJTWC:-/your/JTWC/bdeck/data/dir}

else
echo "Job failed: unknown ${RUN} and ${VERIF_CASE}"
err_exit "FAILED ${jobid} - ERROR IN unknown ${RUN} and ${VERIF_CASE} - ABNORMAL EXIT"

fi

export COMOUT=${COMOUT:-$(compath.py -o ${NET}/${evs_ver})}
export COMOUT=${COMOUT}/${STEP}/${COMPONENT}/${RUN}/${VERIF_CASE}
mkdir -m 775 -p $COMOUT 

msg="HAS BEGUN on `hostname`"
postmsg "$jlogfile" "$msg"

#env

#############################################################
# Execute the script
${SCRIPTSevs}/${STEP}/${COMPONENT}/exevs_${COMPONENT}_${RUN}_${VERIF_CASE}_${STEP}.sh
export err=$?; err_chk

#############################################################

msg="JOB COMPLETED NORMALLY"
postmsg "$jlogfile" "$msg"

##############################
# Remove the Temporary working directory
##############################
if [[ $KEEPDATA != "YES" ]]; then
  rm -rf $DATA
fi

date
