#!/bin/bash

########################################
# Preliminary data setup step
########################################
set -x


##################################################
# SENDMAIL - Send Email Alerts When Missing Data
# SENDECF  - Flag Events on ecFLOW
# SENDCOM  - Copy Files From TMPDIR to $COMOUT
# SENDDBN  - Issue DBNet Client Calls
##################################################
export SENDMAIL=${SENDMAIL:-NO}
export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-YES}
export SENDECF=${SENDECF:-YES}


####################################
# SET SHELL PROCESSING VARIABLES
####################################
export PS4='$SECONDS + '
date


###########################################################
# obtain unique LSF id (jobid) and make temp directories
###########################################################
export pid=$$
export DATA=${DATA:-${DATAROOT:?}/${jobid:?}}
rm -rf $DATA
mkdir -p $DATA
cd $DATA


####################################
# Determine Job Output Name on System
####################################

####################################
# Define NET/RUN variables
####################################
export NET=${NET:-evs}
export STEP=${STEP:-stats}
export COMPONENT=${COMPONENT:-cam}
export RUN=${RUN:-atmos}
export VERIF_CASE=${VERIF_CASE:-grid2obs}
export MODELNAME=${MODELNAME:-rrfs}

####################################
# Set EVS directories
####################################
export HOMEevs=${HOMEevs:-${PACKAGEROOT}/${NET}.${evs_ver}}
export EXECevs=${EXECevs:-$HOMEevs/exec}
export FIXevs=${FIXevs:-$HOMEevs/fix}
export PARMevs=${PARMevs:-$HOMEevs/parm}
export SCRIPTSevs=${SCRIPTSevs:-$HOMEevs/scripts}
export USHevs=${USHevs:-$HOMEevs/ush}
export MASKS=${MASKS:-$FIXevs/masks}


####################################
# Run setpdy and initialize PDY variables
####################################
if [ "$MODELNAME" = "rap" ] && [ "$VERIF_CASE" = "snowfall" ]; then
    printf -v vhr "%02d" $((10#$vhr / 6 * 6))
    export vhr
fi
export cycle=${cycle:-t${vhr}z}
setpdy.sh 8
. ./PDY

if [ $VERIF_CASE = grid2obs ] ; then
    if [ "${RUN}" == "chem" ]; then
        export VDATE=${VDATE:-$PDYm3}
    else
        export VDATE=${VDATE:-$PDYm1}
    fi

elif [ $VERIF_CASE = precip ] ; then
    export VDATE=${VDATE:-$PDYm2}

elif [ $VERIF_CASE = radar ] ; then
    export VDATE=${VDATE:-$PDYm1}

elif [ $VERIF_CASE = snowfall ] ; then
    export VDATE=${VDATE:-$PDYm2}

elif [ $VERIF_CASE = severe ] ; then
   export VDATE=${VDATE:-$PDYm7}

   # Set correct date for SPC report data (set relative to VDATE) 
   export REP_DATE=$(finddate.sh $VDATE d-1)

elif [ $VERIF_CASE = spcoutlook ] ; then
   #for REFS grid2obs SPC outlook 
   export VDATE=${VDATE:-$PDYm1}

else

   err_exit "The provided VERIF_CASE, $VERIF_CASE, is not supported for the $COMPONENT $STEP step"

fi


####################################
# Define METplus variables
####################################
export MET_PLUS_CONF="${PARMevs}/metplus_config/${STEP}/${COMPONENT}/${VERIF_CASE}"


####################################
# Define COMIN/COMOUT variables
####################################
export COMIN=${COMIN:-$(compath.py $envir/com/$NET/$evs_ver)}
export COMINrap=${COMINrap:-$(compath.py $envir/com/rap/$rap_ver)}
export COMINhrrr=${COMINhrrr:-$(compath.py $envir/com/hrrr/$hrrr_ver)}
export COMINrrfs=${COMINrrfs:-$(compath.py $envir/com/rrfs/$rrfs_ver)}
export COMINrefs=${COMINrefs:-$(compath.py $envir/com/refs/$refs_ver)}
export COMINobsproc=${COMINobsproc:-$(compath.py $envir/com/obsproc/$obsproc_ver)}
export COMINccpa=${COMINccpa:-$(compath.py $envir/com/ccpa/$ccpa_ver)}
export DCOMINmrms=${DCOMINmrms:-$DCOMROOT/ldmdata/obs/upperair/mrms}
export DCOMINnohrsc=${DCOMINnohrsc:-$DCOMROOT}
export EVSINhrrr=${EVSINhrrr:-$COMIN/prep/$COMPONENT}
export EVSINrrfs=${EVSINrrfs:-$COMIN/prep/$COMPONENT}
export EVSINccpa=${EVSINccpa:-$COMIN/prep/$COMPONENT}
export EVSINmrms=${EVSINmrms:-$COMIN/prep/$COMPONENT}
export EVSINspcotlk=${EVSINspcotlk:-$COMIN/prep/$COMPONENT}
export EVSINfcst=${EVSINfcst:-$COMIN/prep/$COMPONENT}
export EVSINspclsr=${EVSINspclsr:-$COMIN/prep/$COMPONENT}

export COMOUT=${COMOUT:-$(compath.py -o $NET/$evs_ver/$STEP/$COMPONENT)}

[[ ! -d $COMOUT ]] && mkdir -p $COMOUT

export COMOUTfinal=${COMOUT}/${MODELNAME}.${VDATE}
[[ ! -d $COMOUTfinal ]] && mkdir -p $COMOUTfinal 
if [ "$VERIF_CASE" != "severe" ]; then
    export COMOUTsmall=${COMOUT}/${RUN}.${VDATE}/${MODELNAME}/${VERIF_CASE}
    [[ ! -d "$COMOUTsmall" ]] && mkdir -p "$COMOUTsmall"
fi

if [[ "${RUN}" == "chem" ]]; then
    export EVSINrrfs=${EVSINrrfs:-${COMIN}/prep/${COMPONENT}}
    export DATA_TYPE=${DATA_TYPE:-aeronet_aod}
    # alternative choice is an option different from aqobs
    export airnow_hourly_type=${airnow_hourly_type:-aqobs}
    export restart_mode=${restart_mode:-YES}
fi

####################################
# Execute the script 
####################################
if [[ "$VERIF_CASE" = "radar" || "$VERIF_CASE" = "severe" ]]; then
    $HOMEevs/scripts/${STEP}/${COMPONENT}/exevs_${STEP}_${COMPONENT}_${VERIF_CASE}.sh
elif [[ "$MODELNAME" = "rrfs_firewxnest" || "${MODELNAME}" = "rap" ]]; then
    $HOMEevs/scripts/${STEP}/${COMPONENT}/exevs_${STEP}_${COMPONENT}_${MODELNAME}_${VERIF_CASE}.sh
elif [[ "${MODELNAME}" = *"rrfsmem"* ]]; then
    $HOMEevs/scripts/${STEP}/${COMPONENT}/exevs_${STEP}_rrfsmem_${VERIF_CASE}.sh
elif [ "${RUN}" == "chem" ]; then
    ${HOMEevs}/scripts/${STEP}/${COMPONENT}/exevs_${STEP}_${COMPONENT}_${MODELNAME}_${RUN}_${VERIF_CASE}.sh
else
    $HOMEevs/scripts/${STEP}/${COMPONENT}/exevs_${STEP}_${MODELNAME}_${VERIF_CASE}.sh
fi

export err=$?; err_chk

if [ "$KEEPDATA" != "YES" ]; then
   cd $DATAROOT
   rm -rf $DATA
fi

date
