#!/bin/bash
# JOB card created for aigefs stats jobs
# Updated by L. Gwen Chen (lichuan.chen@noaa.gov), 10/14/2025

########################################
# Preliminary data setup step
########################################
set -x

####################################
# SET SHELL PROCESSING VARIABLES
####################################
export PS4='$SECONDS + '
date

###########################################################
# obtain unique LSF id (jobid) and make temp directories
###########################################################
export pid=$$
export DATA=${DATA:-${DATAROOT:?}/${jobid:?}}
mkdir -p $DATA
cd $DATA

####################################
# Define NET/RUN variables
####################################
export NET=${NET:-evs}
export STEP=${STEP:-stats}
export COMPONENT=${COMPONENT:-aigefs}
export RUN=${RUN:-atmos}
export MODELNAME=${MODELNAME:-aigefs}
export MODNAM=$(echo $MODELNAME | tr '[a-z]' '[A-Z]')
export VERIF_CASE=${VERIF_CASE:-grid2obs}

####################################
# Set EVS directories
####################################
export HOMEevs=${HOMEevs:-${PACKAGEROOT}/${NET}.${evs_ver}}
export EXECevs=${EXECevs:-${HOMEevs}/exec}
export PARMevs=${PARMevs:-${HOMEevs}/parm}
export SCRIPTSevs=${SCRIPTSevs:-${HOMEevs}/scripts}
export USHevs=${USHevs:-${HOMEevs}/ush}
export FIXevs=${FIXevs:-${HOMEevs}/fix}

##########################################
# Run setpdy and initialize PDY variables 
##########################################
export vhr=${vhr:-00}
export cycle=${cycle:-t${vhr}z}
setpdy.sh 20
. ./PDY

if [ "${RUN}" == "atmos" ] ; then
    export VDATE=${VDATE:-$PDYm2}
fi

##################################################
### SENDCOM  - Copy Files From TMPDIR to $COMOUT
### SENDDBN  - Issue DBNet Client Calls 
### SENDECF  - Flag Events on ecFLOW
### SENDMAIL - Send email if file is missing
##################################################
export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-YES}
export SENDECF=${SENDECF:-YES}
export SENDMAIL=${SENDMAIL:-NO}

####################################
# Define COMIN/COMOUT variables
####################################
export COMIN=${COMIN:-$(compath.py ${envir}/com/${NET}/${evs_ver})}
export COMINgefs=${COMINgefs:-$(compath.py ${envir}/com/gefs/${gefs_ver})}
export EVSIN=${EVSIN:-${COMIN}/prep/${COMPONENT}/${RUN}}
export EVSINgefs=${COMIN}/prep/${COMPONENT}
export EVSINaigefs=${COMIN}/prep/${COMPONENT}
export EVSINhgefs=${COMIN}/prep/${COMPONENT}
export EVSINgdasnc=${COMIN}/prep/${COMPONENT}

export COMOUT=${COMOUT:-$(compath.py -o ${NET}/${evs_ver})}/${STEP}/${COMPONENT}
export COMOUTsmall=${COMOUT}/${RUN}.${VDATE}/${MODELNAME}/${VERIF_CASE}
export COMOUTfinal=${COMOUT}/${MODELNAME}.${VDATE}

mkdir -p ${COMOUT} ${COMOUTsmall} ${COMOUTfinal}

####################################
# Execute the script                
####################################    
if [ "${RUN}" == "atmos" ] ; then
    if [ "${VERIF_CASE}" == "grid2grid" ] ; then
        $HOMEevs/scripts/${STEP}/${COMPONENT}/exevs_${STEP}_${COMPONENT}_${RUN}_${VERIF_CASE}.sh $VDATE $MODELNAME upper
    elif [ "${VERIF_CASE}" == "grid2obs" ] ; then
        $HOMEevs/scripts/${STEP}/${COMPONENT}/exevs_${STEP}_${COMPONENT}_${RUN}_grid2obs.sh $VDATE $MODELNAME $VERIF_CASE
    else
        $HOMEevs/scripts/${STEP}/${COMPONENT}/exevs_${STEP}_${COMPONENT}_${RUN}_grid2grid.sh $VDATE $MODELNAME $VERIF_CASE
    fi
fi
export err=$?; err_chk

if [ "${KEEPDATA}" != "YES" ]; then
    cd ${DATAROOT}
    rm -rf ${DATA}
fi

date

