#!/bin/bash

#################################
# SET SHELL PROCESSING VARIABLES 
#################################
set -xa
# ###################################
# # SET SHELL PROCESSING VARIABLES
# # ###################################
date
export PS4='$SECONDS + '

###########################################################
### obtain unique LSF id (jobid) and make temp directories
#############################################################
## export DATA=${DATA:-$DATAROOT/$NET/${evs_ver}}
export DATA=${DATA:-${DATAROOT:?}/${jobid:?}}
mkdir -p $DATA
cd $DATA

####################################
### Determine Job Output Name on System
######################################
export cycle=${cycle:t${cyc}z}

setpdy.sh 8
. ./PDY

export envir=${envir:-prod}
export DCOMROOT=${DCOMROOT:-/lfs/h1/ops/$envir/dcom}

echo $COMPATH

export NET=${NET:-evs}
export STEP=${STEP:-stats}
export COMPONENT=${COMPONENT:-global_ens}
export RUN=${RUN:-chem}
export VERIF_CASE=${VERIF_CASE:-grid2grid}
export MODELNAME=${MODELNAME:-gefs}
export=${modsys:-gefs}
export mod_ver=${mod_ver:-${gefs_ver}}

export HOMEevs=${HOMEevs:-${PACKAGEROOT}/${NET}.${evs_ver}}
export SCRIPTSevs=${SCRIPTSevs:-$HOMEevs/scripts}
export USHevs=${USHevs:-$HOMEevs/ush/$COMPONENT}
export EXECevs=${EXECevs:-$HOMEevs/exec}
export PARMevs=${PARMevs:-$HOMEevs/parm/metplus_config}
export FIXevs=${FIXevs:-$HOMEevs/fix}
## to be determined export MASKS=${MASKS:-$FIXevs/masks}

## PDYm2 for abi, viirs
## PDYm3 for goes5, icap
export VDATE=${VDATE:-${PDYm2}}

# Define COMIN/COMOUT variables:

## export COMINobs=${COMINobs:-${DCOMROOT}}   ==> rename to DCOMIN
## export COMINfcst=${COMINfcst:-$(compath.py $NET/${evs_ver}/prep/$COMPONENT)} ==> rename to EVSINgefs
export COMIN=${COMIN:-$(compath.py $envir/com/$NET/${evs_ver})}
export DCOMIN=${DCOMIN:-${DCOMROOT}}
export EVSINgefs=${EVSINgefs:-${COMIN}/prep/$COMPONENT)}
export COMOUT=${COMOUT:-$(compath.py -o $NET/${evs_ver})}
export OBTTYPE=${OBTTYPE:-goes}
export COMOUTsmall=${COMOUTsmall:-$COMOUT/$STEP/$COMPONENT/$OBTTYPE.$VDATE}
export COMOUTfinal=${COMOUTfinal:-$COMOUT/$STEP/$COMPONENT/$COMPONENT.$VDATE}
export CONFIGevs=${CONFIGevs:-${PARMevs}/${STEP}/$COMPONENT/${RUN}_${VERIF_CASE}}

mkdir -p ${COMOUTsmall} ${COMOUTfinal}
#######################################################################
## Execute the script.
#########################################################################

???? what is the default VAR

if [ $OBTTYPE = 'icap' ] ; then
    export VDATE=${PDYm3}
    for VAR in $VARS; do
        export VAR
        $HOMEevs/scripts/$COMPONENT/$STEP/exevs_${COMPONENT}_${RUN}_${VERIF_CASE}_${OBTTYPE}_${STEP}.sh
    done
elif [ $OBTTYPE = 'geos5' ] ; then
    export VDATE=${PDYm3}
    for VAR in $VARS; do
        export VAR
        $HOMEevs/scripts/$COMPONENT/$STEP/exevs_${COMPONENT}_${RUN}_${VERIF_CASE}_${OBTTYPE}_${STEP}.sh
    done
elif [ $OBTTYPE = 'viirs' ] ; then            
    $HOMEevs/scripts/$COMPONENT/$STEP/exevs_${COMPONENT}_${RUN}_${VERIF_CASE}_${OBTTYPE}_${STEP}.sh
elif [ $OBTTYPE = 'abi' ] ; then
    $HOMEevs/scripts/$COMPONENT/$STEP/exevs_${COMPONENT}_${RUN}_${VERIF_CASE}_${OBTTYPE}_${STEP}.sh
else
    echo "Wrong OBTTYPE: $OBTTYPE"
    exit 
fi

msg="JOB $job HAS COMPLETED NORMALLY."
postmsg "$msg"

if [ "$KEEPDATA" != "YES" ]; then
    cd $DATAROOT
    rm -rf $DATA
fi

