#!/bin/bash
#  JOB card created for running METPlus-based Global ensemble verifications
#   By Binbin Zhou, IMSG@EMC/NCEP
#   Feb 2, 2022
#
#######################################################
set -x
##################################################
### SENDCOM  - Copy Files From TMPDIR to $COMOUT
### SENDDBN  - Issue DBNet Client Calls 
### SENDECF  - Flag Events on ecFLOW
### SENDMAIL - Send email if file is missing
##################################################
export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-YES}
export SENDECF=${SENDECF:-YES}
export SENDMAIL=${SENDMAIL:-NO}

#######################################################
# SET SHELL PROCESSING VARIABLES
#######################################################
date
export PS4='$SECONDS + '

export vhr=${vhr:-00}
export cycle=${cycle:-t${vhr}z}

##########################################################
# obtain unique LSF id (jobid) and make temp directories
##########################################################
export pid=$$
export DATA=${DATA:-${DATAROOT:?}/${jobid:?}}
if [ "${RUN}" != "chem" ]; then
    rm -rf $DATA
fi
mkdir -p $DATA
cd $DATA

export envir=${envir:-prod}

# Define COMIN/COMOUT variables:

echo ${COMPATH}

export NET=${NET:-evs}
export STEP=${STEP:-prep}
export COMPONENT=${COMPONENT:-global_chem}
export RUN=${RUN:-atmos}
export VERIF_CASE=${VERIF_CASE:-grid2obs}
export MODELNAME=${MODELNAME:-gefs}
export modsys=${modsys:-gefs}
export mod_ver=${mod_ver:-${gefs_ver}}

# Run setpdy and initialize PDY variables
setpdy.sh 8
. ./PDY

export HOMEevs=${HOMEevs:-${PACKAGEROOT}/${NET}.${evs_ver}}
export EXECevs=${EXECevs:-${HOMEevs}/exec}
export PARMevs=${PARMevs:-${HOMEevs}/parm}
export SCRIPTSevs=${SCRIPTSevs:-${HOMEevs}/scripts}
export USHevs=${USHevs:-${HOMEevs}/ush}
export FIXevs=${FIXevs:-${HOMEevs}/fix}

export INITDATE=${INITDATE:-${PDYm3}}

#
export COMIN=${COMIN:-$(compath.py $envir/com/$NET/$evs_ver)}
export COMINgefs=${COMINgefs:-$(compath.py $envir/com/gefs/${gefs_ver})}

export DCOMINairnow=${DCOMINairnow:-${DCOMROOT}}
export DCOMINaeronet=${DCOMINaeronet:-${DCOMROOT}}
export COMOUT=${COMOUT:-$(compath.py -o ${NET}/${evs_ver})}
export COMOUTprep=${COMOUTprep:-${COMOUT}/${STEP}/${COMPONENT}/${RUN}.${INITDATE}/${MODELNAME}}
   
mkdir -p ${COMOUT} ${COMOUTprep}
   
# alternative choice is an option different from aqobs
export airnow_hourly_type=${airnow_hourly_type:-aqobs}
export HOURLY_NCOL=${HOURLY_NCOL:-34}


${HOMEevs}/scripts/${STEP}/${COMPONENT}/exevs_${COMPONENT}_${RUN}_${VERIF_CASE}_${STEP}.sh

if [ "${KEEPDATA}" != "YES" ]; then
    cd ${DATAROOT}
    rm -rf ${DATA}
fi

date

