#!/bin/bash

set -x

# ###################################
# SET SHELL PROCESSING VARIABLES
# ###################################
export PS4='$SECONDS + ' 
date

export machine="WCOSS2"

###########################################################
# obtain unique LSF id (jobid) and make temp directories
###########################################################
export DATA=${DATA:-${DATAROOT:?}/${jobid:?}}
mkdir -p $DATA
cd $DATA 
 
################################################################
# SENDCOM=YES--Copy files from TMPDIR to $COMOUT
# SENDECF=YES--Flag events on ecflow
# SENDDBN=YES--Issue DBNet client calls
################################################################
export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-YES}       # need to set to NO for testing
export SENDECF=${SENDECF:-YES}
export SENDDBN_NTC=${SENDDBN_NTC:-NO}
################################################################
# Specify Execution Areas
################################################################
export HOMEevs=${HOMEevs:-${PACKAGEROOT}/${NET}.${evs_ver}}
export EXECevs=${EXECevs:-$HOMEevs/exec}
export PARMevs=${PARMevs:-$HOMEevs/parm}
export USHevs=${USHevs:-$HOMEevs/ush}
export FIXevs=${FIXevs:-$HOMEevs/fix}

export members="NA"


# Run setpdy and initialize PDY variables
export vhr=${vhr:-00}
export cycle=${cycle:-t${vhr}z}
setpdy.sh $DAYS
. ./PDY

export VDATE_START=${VDATE_START:-$(eval echo \$PDYm$DAYS)}
export VDATE_END=${VDATE_END:-$PDYm2}

#################################################
# Set up the INPUT and OUTPUT directories
#################################################
export COMIN=${COMIN:-$(compath.py ${envir}/com/$NET/$evs_ver)}
export EVSINgefs=${EVSINgefs:-$COMIN/stats/$COMPONENT/gefs}
export EVSINcfs=${EVSINcfs:-$COMIN/stats/$COMPONENT/cfs}
export COMOUT=${COMOUT:-$(compath.py -o $NET/$evs_ver/$STEP/$COMPONENT)}/$RUN.$VDATE_END

mkdir -p $COMOUT


echo Actual output starts here


#######################################################################
# Execute the script.
#######################################################################
$HOMEevs/scripts/$STEP/$COMPONENT/exevs_${COMPONENT}_${VERIF_CASE}_${STEP}.sh
export err=$?; err_chk


if [ "$KEEPDATA" != "YES" ] ; then
  cd $DATAROOT
  rm -rf $DATA
fi

date
