#!/bin/bash

set -xa

########################################
# Preliminary data setup step
########################################

##################################################
### SENDCOM  - Copy Files From TMPDIR to $COMOUT
### SENDDBN  - Issue DBNet Client Calls 
### SENDECF  - Flag Events on ecFLOW
### SENDMAIL - Send email if file is missing
###################################################
export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-NO}
export SENDECF=${SENDECF:-YES}
export SENDMAIL=${SENDMAIL:-NO}

###################################
# SET SHELL PROCESSING VARIABLES
# ###################################
date
export PS4='$SECONDS + '

# ###########################################################
# # obtain unique LSF id (jobid) and make temp directories
# ###########################################################
## to be removed export DATA=${DATA:-$DATAROOT/$NET/${evs_ver}}
export DATA=${DATA:-${DATAROOT:?}/${jobid:?}}
mkdir -p $DATA
cd $DATA

export cycle=${cycle:-t${cyc}z}

setpdy.sh 8
. ./PDY

export envir=${envir:-prod}
export DCOMROOT=${DCOMROOT:-/lfs/h1/ops/$envir/dcom}

export HOMEevs=${HOMEevs:-${PACKAGEROOT}/${NET}.${evs_ver}}
export SCRIPTSevs=${SCRIPTSevs:-$HOMEevs/scripts}
export EXECevs=${EXECevs:-$HOMEevs/exec}
export PARMevs=${PARMevs:-$HOMEevs/parm/metplus_config}
export FIXevs=${FIXevs:-$HOMEevs/fix}

# Define COMIN/COMOUT variables:

echo $COMPATH

export NET=${NET:-evs}
export STEP=${STEP:-prep}
export COMPONENT=${COMPONENT:-global_ens}
export RUN=${RUN:-chem}
export VERIF_CASE=${VERIF_CASE:-grid2obs}
export MODELNAME=${MODELNAME:-gefs}
export modsys=${modsys:-gefs}
export mod_ver=${mod_ver:-${gefs_ver}}

export USHevs=${USHevs:-$HOMEevs/ush/$COMPONENT}
export CONFIGevs=${CONFIGevs:-${PARMevs}/${STEP/$COMPONENT}}

## export COMINobs=${COMINobs:-$(compath.py $envir/dcom)}  ==> COMINobs renamed to DCOMIN
export COMIN=${COMIN:-$(compath.py $envir/com/$NET/${evs_ver})}
export DCOMIN=${DCOMIN:-${DCOMROOT}}
export COMOUT=${COMOUT:-$(compath.py -o $NET/${evs_ver})}
export COMOUTprep=${COMOUTprep:-$COMOUT/$STEP/$COMPONENT}

#######################################################################
# Execute the script.
#######################################################################
$HOMEevs/scripts/${STEP}/${COMPONENT}/exevs_${MODELNAME}_${RUN}_${VERIF_CASE}_${STEP}.sh

msg="JOB $job HAS COMPLETED NORMALLY."
postmsg "$msg"

if [ "$KEEPDATA" != "YES" ]; then
    cd $DATAROOT
    rm -rf $DATA
fi

