#!/bin/bash

set -xa

#################################
#  Preliminary data setup step
#################################
 
##################################################
### SENDCOM  - Copy Files From TMPDIR to $COMOUT
### SENDDBN  - Issue DBNet Client Calls 
### SENDECF  - Flag Events on ecFLOW
### SENDMAIL - Send email if file is missing
###################################################
export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-NO}
export SENDECF=${SENDECF:-YES}
export SENDMAIL=${SENDMAIL:-NO}

###################################
# SET SHELL PROCESSING VARIABLES
# ###################################
date
export PS4='$SECONDS + '

###########################################################
### obtain unique LSF id (jobid) and make temp directories
#############################################################
## export DATA=${DATA:-$DATAROOT/$NET/${evs_ver}}
export DATA=${DATA:-${DATAROOT:?}/${jobid:?}}
mkdir -p $DATA
cd $DATA

export cycle=${cycle:t${cyc}z}

setpdy.sh 8
. ./PDY

export envir=${envir:-prod}

# Define COMIN/COMOUT variables:

echo $COMPATH

export NET=${NET:-evs}
export STEP=${STEP:-stats}
export COMPONENT=${COMPONENT:-global_ens}
export RUN=${RUN:-chem}
export VERIF_CASE=${VERIF_CASE:-grid2grid}
export MODELNAME=${MODELNAME:-gefs}
export=${modsys:-gefs}
export mod_ver=${mod_ver:-${gefs_ver}}

export HOMEevs=${HOMEevs:-${PACKAGEROOT}/${NET}.${evs_ver}}
export SCRIPTSevs=${SCRIPTSevs:-$HOMEevs/scripts}
export USHevs=${USHevs:-$HOMEevs/ush/$COMPONENT}
export EXECevs=${EXECevs:-$HOMEevs/exec}
export PARMevs=${PARMevs:-$HOMEevs/parm/metplus_config}
export FIXevs=${FIXevs:-$HOMEevs/fix}
## to be determined export MASKS=${MASKS:-$FIXevs/masks}

## PDYm2 for abi, viirs
## PDYm3 for goes5, icap
export VDATE=${VDATE:-${PDYm2}}

export OBTTYPE=${OBTTYPE:-geos5}

## export COMINobs=${COMINobs:-${DCOMROOT}}   ==> rename to DCOMIN
export COMIN=${COMIN:-$(compath.py $envir/com/$NET/${evs_ver})}
export COMINgefs=${COMINgefs:-$(compath.py -o ${modsys}/${mod_ver}}
export DCOMIN=${DCOMIN:-${DCOMROOT}}
export EVSINgefs=${EVSINgefs:-${COMIN}/prep/$COMPONENT)}
export COMOUT=${COMOUT:-$(compath.py -o $NET/${evs_ver})}
export COMOUTsmall=${COMOUTsmall:-$COMOUT/$STEP/$COMPONENT/$OBTTYPE.$VDATE}
export COMOUTfinal=${COMOUTfinal:-$COMOUT/$STEP/$COMPONENT/$COMPONENT.$VDATE}

mkdir -p ${COMOUTsmall} ${COMOUTfinal}
#######################################################################
## Execute the script.
#########################################################################
$HOMEevs/scripts/$COMPONENT/$STEP/exevs_${COMPONENT}_${RUN}_${VERIF_CASE}_${STEP}.sh

msg="JOB $job HAS COMPLETED NORMALLY."
postmsg "$msg"

if [ "$KEEPDATA" != "YES" ]; then
    cd $DATAROOT
    rm -rf $DATA
fi

