#!/bin/bash
# JOB card created for aigefs plots jobs
# Updated by L. Gwen Chen (lichuan.chen@noaa.gov), 10/21/2025

########################################
# Preliminary data setup step
########################################
set -x

####################################
# SET SHELL PROCESSING VARIABLES
####################################
export PS4='$SECONDS + '
date

###########################################################
# obtain unique LSF id (jobid) and make temp directories
###########################################################
export pid=$$
export DATA=${DATA:-${DATAROOT:?}/${jobid:?}}
mkdir -p $DATA
cd $DATA

####################################
# Define NET/RUN variables
####################################
export NET=${NET:-evs}
export STEP=${STEP:-plots}
export COMPONENT=${COMPONENT:-aigefs}
export RUN=${RUN:-atmos}
export MODELNAME=${MODELNAME:-aigefs}
export MODNAM=$(echo $MODELNAME | tr '[a-z]' '[A-Z]')
export VERIF_CASE=${VERIF_CASE:-grid2obs}
export modsys=${modsys:-aigefs}
export mod_ver=${mod_ver:-${aigefs_ver}}

####################################
# Set EVS directories
####################################
export HOMEevs=${HOMEevs:-${PACKAGEROOT}/${NET}.${evs_ver}}
export EXECevs=${EXECevs:-${HOMEevs}/exec}
export PARMevs=${PARMevs:-${HOMEevs}/parm}
export SCRIPTSevs=${SCRIPTSevs:-${HOMEevs}/scripts}
export USHevs=${USHevs:-${HOMEevs}/ush}
export ush_dir=${USHevs}/${COMPONENT}/ush_gens_plot_py
export FIXevs=${FIXevs:-${HOMEevs}/fix}

##########################################
# Run setpdy and initialize PDY variables 
##########################################
export vhr=${vhr:-00}
export cycle=${cycle:-t${vhr}z}
setpdy.sh 90
. ./PDY

if [ "${RUN}" == "atmos" ] ; then
    export VDATE=${VDATE:-${PDYm2}}
fi

##################################################
### SENDCOM  - Copy Files From TMPDIR to $COMOUT
### SENDDBN  - Issue DBNet Client Calls 
### SENDECF  - Flag Events on ecFLOW
### SENDMAIL - Send email if file is missing
##################################################
export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-YES}
export SENDECF=${SENDECF:-YES}
export SENDMAIL=${SENDMAIL:-NO}

########################################
# Define COMIN/COMOUT variables
########################################
export COMIN=${COMIN:-$(compath.py ${envir}/com/${NET}/${evs_ver})}
export EVSIN=${EVSIN:-$COMIN/stats/$COMPONENT/$MODELNAME.$VDATE}
export EVSINapcp24mean=${EVSINapcp24mean:-$COMIN/stats/$COMPONENT/$RUN.$VDATE/apcp24_mean}
export COMOUT=${COMOUT:-$(compath.py -o $NET/${evs_ver})}/$STEP/$COMPONENT/$RUN.$VDATE
export DATA_IN=${DATA_IN:-$DATAROOT}

export run_mpi=${run_mpi:-yes}
export valid_time=${valid_time:-both}

mkdir -p ${COMOUT}

########################################
# Execute the script
########################################
if [ "${valid_time}" == "separate" ] ; then
    $HOMEevs/scripts/${STEP}/${COMPONENT}/exevs_${STEP}_${COMPONENT}_${RUN}_${MODELNAME}_${VERIF_CASE}_separate.sh
elif [ "${valid_time}" == "both" ] ; then
    $HOMEevs/scripts/${STEP}/${COMPONENT}/exevs_${STEP}_${COMPONENT}_${RUN}_${MODELNAME}_${VERIF_CASE}.sh
fi
export err=$?; err_chk

if [ "${KEEPDATA}" != "YES" ]; then
    cd ${DATAROOT}
    rm -rf ${DATA}
fi

date

