#!/bin/bash
###############################################################################
# Job Name: JEVS_RTOFS_PLOTS
# Purpose: To create plots for RTOFS forecast verification using MET/METplus.
# Author: L. Gwen Chen (lichuan.chen@noaa.gov)
###############################################################################

set -x

########################################
# Preliminary data setup step
########################################

export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-YES}
export SENDECF=${SENDECF:-YES}
export SENDMAIL=${SENDMAIL:-NO}

# ###################################
# SET SHELL PROCESSING VARIABLES
# ###################################
export PS4='$SECONDS + '
date

###########################################################
# obtain unique LSF id (jobid) and make temp directories
###########################################################
export pid=$$
export DATA=${DATA:-${DATAROOT:?}/${jobid:?}}
mkdir -p $DATA
cd $DATA

####################################
# Define NET/RUN variables
####################################
export NET=${NET:-evs}
export STEP=${STEP:-plots}
export COMPONENT=${COMPONENT:-rtofs}
export RUN=${RUN:-argo}
export VERIF_CASE=${VERIF_CASE:-grid2obs}

##################################
# Set EVS directories
####################################
export HOMEevs=${HOMEevs:-${PACKAGEROOT}/${NET}.${evs_ver}}
export EXECevs=${EXECevs:-$HOMEevs/exec}
export FIXevs=${FIXevs:-$HOMEevs/fix}
export PARMevs=${PARMevs:-$HOMEevs/parm}
export SCRIPTSevs=${SCRIPTSevs:-$HOMEevs/scripts}
export CONFIGevs=${CONFIGevs:-$HOMEevs/parm/metplus_config}
export USHevs=${USHevs:-$HOMEevs/ush}
export MASKS=${MASKS:-$FIXevs/masks}

##########################################
# Run setpdy and initialize PDY variables
#########################################
export vhr=${vhr:-"00"}
export cycle=${cycle:-t${vhr}z}
setpdy.sh
. ./PDY
export VDATE=${VDATE:-$PDYm3}

################################
# define COMIN/COMOUT variables
###############################
export COMIN=${COMIN:-$(compath.py $envir/com/$NET/${evs_ver})}
export COMOUT=${COMOUT:-$(compath.py -o $NET/${evs_ver})}
export COMOUTplots=${COMOUTplots:-$COMOUT/$STEP/$COMPONENT/$COMPONENT.$VDATE}
export COMOUTplotsheadline=${COMOUTplotsheadline:-$COMOUT/$STEP/$COMPONENT/headline.$VDATE}

mkdir -p $COMOUT

if [ $RUN = headline ]; then
    mkdir -p $COMOUTplotsheadline
else
    mkdir -p $COMOUTplots
fi

#######################################################################
# Execute the script
#######################################################################
env
$HOMEevs/scripts/$STEP/$COMPONENT/exevs_${COMPONENT}_${RUN}_${VERIF_CASE}_${STEP}.sh
export err=$?; err_chk

if [ "$KEEPDATA" != "YES" ] ; then
  cd $DATAROOT
  rm -rf $DATA
fi

date
