#!/bin/bash

set -x

# ###################################
# SET SHELL PROCESSING VARIABLES
# ###################################
export PS4='$SECONDS + ' 
date

export machine="WCOSS2"

###########################################################
# obtain unique LSF id (jobid) and make temp directories
###########################################################
export DATA=${DATA:-${DATAROOT:?}/${jobid:?}}
mkdir -p $DATA
cd $DATA 

################################################################
# SENDCOM=YES--Copy files from TMPDIR to $COMOUT
# SENDMAIL=YES--Send missing data emails
# SENDECF=YES--Flag events on ecflow
# SENDDBN=YES--Issue DBNet client calls
################################################################
export SENDCOM=${SENDCOM:-YES}
export SENDMAIL=${SENDMAIL:-NO}
export SENDDBN=${SENDDBN:-YES}       # need to set to NO for testing
export SENDECF=${SENDECF:-YES}
export SENDDBN_NTC=${SENDDBN_NTC:-NO}
################################################################
# Specify Execution Areas
################################################################
export HOMEevs=${HOMEevs:-${PACKAGEROOT}/${NET}.${evs_ver}}
export EXECevs=${EXECevs:-$HOMEevs/exec}
export PARMevs=${PARMevs:-$HOMEevs/parm}
export USHevs=${USHevs:-$HOMEevs/ush}
export FIXevs=${FIXevs:-$HOMEevs/fix}

export gefs_members="30"

export cfs_members="4"

# Run setpdy and initialize PDY variables
export vhr=${vhr:-00}
export cycle=${cycle:-t${vhr}z}
setpdy.sh
. ./PDY

export INITDATE=$PDYm2

#################################################
# Set up the INPUT and OUTPUT directories
#################################################
export COMINgefs=${COMINgefs:-$(compath.py ${envir}/com/gefs/${gefs_ver}/gefs.$INITDATE)}
export COMINcfs=${COMINcfs:-$(compath.py ${envir}/com/cfs/${cfs_ver}/cfs.$INITDATE)}
export COMINgfs=${COMINgfs:-$(compath.py ${envir}/com/gfs/${gfs_ver})}
export DCOMINecmwf=${DCOMINecmwf:-$DCOMROOT}
export DCOMINosi=${DCOMINosi:-$DCOMROOT}
export DCOMINghrsst=${DCOMINghrsst:-$DCOMROOT}
export DCOMINumd=${DCOMINumd:-$DCOMROOT}
export COMINnam=${COMINnam:-$(compath.py ${envir}/com/obsproc/${obsproc_ver})}
export COMINccpa=${COMINccpa:-$(compath.py ${envir}/com/ccpa/${ccpa_ver})}
export COMOUT=${COMOUT:-$(compath.py -o $NET/$evs_ver/$STEP/$COMPONENT/$RUN)}


echo Actual output starts here


#######################################################################
# Execute the script.
#######################################################################
$HOMEevs/scripts/$STEP/$COMPONENT/exevs_${COMPONENT}_${PREP_TYPE}_${STEP}.sh
export err=$?; err_chk


if [ "$KEEPDATA" != "YES" ] ; then
  cd $DATAROOT
  rm -rf $DATA
fi

date
