#!/bin/ksh

set -x

########################################
# Preliminary data setup step
########################################

##################################################
### SENDECF  - Flag Events on ecFLOW
### SENDCOM  - Copy Files From TMPDIR to $COMOUT
### SENDDBN  - Issue DBNet Client Calls
### SENDMAIL - Send email if file is missing
###################################################
export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-YES}
export SENDECF=${SENDECF:-YES}
export SENDMAIL=${SENDMAIL:-NO}

# ###################################
# SET SHELL PROCESSING VARIABLES
# ###################################
date
export PS4='$SECONDS + '

###########################################################
# obtain unique LSF id (jobid) and make temp directories
###########################################################
export pid=$$

export DATA=${DATA:-${DATAROOT:?}/${jobid:?}}
mkdir -p $DATA
cd $DATA

export vhr=${vhr:-00}
export cycle=${cycle:-t${vhr}z}
setpdy.sh
. ./PDY

export envir=${envir:-prod}

export NET=${NET:-evs}
export STEP=${STEP:-prep}
export COMPONENT=${COMPONENT:-aqm}
export RUN=${RUN:-atmos}
export VERIF_CASE=${VERIF_CASE:-grid2obs}
export MODELNAME=${MODELNAME:-aqm}
export modsys=${modsys:-aqm}
export mod_ver=${mod_ver:-${aqm_ver}}

export HOMEevs=${HOMEevs:-${PACKAGEROOT}/${NET}.${evs_ver}}
export EXECevs=${EXECevs:-${HOMEevs}/exec}
export FIXevs=${FIXevs:-${HOMEevs}/fix}
export PARMevs=${PARMevs:-${HOMEevs}/parm}
export SCRIPTSevs=${SCRIPTSevs:-${HOMEevs}/scripts}
export USHevs=${USHevs:-${HOMEevs}/ush}
export MASKS=${MASKS:-${FIXevs}/masks}

# Define COMIN/COMOUT variables:

echo ${COMPATH}

#
#  The AirNOW obs in DCOM will continue to be updated after first
#  created upto 48 hours.
#  Process the observation input only when it stop updating.
#
export INITDATE=${INITDATE:-${PDYm3}}

export COMIN=${COMIN:-$(compath.py ${envir}/com/${NET}/${evs_ver})}
export COMINaqm=${COMINaqm:-$(compath.py ${envir}/com/${modsys}/${mod_ver})}
export COMOUT=${COMOUT:-$(compath.py -o ${NET}/${evs_ver})}
export COMOUTproc=${COMOUTproc:-${COMOUT}/${STEP}/${COMPONENT}/${RUN}.${INITDATE}/${MODELNAME}}
mkdir -p ${COMOUT} ${COMOUTproc}

if [ "${VERIF_CASE}" == "grid2obs" ]; then
    # alternative choice is dan option different from aqons
    export airnow_hourly_type=${airnow_hourly_type:-aqobs}
    export DCOMINairnow=${DCOMINairnow:-${DCOMROOT}}
    export HOURLY_NCOL=${HOURLY_NCOL:-34}
    export DAILY_NCOL=${DAILY_NCOL:-13}
else
    export DATA_TYPE=${DATA_TYPE:-abi}
    if [ "${DATA_TYPE}" == "abi" ]; then
        export DCOMINabi=${DCOMINabi:-${DCOMROOT}}
        export GOES_EAST=${GOES_EAST:-g19}
        export GOES_WEST=${GOES_WEST:-g18}
        export AOD_SCAN_TYPE=${AOD_SCAN_TYPE:-AODC}
        export ADP_SCAN_TYPE=${ADP_SCAN_TYPE:-ADPC}
        export AOD_QC_NAME=${AOD_QC_NAME:-high}
        export restart_mode=${restart_mode:-YES}
    else
        echo "DEBUG :: DATA_TYPE == ${DATA_TYPE} is not defined, set default value = abi"
	export DATA_TYPE=abi
    fi
fi


#######################################################################
# Execute the script.
#######################################################################

${HOMEevs}/scripts/${STEP}/${COMPONENT}/exevs_${COMPONENT}_${VERIF_CASE}_${STEP}.sh
export err=$?; err_chk

msg="JOB ${job} HAS COMPLETED NORMALLY."
postmsg "${msg}"

if [ "${KEEPDATA}" != "YES" ]; then
    cd ${DATAROOT}
    rm -rf ${DATA}
fi

