#!/bin/bash

set -x

# ###################################
# SET SHELL PROCESSING VARIABLES
# ###################################
export PS4='$SECONDS + ' 
date

export machine="WCOSS2"

###########################################################
# obtain unique LSF id (jobid) and make temp directories
###########################################################
export DATA=${DATA:-${DATAROOT:?}/${jobid:?}}
mkdir -p $DATA
cd $DATA 

################################################################
# SENDCOM=YES--Copy files from TMPDIR to $COMOUT
# SENDECF=YES--Flag events on ecflow
# SENDDBN=YES--Issue DBNet Client Calls
################################################################
export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-YES}       # need to set to NO for testing
export SENDECF=${SENDECF:-YES} 
export SENDDBN_NTC=${SENDDBN_NTC:-NO}
################################################################
# Specify Execution Areas
################################################################
export HOMEevs=${HOMEevs:-${PACKAGEROOT}/${NET}.${evs_ver}}
export EXECevs=${EXECevs:-$HOMEevs/exec}
export PARMevs=${PARMevs:-$HOMEevs/parm}
export USHevs=${USHevs:-$HOMEevs/ush}
export FIXevs=${FIXevs:-$HOMEevs/fix}

if [ $MODELNAME = gefs ] ; then
    export members="30"
fi
if [ $MODELNAME = cfs ] ; then
    export members="4"
fi


# Run setpdy and initialize PDY variables
export vhr=${vhr:-00}
export cycle=${cycle:-t${vhr}z}
setpdy.sh 40
. ./PDY

export VDATE=${VDATE:-$PDYm2}


#################################################
# Set up the INPUT and OUTPUT directories
#################################################
export COMIN=${COMIN:-$(compath.py ${envir}/com/$NET/$evs_ver/prep)/$COMPONENT/$RUN}
export EVSINclimo=${EVSINclimo:-$FIXevs/climos/atmos}
export COMOUT=${COMOUT:-$(compath.py -o $NET/$evs_ver/$STEP/$COMPONENT)}
export COMOUTsmall=$COMOUT/$RUN.$VDATE/$MODELNAME/$VERIF_CASE
export COMOUTfinal=$COMOUT/$MODELNAME.$VDATE

mkdir -p $COMOUT $COMOUTfinal

echo Actual output starts here


#######################################################################
# Execute the script.
#######################################################################
$HOMEevs/scripts/$STEP/$COMPONENT/exevs_${COMPONENT}_${VERIF_CASE}_${STEP}.sh
export err=$?; err_chk


if [ "$KEEPDATA" != "YES" ] ; then
  cd $DATAROOT
  rm -rf $DATA
fi

date
