#!/bin/bash

#################################
# SET SHELL PROCESSING VARIABLES 
#################################
set -x
export PS4='+ $SECONDS + '
date

#########################################################
# obtain unique LSF id (jobid) and make temp directories 
#########################################################
export DATA=${DATA:-${DATAROOT}/${jobid:?}}
mkdir -p $DATA
cd $DATA

##########################################
# Run setpdy and initialize PDY variables 
##########################################
export cycle=${cycle:-t00z}
setpdy.sh 20
. ./PDY
export INITDATE=${INITDATE:-${PDYm1}}
export NEXTDATE=${NEXTDATE:-${PDY}}

####################################
# Set EVS directories               
####################################
export HOMEevs=${HOMEevs:-${PACKAGEROOT}/${NET}.${evs_ver}}
export EXECevs=${EXECevs:-$HOMEevs/exec}
export FIXevs=${FIXevs:-$HOMEevs/fix}
export PARMevs=${PARMevs:-$HOMEevs/parm}
export USHevs=${USHevs:-$HOMEevs/ush}

####################################
# Set data directives
####################################
export SENDECF=${SENDECF:-YES}
export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-YES}
export SENDMAIL=${SENDMAIL:-NO}

####################################
# Define NET/RUN variables          
####################################
export NET=${NET:-evs}
export MODEL=${MODEL:-evs}
export STEP=${STEP:-prep}
export COMPONENT=${COMPONENT:-nfcens}
export MODELNAME=${MODELNAME:-nfcens}
export MODNAM=echo $MODELNAME | tr '[a-z]' '[A-Z]'
export OBTYPE=${OBTYPE:-GDAS}
export RUN=${RUN:-wave}
export VERIF_CASE=${VERIF_CASE:-grid2obs}

####################################
# Define COMIN/COMOUT variables     
####################################
export COMIN=${COMIN:-$(compath.py ${envir}/com/${NET}/${evs_ver})}
export COMINnfcens=${COMINnfcens:-$(compath.py ${envir}/com/${RUN}_${MODELNAME}/${nfcens_ver})} 
export COMINobsproc=${COMINobsproc:-$(compath.py ${envir}/com/obsproc/${obsproc_ver}/gdas)}
export COMOUT=${COMOUT:-$(compath.py -o ${NET}/${evs_ver})/${STEP}/${COMPONENT}/${RUN}}
export ARCmodel=${COMOUT}.${INITDATE}/${MODELNAME}/${VERIF_CASE}

# make the directory where the ARCmodel and gdasnc will be kept
mkdir -p ${COMOUT}.${INITDATE}/${MODELNAME}/${VERIF_CASE}


####################################
# Execute the script                
####################################
$HOMEevs/scripts/${STEP}/${COMPONENT}/exevs_${COMPONENT}_${RUN}_${VERIF_CASE}_${STEP}.sh
export err=$?; err_chk

msg="JOB $job HAS COMPLETED NORMALLY."

if [ "$KEEPDATA" != "YES" ] ; then
  rm -rf $DATA
fi

date
