#!/bin/bash

set -x

########################################
# Preliminary data setup step
########################################

##################################################
### SENDCOM  - Copy Files From TMPDIR to $COMOUT
### SENDDBN  - Issue DBNet Client Calls 
### SENDECF  - Flag Events on ecFLOW
### SENDMAIL - Send email if file is missing
##################################################
export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-YES}
export SENDECF=${SENDECF:-YES}
export SENDMAIL=${SENDMAIL:-NO}

###################################
# SET SHELL PROCESSING VARIABLES
###################################
date
export PS4='$SECONDS + '

###########################################################
## obtain unique LSF id (jobid) and make temp directories
###########################################################
export DATA=${DATA:-${DATAROOT:?}/${jobid:?}}
mkdir -p ${DATA}
cd ${DATA}

####################################
## Determine Job Output Name on System
#####################################
export vhr=${vhr:-00}
export cycle=${cycle:-t${vhr}z}

setpdy.sh 8
. ./PDY

export envir=${envir:-prod}

# Define COMIN/COMOUT variables:
 
echo ${COMPATH}

export NET=${NET:-evs}
export STEP=${STEP:-stats}
export COMPONENT=${COMPONENT:-global_ens}
export RUN=${RUN:-chem}
export VERIF_CASE=${VERIF_CASE:-grid2obs}
export MODELNAME=${MODELNAME:-gefs}
export modsys=${modsys:-gefs}
export mod_ver=${mod_ver:-${gefs_ver}}

export HOMEevs=${HOMEevs:-${PACKAGEROOT}/${NET}.${evs_ver}}
export SCRIPTSevs=${SCRIPTSevs:-${HOMEevs}/scripts}
export EXECevs=${EXECevs:-${HOMEevs}/exec}
export USHevs=${USHevs:-${HOMEevs}/ush/${COMPONENT}}
export PARMevs=${PARMevs:-${HOMEevs}/parm}
export FIXevs=${FIXevs:-${HOMEevs}/fix}
export MASK_DIR=${MASK_DIR:-$FIXevs/masks}

export VDATE=${VDATE:-${PDYm3}}

export COMIN=${COMIN:-$(compath.py ${envir}/com/${NET}/${evs_ver})}
export DCOMIN=${DCOMIN:-${DCOMROOT}}
export EVSINgefs=${EVSINgefs:-${COMIN}/prep/${COMPONENT}}
export COMOUT=${COMOUT:-$(compath.py -o ${NET}/${evs_ver})}
export COMOUTsmall=${COMOUTsmall:-${COMOUT}/${STEP}/${COMPONENT}/${RUN}.${VDATE}/${MODELNAME}/${VERIF_CASE}}
export COMOUTfinal=${COMOUTfinal:-${COMOUT}/${STEP}/${COMPONENT}/${MODELNAME}.${VDATE}}

mkdir -p ${COMOUT} ${COMOUTsmall} ${COMOUTfinal}

export DATA_TYPE=${DATA_TYPE:-aeronet}
 
# alternative choice is an option different from aqobs
export airnow_hourly_type=${airnow_hourly_type:-aqobs}

#######################################################################
# Execute the script.
#######################################################################

${HOMEevs}/scripts/${STEP}/${COMPONENT}/exevs_${COMPONENT}_${RUN}_${VERIF_CASE}_${STEP}.sh

msg="JOB ${job} HAS COMPLETED NORMALLY."
postmsg "${msg}"

if [ "${KEEPDATA}" != "YES" ]; then
    cd ${DATAROOT}
    rm -rf ${DATA}
fi

