#!/bin/bash
###############################################################################
# Job Name: JEVS_RTOFS_PREP
# Purpose: To pre-process RTOFS forecast data into the same spatial and
#          temporal scales as validation data.
# Author: L. Gwen Chen (lichuan.chen@noaa.gov)
###############################################################################

set -x

########################################
# Preliminary data setup step
########################################

export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-YES}
export SENDECF=${SENDECF:-YES}
export SENDMAIL=${SENDMAIL:-NO}

# ###################################
# SET SHELL PROCESSING VARIABLES
# ###################################
export PS4='$SECONDS + '
date

###########################################################
# obtain unique LSF id (jobid) and make temp directories
###########################################################
export pid=$$
export DATA=${DATA:-${DATAROOT:?}/${jobid:?}}
mkdir -p $DATA
cd $DATA

###################################
# Set EVS directories
####################################
export HOMEevs=${HOMEevs:-${PACKAGEROOT}/${NET}.${evs_ver}}
export EXECevs=${EXECevs:-$HOMEevs/exec}
export FIXevs=${FIXevs:-$HOMEevs/fix}
export PARMevs=${PARMevs:-$HOMEevs/parm}
export SCRIPTSevs=${SCRIPTSevs:-$HOMEevs/scripts}
export CONFIGevs=${CONFIGevs:-$HOMEevs/parm/metplus_config}
export USHevs=${USHevs:-$HOMEevs/ush}
export MASKS=${MASKS:-$FIXevs/masks}

# Run setpdy and initialize PDY variables
export vhr=${vhr:-"00"}
export cycle=${cycle:-t${vhr}z}
setpdy.sh
. ./PDY
export VDATE=${VDATE:-$PDYm2}

####################################
# Define NET/RUN variables
####################################
export NET=${NET:-evs}
export STEP=${STEP:-prep}
export COMPONENT=${COMPONENT:-rtofs}

# define COMIN/COMOUT variables
export COMIN=${COMIN:-$(compath.py $envir/com/$NET/${evs_ver})}
export COMINrtofs=${COMINrtofs:-$(compath.py $envir/com/rtofs/${rtofs_ver})}
export EVSINprep=${EVSINprep:-$COMIN/$STEP/$COMPONENT}
export COMOUT=${COMOUT:-$(compath.py -o $NET/${evs_ver})}
export COMOUTprep=${COMOUTprep:-$COMOUT/$STEP/$COMPONENT}

mkdir -p $COMOUT $COMOUTprep

#######################################################################
# Execute the script
#######################################################################
env
$HOMEevs/scripts/$STEP/$COMPONENT/exevs_${COMPONENT}_${STEP}.sh
export err=$?; err_chk

if [ "$KEEPDATA" != "YES" ] ; then
  cd $DATAROOT
  rm -rf $DATA
fi

date
