#!/bin/bash

#################################
# SET SHELL PROCESSING VARIABLES 
#################################
set -x
export PS4='+ $SECONDS + '
date

#########################################################
# obtain unique LSF id (jobid) and make temp directories 
#########################################################
export DATA=${DATA:-${DATAROOT:?}/${jobid:?}}
mkdir -p $DATA
cd $DATA

##########################################
# Run setpdy and initialize PDY variables 
##########################################
export cycle=${cycle:-t00z}
setpdy.sh 17
. ./PDY
export VDATE=${VDATE:-${PDYm1}}
export NEXTDATE=${NEXTDATE:-${PDY}}

####################################
# Set data directives
####################################
export SENDECF=${SENDECF:-YES}
export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-YES}

####################################
# Define NET/RUN variables          
####################################
export NET=${NET:-evs}
export MODEL=${MODEL:-evs}
export STEP=${STEP:-stats}
export COMPONENT=${COMPONENT:-nfcens}
export MODELNAME=${MODELNAME:-nfcens}
export MODEL1NAME=${MODEL1NAME:-gefs}
export MODEL2NAME=${MODEL2NAME:-fnmoc}
export MODNAM=`echo $MODELNAME | tr '[a-z]' '[A-Z]'`
export MOD1NAM=`echo $MODEL1NAME | tr '[a-z]' '[A-Z]'`
export MOD2NAM=`echo $MODEL2NAME | tr '[a-z]' '[A-Z]'`
export OBTYPE=${OBTYPE:-GDAS}
export RUN=${RUN:-wave}
export VERIF_CASE=${VERIF_CASE:-grid2obs}

####################################
# Set EVS directories               
####################################
export HOMEevs=${HOMEevs:-${PACKAGEROOT}/${NET}.${evs_ver}}
export EXECevs=${EXECevs:-$HOMEevs/exec}
export FIXevs=${FIXevs:-$HOMEevs/fix}
export PARMevs=${PARMevs:-$HOMEevs/parm}
export USHevs=${USHevs:-$HOMEevs/ush}

####################################
# Define COMIN/COMOUT variables     
####################################
export COMIN=${COMIN:-$(compath.py ${envir}/com/${NET}/${evs_ver})}
export COMINnfcens=${COMINnfcens:-$(compath.py ${envir}/com/${RUN}_${MODELNAME}/${nfcens_ver})}
export EVSINgdasnc=${COMIN}/prep/${COMPONENT}
export ARCmodel=${COMIN}/prep/${COMPONENT}

export COMOUT=${COMOUT:-$(compath.py -o ${NET}/${evs_ver})/${STEP}/${COMPONENT}}

export COMOUTsmall=${COMOUT}/${RUN}.${VDATE}/${MODELNAME}/${VERIF_CASE}
export COMOUTfinal=${COMOUT}/${MODELNAME}.${VDATE}

mkdir -p ${COMOUT} ${COMOUTsmall} ${COMOUTfinal} 


####################################
# Execute the script                
####################################
$HOMEevs/scripts/${STEP}/${COMPONENT}/exevs_${COMPONENT}_${RUN}_${VERIF_CASE}_${STEP}.sh
export err=$?; err_chk

msg="JOB $job HAS COMPLETED NORMALLY."

if [ "$KEEPDATA" != "YES" ] ; then
  rm -rf $DATA
fi

date
