#!/bin/bash
###############################################################################
# Job Name: JEVS_RTOFS_STATS
# Purpose: To create stat files for RTOFS forecast verification using
#          MET/METplus.
# Author: L. Gwen Chen (lichuan.chen@noaa.gov)
###############################################################################
 
set -x

# Preliminary data setup step
########################################

export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-YES}
export SENDECF=${SENDECF:-YES}
export SENDMAIL=${SENDMAIL:-NO}

# ###################################
# SET SHELL PROCESSING VARIABLES
# ###################################
export PS4='$SECONDS + '
date

###########################################################
# obtain unique LSF id (jobid) and make temp directories
###########################################################
export pid=$$
export DATA=${DATA:-${DATAROOT:?}/${jobid:?}}
mkdir -p $DATA
cd $DATA

###################################
# Set EVS directories
####################################
export HOMEevs=${HOMEevs:-${PACKAGEROOT}/evs.${evs_ver}}
export EXECevs=${EXECevs:-$HOMEevs/exec}
export FIXevs=${FIXevs:-$HOMEevs/fix}
export PARMevs=${PARMevs:-$HOMEevs/parm}
export SCRIPTSevs=${SCRIPTSevs:-$HOMEevs/scripts}
export CONFIGevs=${CONFIGevs:-$HOMEevs/parm/metplus_config}
export USHevs=${USHevs:-$HOMEevs/ush}
export MASKS=${MASKS:-$FIXevs/masks}

# Run setpdy and initialize PDY variables
export cyc=${cyc:-"00"}
export cycle=${cycle:-t${cyc}z}
setpdy.sh
. ./PDY
export VDATE=${VDATE:-$PDYm2}

####################################
# Define NET/RUN variables
####################################
export NET=${NET:-evs}
export STEP=${STEP:-prep}
export COMPONENT=${COMPONENT:-rtofs}

# define COMIN/COMOUT variables
export COMIN=${COMIN:-$(compath.py $envir/com/$NET/${evs_ver})}
export COMOUT=${COMOUT:-$(compath.py -o $NET/${evs_ver})}
export COMOUTsmall=${COMOUTsmall:-$COMOUT/$STEP/$COMPONENT/$RUN.$VDATE}
export COMOUTfinal=${COMOUTfinal:-$COMOUT/$STEP/$COMPONENT/$COMPONENT.$VDATE}

mkdir -p $COMOUT $COMOUTsmall $COMOUTfinal

$HOMEevs/scripts/$STEP/$COMPONENT/exevs_${COMPONENT}_${RUN}_${STEP}.sh

export err=$?; err_chk

msg="JOB $job HAS COMPLETED NORMALLY."
postmsg "$msg"

if [ "$KEEPDATA" != "YES" ] ; then
  cd $DATAROOT
  rm -rf $DATA
fi

date

################################# END OF JOB ##################################
