#!/bin/ksh

########################################
# Preliminary data setup step
########################################

# ###################################
# SET SHELL PROCESSING VARIABLES
# ###################################
date
export PS4='$SECONDS + '
set -xa

###########################################################
# obtain unique LSF id (jobid) and make temp directories
###########################################################
export pid=$$

export DATA=${DATA:-${DATAROOT:?}/${jobid:?}}
mkdir -p $DATA
cd $DATA

export cycle=${cycle:-t${cyc}z}
setpdy.sh
. ./PDY

####################################
# Determine Job Output Name on System
####################################
export pgmout="OUTPUT.${pid}"

##################################################
# SAVEGES  - Copy Files From TMPDIR to $GESdir
# SENDECF  - Flag Events on ecFLOW
# SENDCOM  - Copy Files From TMPDIR to $COMOUT
# SENDDBN  - Issue DBNet Client Calls
##################################################
export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-YES}
export SENDECF=${SENDECF:-YES}

export DCOMROOT=${DCOMROOT:-/lfs/h1/ops/$envir/dcom}
export EXECevs=${EXECevs:-$HOMEevs/exec}
export FIXvevs=${FIXevs:-$HOMEevs/fix}
export PARMevs=${PARMevs:-$HOMEevs/parm}
export USHevs=${USHevs:-$HOMEevs/ush}

# Define COMIN/COMOUT variables:

echo $COMPATH

export VDATE=${VDATE:-${PDYm3}}

export COMIN=${COMIN:-$(compath.py evs/${evs_ver}/)}
export COMINobs=${COMINobs:-${DCOMROOT}}
export COMINaqm=${COMINaqm:-$(compath.py ${modsys}/${mod_ver})}
export COMOUT=${COMOUT:-$(compath.py ${NET}/${evs_ver}/${STEP}/${COMPONENT}/${RUN})}

#######################################################################
# Execute the script.
#######################################################################

$HOMEevs/scripts/${COMPONENT}/${STEP}/exevs_${MODELNAME}_${STEP}.sh

cat $pgmout

msg="JOB $job HAS COMPLETED NORMALLY."
postmsg "$jlogfile" "$msg"

#if [ "$KEEPDATA" != "YES" ] ; then
#  cd $DATAROOT
#  rm -rf $DATA
#fi

