#!/bin/bash

set -xa

export PS4='$SECONDS + '
date

############################################
# Working Directory                                                                                                                                      
############################################
export DATA=${DATA:-${DATAROOT}/${jobid:?}}
mkdir -p $DATA
mkdir -p $DATA/semifinal
cd $DATA

############################################
# Determine Job Output Name on System
############################################
export pid=$$
export pgmout=OUTPUT.${pid}

############################################
# Initialize PDY variables
############################################
export cyc=${cyc:-00}
export cycle=t${cyc}z

#It needs $DATA and $cycle to be set
setpdy.sh
. ./PDY

# Don't specify $VDATE to be flexible to both data preparation and MET stat input
export VDATE=${VDATE:-$PDYm1}

############################################
# Set up the NET and RUN                                                                                                                         
############################################
export NET=${NET:-evs}
export STEP=${STEP:-stats} # prep stats plot
export COMPONENT=${COMPONENT:-wafs}
export RUN=${RUN:-atmos}
export VERIF_CASE=${VERIF_CASE:-grid2grid}

# WAFS is the general MODELNAME for data structure
# while the center (us/uk/blend or gfs) will be the actual MODEL
# parm/metplus_config/wafs/atmos/stats/GridStat_fcstWAFS_obsGCIP.conf
# parm/metplus_config/wafs/atmos/stats/StatAnalysis_fcstWAFS_obsGCIP_GatherbyDay.conf
export MODELNAME=${MODELNAME:-wafs}

############################################
# Set up the INPUT and OUTPUT directories
############################################

# COMIN folder of analysis and forecast grib2 data
# gfs_ver defined in versions/run.ver
export COMIN=${COMIN:-$(compath.py ${envir}/com/${NET}/${evs_ver})}
export COMINuk=${COMINuk:-$DCOMROOT} # $VDATE/wgrbbul/ukmet_wafs}
export COMINgfs=${COMINgfs:-$(compath.py gfs/${gfs_ver})}
export COMINobs=$COMINgfs

# COMOUT folder
# evs_ver defined in versions/run.ver
export COMOUT=${COMOUT:-$(compath.py ${envir}/com/${NET}/${evs_ver})}
export COMOUTsmall=$COMOUT/$STEP/$COMPONENT/$RUN.$VDATE/$MODELNAME/$VERIF_CASE
export COMOUTfinal=$COMOUT/$STEP/$COMPONENT/$MODELNAME.$VDATE

mkdir -p $COMOUTsmall $COMOUTfinal
rm $COMOUTsmall/* $COMOUTfinal/*

############################################
# Specify HOME Directory
############################################

export HOMEevs=${HOMEevs:-$PACKAGEROOT/evs.$evs_ver}
export EXECevs=${EXECevs:-$HOMEevs/exec}
export FIXevs=${FIXevs:-$HOMEevs/fix}
export SCRIPTSevs=${SCRIPTSevs:-$HOMEevs/scripts/$COMPONENT} # step
export JOBSevs=${JOBSevs:-$HOMEevs/jobs/$COMPONENT} # step
export PARMevs=${PARMevs:-$HOMEevs/parm/metplus_config/$COMPONENT/$RUN} # step
export USHevs=${USHevs:-$HOMEevs/ush/$COMPONENT} # all pool

export MACHINE_CONF=$HOMEevs/parm/metplus_config/machine.conf

export MASKS=${MASKS:-$FIXevs/masks}

############################################
# Execute the script using MPMD
############################################
rm wafs_stat.cmdfile

export MPIRUN=${MPIRUN:-"mpiexec"}
ic=0
observations="GCIP GFS"
for observation in $observations ; do
    if [ $observation = "GCIP" ] ; then
	# For ICING, there are 2 different resoltions (before Nov 2023) and 3 centers
	resolutions="0P25"
	centers="blend uk us"
    elif [ $observation = "GFS" ] ; then
	# For wind/temperature, only 1 resolution so far
	resolutions="1P25"
	centers="gfs"
    fi

    for resolution in $resolutions ; do
	for center in $centers; do
	    if [ `echo $MPIRUN | cut -d " " -f1` = 'srun' ] ; then
		echo $ic $SCRIPTSevs/stats/exevs_wafs_atmos_stats.sh $observation $resolution $center  >> wafs_stat.cmdfile
	    else
		echo $SCRIPTSevs/stats/exevs_wafs_atmos_stats.sh $observation $resolution $center  >> wafs_stat.cmdfile
		export MP_PGMMODEL=mpmd
	    fi
	    ic=`expr $ic + 1`
	done
    done
done

export MPIRUN="$MPIRUN -np $ic -cpu-bind verbose,core cfp"
$MPIRUN wafs_stat.cmdfile

export err=$?; err_chk

# Combine icing files from different centers ( blend, uk, us) to $COMOUTfinal
#===============================
resolutions="0P25"
centers="blend uk us"
cd $DATA/semifinal
for resolution in $resolutions ; do
    for center in $centers ; do
	file=`ls ${center}_$resolution.*`
	finalfile=${file#*\.}
	cat $file >> $finalfile
    done
    if [[ -s $finalfile ]] ; then
	awk '!seen[$0]++' $finalfile > $COMOUTfinal/$finalfile
    fi
done

msg="JOB $job HAS COMPLETED NORMALLY."
echo $msg

if [ "$KEEPDATA" != "YES" ] ; then
  rm -rf $DATA
fi

date
exit
