#!/bin/bash

#################################
# SET SHELL PROCESSING VARIABLES 
#################################
set -x
export PS4='+ $SECONDS + '
date

#########################################################
# obtain unique LSF id (jobid) and make temp directories 
#########################################################
export pid=$$
export DATA=${DATA:-${DATAROOT:?}/${jobid:?}}
mkdir -p $DATA
cd $DATA

##########################################
# Run setpdy and initialize PDY variables 
##########################################
export cycle=${cycle:-t00z}
setpdy.sh 17
. ./PDY
export VDATE=${VDATE:-${PDYm1}}
export NEXTDATE=${NEXTDATE:-${PDY}}

######################################
# Determine Job Output Name on System 
######################################
export pgmout="OUTPUT.${pid}"

####################################
# Set EVS directories               
####################################
export HOMEevs=${HOMEevs:-${PACKAGEROOT}/evs.${model_ver}}
export EXECevs=${EXECevs:-$HOMEevs/exec}
export FIXevs=${FIXevs:-$HOMEevs/fix}
export PARMevs=${PARMevs:-$HOMEevs/parm}
export USHevs=${USHevs:-$HOMEevs/ush}

######################################
# Correct MET/METplus roots (Aug 2022)
######################################
# for use with MET/10.1.1 and METplus/4.1.1
export MET_ROOT=/apps/ops/para/libs/intel/${intel_ver}/met/${met_ver}
export MET_BASE=${MET_ROOT}/share/met
export METPLUS_PATH=/apps/ops/para/libs/intel/${intel_ver}/metplus/${metplus_ver}
export PATH=${METPLUS_PATH}/ush:${MET_ROOT}/bin:${PATH}

####################################
# Define NET/RUN variables          
####################################
export NET=${NET:-evs}
export MODEL=${MODEL:-evs}
export STEP=${STEP:-stats}
export COMPONENT=${COMPONENT:-nfcens}
export MODELNAME=${MODELNAME:-nfcens}
export MODNAM=`echo $MODELNAME | tr '[a-z]' '[A-Z]'`
export OBTYPE=${OBTYPE:-GDAS}
export RUN=${RUN:-wave}
export VERIF_CASE=${VERIF_CASE:-grid2obs}

####################################
# Define COMIN/COMOUT variables     
####################################
export COMIN=${COMIN:-$(compath.py ${envir}/com/${NET}/${evs_ver})}
export COMINmodel=${COMINmodel:-$(compath.py ${envir}/com/${RUN}_${MODELNAME}/${model_ver})}
export COMINgdasnc=${COMIN}/prep/${COMPONENT}
export ARCmodel=${COMIN}/prep/${COMPONENT}

export COMOUT=${COMOUT:-${COMIN}/${STEP}/${COMPONENT}}
export COMOUTsmall=${COMOUT}/${RUN}.${VDATE}/${MODELNAME}/${VERIF_CASE}
export COMOUTfinal=${COMOUT}/${MODELNAME}.${VDATE}

mkdir -p ${COMOUT} ${COMOUTsmall} ${COMOUTfinal} 

export jlogfile=${DATA}/${MODELNAME}_${RUN}_PointStat.log

####################################
# Execute the script                
####################################
env

$HOMEevs/scripts/nfcens/stats/exevs_nfcens_wave_grid2obs_stats.sh 1>>$pgmout 2>errfile.${pid}

export err=$?; err_chk

cat $pgmout

msg="JOB $job HAS COMPLETED NORMALLY."
postmsg "$jlogfile" "$msg"

if [ "$KEEPDATA" != "YES" ] ; then
  rm -rf $DATA
fi

date
