#!/bin/bash
###############################################################################
# Job Name: JEVS_RTOFS_STATS
# Purpose: To create stat files for RTOFS forecast verification using
#          MET/METplus.
# Author: L. Gwen Chen (lichuan.chen@noaa.gov)
###############################################################################

set -x

# set up paths
export FIXevs=${FIXevs:-$HOMEevs/fix}
export CONFIGevs=${CONFIGevs:-$HOMEevs/parm/metplus_config/$COMPONENT}

# define COMIN/COMOUT variables
export COMIN=${COMIN:-$(compath.py $envir/com/$NET/${evs_ver})}
export COMINobs=${COMINobs:-$(compath.py $envir/dcom)}
export COMINfcst=${COMINfcst:-$(compath.py $NET/${evs_ver}/prep/$COMPONENT)}
export COMINclimo=${COMINclimo:-$HOMEevs/fix/climos/$COMPONENT}
export COMOUT=${COMOUT:-$(compath.py $NET/${evs_ver})}
export COMOUTsmall=$COMOUT/$STEP/$COMPONENT/$RUN.$VDATE
export COMOUTfinal=${COMOUTfinal:-$COMOUT/$STEP/$COMPONENT/$COMPONENT.$VDATE}
export DATA=${DATA:-$DATAROOT/$NET/${evs_ver}}

mkdir -p $COMOUT $COMOUTsmall $COMOUTfinal

if [ $RUN = 'argo' ] ; then
  for vari in ${VARS}; do
    export VAR=$vari
    export COMOUTsmall=$COMOUT/$STEP/$COMPONENT/$RUN.$VDATE/$VAR
    $HOMEevs/scripts/$COMPONENT/$STEP/exevs_${COMPONENT}_${RUN}_${STEP}.sh
  done
else
  $HOMEevs/scripts/$COMPONENT/$STEP/exevs_${COMPONENT}_${RUN}_${STEP}.sh
fi

################################# END OF JOB ##################################
