#!/bin/bash
###############################################################################
# Job Name: JEVS_RTOFS_VERIF_STATS
# Purpose: To create stat files for RTOFS forecast verification using
#          MET/METplus.
# Author: L. Gwen Chen (lichuan.chen@noaa.gov)
###############################################################################

set -x

# set up VDATE
#export VDATE=20221018
#export VDATE=$(date --date="yesterday" +%Y%m%d)
export VDATE=$(date --date="2 days ago" +%Y%m%d)

# set up paths
#export COMIN=${COMIN:-$(compath.py $envir/com/$NET/${evs_ver})}
#export COMINobs=$DCOMROOT
export COMINobs=/lfs/h2/emc/vpppg/noscrub/Lichuan.Chen
#export COMINfcst=$COMIN/prep/$COMPONENT
export COMINfcst=/lfs/h2/emc/ptmp/$USER/$NET/${evs_ver}/prep/$COMPONENT
#export COMINclimo=$EVS/fix/climos/$COMPONENT
export COMINclimo=/lfs/h2/emc/vpppg/noscrub/emc.vpppg/verification/EVS_fix/climos/$COMPONENT
#export COMOUT=$COMIN
export COMOUT=/lfs/h2/emc/ptmp/$USER/$NET/${evs_ver}
export COMOUTfinal=$COMOUT/$STEP/$COMPONENT/$COMPONENT.$VDATE
#export FIXevs=$EVS/fix
export FIXevs=/lfs/h2/emc/vpppg/noscrub/emc.vpppg/verification/EVS_fix
export CONFIGevs=$EVS/parm/metplus_config/$COMPONENT
export ARCHevs=/lfs/h2/emc/vpppg/noscrub/$USER/stat_archive/RTOFS

# run scripts for each RUN;
# RUN is the validation source: gmpe, smos, smap etc.
for rcase in ghrsst gmpe smos smap aviso osisaf; do
  export RUN=$rcase
  export COMOUTsmall=$COMOUT/$STEP/$COMPONENT/$RUN.$VDATE

  if [ $rcase = 'ghrsst' ] ; then
     export RUNupper=GHRSST
     export VAR=sst
  fi

  if [ $rcase = 'gmpe' ] ; then
     export RUNupper=GMPE
     export VAR=sst
  fi

  if [ $rcase = 'smos' ] ; then
     export RUNupper=SMOS
     export VAR=sss
  fi

  if [ $rcase = 'smap' ] ; then
     export RUNupper=SMAP
     export VAR=sss
  fi

  if [ $rcase = 'aviso' ] ; then
     export RUNupper=AVISO
     export VAR=ssh
  fi

  if [ $rcase = 'osisaf' ] ; then
     export RUNupper=OSISAF
     export VAR=sic
  fi

  $EVS/scripts/$COMPONENT/$STEP/exevs_${COMPONENT}_${RUN}_stats.sh
done

################################# END OF JOB ##################################
