#!/bin/ksh

########################################
# Preliminary data setup step
########################################
set -xa


export cycle=t${cyc}z 

export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-YES}
export SENDECF=${SENDECF:-YES}

export DATA_IN=${DATA_IN:-$DATAROOT}
export pid=$$
jobid=evs_${MODELNAME}_${VERIF_CASE}_${STEP}.$$
export DATA=${DATA:-$DATA_IN/${jobid}}
#export DATA=${DATA:-$DATA_IN/evs_href_spcoutlook_stats}
mkdir -p $DATA
cd $DATA

setpdy.sh
. $DATA/PDY

if [ $MODELNAME = href ] ; then
  export VDATE=${VDATE:-$PDYm2}
fi


export COMIN=${COMIN:-$(compath.py  $NET/$evs_ver)}
export COMINhref=${COMINhref:-$(compath.py  href/$href_ver)}
export COMINprepbufr=${COMINprepbufr:-$(compath.py  obsproc/${obsproc_ver})}
export COMINccpa=${COMINccpa:-$(compath.py  ccpa/${ccpa_ver})}
export COMINsnow=$DCOMROOT
export COMINmrms=$DCOMROOT/ldmdata/obs/upperair/mrms/alaska/MultiSensorQPE

export COMOUT=${COMOUT:-$(compath.py -o ${NET}/${evs_ver})}/$STEP/$COMPONENT
mkdir -p $COMOUT

export COMOUTfinal=${COMOUT}/${MODELNAME}.${VDATE}
export COMOUTsmall=${COMOUT}/${RUN}.${VDATE}/${MODELNAME}/${VERIF_CASE}
mkdir -p $COMOUTfinal $COMOUTsmall


export HOMEevs=${HOMEevs:-${PACKAGEROOT}/evs.${evs_ver}}
export EXECevs=${EXECevs:-$HOMEevs/exec}
export FIXvevs=${FIXevs:-$HOMEevs/fix}
export PARMevs=${PARMevs:-$HOMEevs/parm}
export USHevs=${USHevs:-$HOMEevs/ush}
export FIXevs=${FIXevs:-$HOMEevs/fix}
export MASKS=${MASKS:-$FIXevs/masks} 

export pid=$$
jobid=evs_${MODELNAME}_${VERIF_CASE}_${STEP}.$$
export DATA=${DATA:-$DATA_IN/${jobid}}
mkdir -p $DATA
cd $DATA


export pgmout="OUTPUT.${pid}"

$HOMEevs/scripts/${COMPONENT}/${STEP}/exevs_${MODELNAME}_${VERIF_CASE}_${STEP}.sh

msg="JOB $job HAS COMPLETED NORMALLY."
postmsg "$msg"

if [ "$KEEPDATA" != "YES" ] ; then
  cd $DATAROOT
  rm -rf $DATA
fi

