#!/bin/bash

########################################
# Preliminary data setup step
########################################
set -xa

# LCD COMMENT: Implementation standards say these should be set in job card
export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-YES}
export SENDECF=${SENDECF:-YES}


####################################
# SET SHELL PROCESSING VARIABLES
####################################
export PS4='$SECONDS + '
date


###########################################################
# obtain unique LSF id (jobid) and make temp directories
###########################################################
export pid=$$

# LCD COMMENT: DATAROOT preferred over DATA_IN
if [ $MODELNAME = href ] ; then
   export DATA=${DATA:-$DATA_IN/${jobid}}
else
   export DATA=${DATA:-${DATAROOT:?}}/${jobid:?}
   rm -rf $DATA
fi

export DATA=${DATA:-${DATAROOT:?}/${jobid:?}}
rm -rf $DATA
mkdir -p $DATA
cd $DATA


####################################
# Determine Job Output Name on System
####################################
export pgmout="OUTPUT.${pid}"


####################################
# Set EVS directories
####################################
export HOMEevs=${HOMEevs:-${PACKAGEROOT}/evs.${evs_ver}}
export EXECevs=${EXECevs:-$HOMEevs/exec}
export FIXevs=${FIXevs:-$HOMEevs/fix}
export PARMevs=${PARMevs:-$HOMEevs/parm}
export SCRIPTSevs=${SCRIPTSevs:-$HOMEevs/scripts}
export USHevs=${USHevs:-$HOMEevs/ush}
export MASKS=${MASKS:-$FIXevs/masks}
export MET_PLUS_CONF="${PARMevs}/metplus_config/${COMPONENT}/${VERIF_CASE}/${STEP}"


####################################
# Run setpdy and initialize PDY variables
####################################
export cycle=${cycle:-t${cyc}z}
setpdy.sh 8
. ./PDY

if [ $VERIF_CASE = severe ] ; then

   # Set verification date
   export VDATE=${VDATE:-$PDYm7}
  
   # Set correct date for SPC report data 
   export REP_DATE=${REP_DATE:-$(date -d "$VDATE -1 day" +"%Y%m%d")}

   # Set initialization date (only for forecast prep step)
   export IDATE=${IDATE:-$PDYm1}

else

   if [ $MODELNAME = href ]; then
      if [ $VERIF_CASE = precip ] ; then
         export VDATE=${VDATE:-$PDYm2}
      else
         export VDATE=${VDATE:-$PDYm1}
      fi

   else
    # LCD COMMENT: can use setpdy.sh instead to match convention of rest of EVS  
      export VDATE=${VDATE:-$PDYm1}
    # export VDATE=$(date -d "today -1 day" +"%Y%m%d")

   fi

fi


####################################
# Define NET/RUN variables
####################################
export NET=${NET:-evs}
export STEP=${STEP:-stats}
export COMPONENT=${COMPONENT:-cam}
export RUN=${RUN:-atmos}


####################################
# Define COMIN/COMOUT variables
####################################
export COMIN=${COMIN:-$(compath.py $NET/$evs_ver)}
export COMINhiresw=${COMINhiresw:-$(compath.py ${envir}/com/hiresw/${hiresw_ver})}
export COMINhref=${COMINhref:-$(compath.py  href/$href_ver)}
export COMINhrrr=${COMINhrrr:-$(compath.py ${envir}/com/hrrr/${hrrr_ver})}
export COMINnam=${COMINnam:-$(compath.py ${envir}/com/nam/${nam_ver})}
export COMINsnow=$DCOMROOT

#LCD COMMENT: Do we need both of these???
export COMINprepbufr=${COMINprepbufr:-$(compath.py  obsproc/${obsproc_ver})}
export COMINobsproc=${COMINobsproc:-$(compath.py ${envir}/com/obsproc/${obsproc_ver})}

# LCD COMMENT: COMOUT should not be different between HREF and other CAMs
if [ $MODELNAME = href ] ; then
   export COMINccpa=${COMINccpa:-$(compath.py  ccpa/${ccpa_ver})}
   export COMINmrms=$DCOMROOT/ldmdata/obs/upperair/mrms/alaska/MultiSensorQPE
   export COMOUT=${COMOUT:-$(compath.py -o ${NET}/${evs_ver})}/$STEP/$COMPONENT

else
   export COMINccpa=${COMINccpa:-$(compath.py -o $NET/$evs_ver/prep/$COMPONENT/$RUN)}
   export COMINmrms=${COMINmrms:-$(compath.py -o $NET/$evs_ver/prep/$COMPONENT/$RUN)}
   export COMINspcotlk=${COMINspcotlk:-$(compath.py -o $NET/$evs_ver/prep/$COMPONENT/$RUN)}

   export COMOUT=${COMOUT:-$(compath.py -o $NET/$evs_ver/$STEP/$COMPONENT/$RUN)}

fi

export COMOUTfinal=${COMOUT}/${MODELNAME}.${VDATE}
export COMOUTsmall=${COMOUT}/${RUN}.${VDATE}/${MODELNAME}/${VERIF_CASE}
mkdir -p $COMOUTfinal $COMOUTsmall


####################################
# Execute the script 
####################################
$HOMEevs/scripts/$COMPONENT/$STEP/exevs_${MODELNAME}_${VERIF_CASE}_${STEP}.sh
export err=$?; err_chk

if [ -e "$pgmout" ]; then
   cat $pgmout
fi

msg="JOB $job HAS COMPLETED NORMALLY."
postmsg "$msg"

if [ "$KEEPDATA" != "YES" ]; then
   cd $DATAROOT
   rm -rf $DATA
fi

date
