#!/bin/ksh

########################################
# Preliminary data setup step
########################################
set -xa

export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-YES}
export SENDECF=${SENDECF:-YES}

# ###################################
# SET SHELL PROCESSING VARIABLES
# ###################################
export PS4='$SECONDS + '
date

###########################################################
# obtain unique LSF id (jobid) and make temp directories
###########################################################
export pid=$$

export DATA=${DATA:-${DATAROOT:?}/${jobid:?}}
rm -rf $DATA
mkdir -p $DATA
cd $DATA

####################################
# Determine Job Output Name on System
####################################
export pgmout="OUTPUT.${pid}"

export cycle=t${cyc}z

##################################################
# SAVEGES  - Copy Files From TMPDIR to $GESdir
# SENDECF  - Flag Events on ecFLOW
# SENDCOM  - Copy Files From TMPDIR to $COMOUT
# SENDDBN  - Issue DBNet Client Calls
##################################################

export DCOMROOT=${DCOMROOT:-/lfs/h1/ops/$envir/dcom}
export HOMEevs=${HOMEevs:-${PACKAGEROOT}/evs.${evs_ver}}
export EXECevs=${EXECevs:-$HOMEevs/exec}
export FIXevs=${FIXevs:-$HOMEevs/fix}
export PARMevs=${PARMevs:-$HOMEevs/parm}
export SCRIPTSevs=${SCRIPTSevs:-$HOMEevs/scripts}
export USHevs=${USHevs:-$HOMEevs/ush}

# Run setpdy and initialize PDY variables
 setpdy.sh 31
 . ./PDY

export VDATE=${VDATE:-$PDYm1}

####################################
### Define NET/RUN variables
######################################
export NET=${NET:-evs}
export STEP=${STEP:-plots}
export COMPONENT=${COMPONENT:-analyses}
export RUN=${RUN:-atmos}

# Define COMIN/COMOUT variables:

echo $COMPATH

export COMIN=${COMIN:-$(compath.py ${envir}/com/evs/${evs_ver}/)}
export COMINanl=${COMINanl:-$(compath.py ${envir}/com/evs/${evs_ver}/stats/${COMPONENT})}
export COMOUT=${COMOUT:-${COMIN}/${STEP}/${COMPONENT}}
export COMOUTplots=${COMOUTplots:-${COMOUT}/${RUN}.${VDATE}}
mkdir -m 775 -p $COMOUTplots

#######################################################################
# Execute the script.
#######################################################################

$HOMEevs/scripts/${COMPONENT}/${STEP}/exevs_${COMPONENT}_${VERIF_CASE}_${STEP}.sh

if [ -e "$pgmout" ]; then
  cat $pgmout
fi

msg="JOB $job HAS COMPLETED NORMALLY."
postmsg "$msg"

if [ "$KEEPDATA" != "YES" ] ; then
  cd $DATAROOT
  rm -rf $DATA
fi

date
