import os
from datetime import datetime
graphics = {
    'mesoscale':{
        'headline':{
            'metar':{
                'nam, rap, gfs': {
                    'lead_average':{
                        'DATE_TYPE':'INIT',
                        'VALID_BEG':'',
                        'VALID_END':'',
                        'INIT_BEG':'',
                        'INIT_END':'',
                        'VX_MASK_LIST':'CONUS_East,CONUS_West,CONUS_Central,CONUS_South,Alaska,Hawaii',
                        'EVAL_PERIODS':['LAST90DAYS'],
                        'FCST_VALID_HOURS':[''],
                        'FCST_INIT_HOURS':['0'],
                        'VARIABLES':{
                            'sl1l2':{
                                'TMP2m':{
                                    'STATSs':['bcrmse,me'],
                                    'FCST_LEADS':['0,3,6,9,12,15,18,21,24'],
                                    'FCST_LEVEL':'Z2',
                                    'OBS_LEVEL':'Z2',
                                    'FCST_THRESHs':[''],
                                    'OBS_THRESHs':[''],
                                    'CONFIDENCE_INTERVALS':'False',
                                    'INTERP':'BILIN',
                                    'INTERP_PNTSs':[''],
                                },
                                'DPT2m':{
                                    'STATSs':['bcrmse,me'],
                                    'FCST_LEADS':['0,3,6,9,12,15,18,21,24'],
                                    'FCST_LEVEL':'Z2',
                                    'OBS_LEVEL':'Z2',
                                    'FCST_THRESHs':['','','','',''],
                                    'OBS_THRESHs':['','>=277.594','>=283.15','>=288.706','>=294.261'],
                                    'CONFIDENCE_INTERVALS':'False',
                                    'INTERP':'BILIN',
                                    'INTERP_PNTSs':[''],
                                },
                            },
                            'vl1l2':{
                                'UGRD_VGRD10m':{
                                    'STATSs':['bcrmse,me'],
                                    'FCST_LEADS':['0,3,6,9,12,15,18,21,24'],
                                    'FCST_LEVEL':'Z10',
                                    'OBS_LEVEL':'Z10',
                                    'FCST_THRESHs':[''],
                                    'OBS_THRESHs':[''], 
                                    'CONFIDENCE_INTERVALS':'False',
                                    'INTERP':'BILIN',
                                    'INTERP_PNTSs':[''],
                                }
                            },
                        }
                    },
                }
            }
        }
    },
}
