#!/bin/bash

set -xa

# ###################################
# SET SHELL PROCESSING VARIABLES
# ###################################
export PS4='$SECONDS + '
date

###########################################################
## obtain unique LSF id (jobid) and make temp directories
############################################################
export pid=$$

export DATA=${DATA:-${DATAROOT:?}/${jobid:?}}
rm -rf $DATA
mkdir -p $DATA
cd $DATA

####################################
## Determine Job Output Name on System
#####################################
export pgmout="OUTPUT.${pid}"
export cycle=t${cyc}z

setpdy.sh 8
. ./PDY

export FIXevs=${FIXevs:-$HOMEevs/fix}
export CONFIGevs=${CONFIGevs:-$HOMEevs/parm/metplus_config/$COMPONENT}
export USHevs=${USHevs:-$HOMEevs/ush/$COMPONENT}
export EXECevs=${EXECevs:-$HOMEevs/exec}
export PARMevs=${PARMevs:-$HOMEevs/parm}
export USHevs=${USHevs:-$HOMEevs/ush}

#export VDATE=${PDYm2}
echo $COMPATH

export COMIN=${COMIN:-$(compath.py $envir/com/$NET/${evs_ver})}
export COMINobs=${COMINobs:-$(compath.py $envir/dcom)}
export COMINobs2=${COMINobs2:-$(compath.py obsproc/${obsproc_ver})}
export COMINfcst=${COMINfcst:-$(compath.py $NET/${evs_ver}/prep/$COMPONENT)}
export COMOUT=${COMOUT:-$(compath.py $NET/${evs_ver})}
export COMOUTsmall=$COMOUT/$STEP/$COMPONENT/$RUN.$VDATE
export COMOUTfinal=${COMOUTfinal:-$COMOUT/$STEP/$COMPONENT/$COMPONENT.$VDATE}
export DATA=${DATA:-$DATAROOT/$NET/${evs_ver}}

#######################################################################
# Execute the script.
#######################################################################
if [ $OBTTYPE = aeronet ] ; then
            $HOMEevs/scripts/${COMPONENT}/${STEP}/exevs_${COMPONENT}_${RUN}_${VERIF_CASE}_${OBTTYPE}_${STEP}.sh $VDATE
elif [ $OBTTYPE = airnow ] ; then
            $HOMEevs/scripts/${COMPONENT}/${STEP}/exevs_${COMPONENT}_${RUN}_${VERIF_CASE}_${OBTTYPE}_${STEP}.sh $VDATE
      else
      echo "Wrong RUN: $RUN"
      exit
fi

cat $pgmout

msg="JOB $job HAS COMPLETED NORMALLY."
postmsg "$jlogfile" "$msg"

if [ "$KEEPDATA" != "YES" ]; then
       cd $DATAROOT
       rm -rf $DATA
fi

