#!/bin/ksh
#***************************************************************************************************
# Purpose: run Global ensemble snowfall verification by METplus
# Input parameters:
#   (1) modnam: ensemble system names (gefs, cmce, or ecme)
#   (2) verify: verification case (snowfall)
# Execution steps:
#   (1) Set/export environment parameters for METplus conf files and put them into procedure files 
#   (2) Set running conf files and put them into sub-task scripts
#   (3) Put all sub-task scripts into one poe script file 
#   (4) If $run_mpi is yes, run the poe script in parallel; otherwise run the poe script in sequence
# Notes on METplus verification:
#   (1) For EnsembleStat, the input forecast files are ensemble member files from EVS prep directory
#   (2) For GridStat, the input forecast files are ensemble products (mean and probability). 
#       Since the global ensemble systems do not output snowfall ensemble products, they need to be 
#       generated. In this script, snowfall ensemble products are first generated by the MET
#       GenEnsProd tool dynamically and saved in netCDF files. Then the ensemble product netCDF
#       files are used as input for GridStat to verify SL1L2, CTC, PSTD line types.
#       
# Last update: 04/02/2025 by L. Gwen Chen (lichuan.chen@noaa.gov)
#              11/16/2023 by Binbin Zhou (Lynker@NCEP/EMC)
#              11/12/2023 by Mallory Row (SAIC@NCEP/EMC)
#       
#***************************************************************************************************

set -x 

modnam=$1
verify=$2

###########################################################
# export global parameters unified for all mpi sub-tasks
###########################################################
export regrid='NONE'

#*******************************************************
# Check input if obs and fcst input data files available
#*******************************************************
$USHevs/global_ens/evs_gens_atmos_check_input_files.sh nohrsc
export err=$?; err_chk
$USHevs/global_ens/evs_gens_atmos_check_input_files.sh $modnam
export err=$?; err_chk

MODL=`echo $modnam | tr '[a-z]' '[A-Z]'`
if [ $modnam = gefs ] ; then
  mbrs=30
  types='WEASD SNOD'
elif [ $modnam = cmce ] ; then
  mbrs=20
  types='WEASD SNOD'
elif [ $modnam = ecme ] ; then
  mbrs=50
  types='weasd'
else
  err_exit "wrong model: $modnam"
fi

#*************************
# Get sub-string of $EVSIN
#*************************
tail='/atmos'
prefix=${EVSIN%%$tail*}
index=${#prefix}
echo $index
COM_IN=${EVSIN:0:$index}
echo $COM_IN

#********************************
# Begin to build sub-task scripts
#********************************
anl=nohrsc
vhour='12'

#*****************************************************************
# Check if all stats sub-tasks are completed in the previous runs
if [ ! -s $COMOUTsmall/completed/stats_completed ] ; then
mkdir -p $COMOUTsmall/completed
mkdir -p $WORK/completed

# Check if restart directory exists
if [ -d $COMOUTsmall/restart/${verify} ] ; then
  cp -rfu $COMOUTsmall/restart/${verify} $WORK
fi
#*****************************************************************

for metplus_job in GenEnsProd EnsembleStat GridStat; do
  #****************************************
  # Build a poe script to collect sub-tasks
  #****************************************
  >run_all_gens_snowfall_${metplus_job}_poe.sh
  for type in $types ; do
    #***********************
    # Build sub-task scripts
    #***********************
    >run_${modnam}_${verify}_${type}_${metplus_job}.sh
    echo  "export output_base=${WORK}/${verify}/run_${modnam}_${verify}_${type}" >> run_${modnam}_${verify}_${type}_${metplus_job}.sh
    echo  "export type=$type" >> run_${modnam}_${verify}_${type}_${metplus_job}.sh
    echo  "export modelpath=$COM_IN" >> run_${modnam}_${verify}_${type}_${metplus_job}.sh
    echo  "export OBTYPE=NOHSRC" >> run_${modnam}_${verify}_${type}_${metplus_job}.sh
    echo  "export maskpath=$maskpath" >> run_${modnam}_${verify}_${type}_${metplus_job}.sh
    echo  "export obsvhead=$anl" >> run_${modnam}_${verify}_${type}_${metplus_job}.sh
    echo  "export obsvgrid=grid184" >> run_${modnam}_${verify}_${type}_${metplus_job}.sh
    echo  "export obsvpath=$COM_IN" >> run_${modnam}_${verify}_${type}_${metplus_job}.sh
    if [ ${modnam} = ecme ] ; then
        echo  "export modelgrid=grid4.weasd_24h.f" >> run_${modnam}_${verify}_${type}_${metplus_job}.sh
    else
        echo  "export modelgrid=grid3.${type}_24h.f" >> run_${modnam}_${verify}_${type}_${metplus_job}.sh
    fi
    echo  "export model=$modnam" >> run_${modnam}_${verify}_${type}_${metplus_job}.sh
    echo  "export MODEL=$MODL" >> run_${modnam}_${verify}_${type}_${metplus_job}.sh
    echo  "export modelhead=$modnam" >> run_${modnam}_${verify}_${type}_${metplus_job}.sh
    echo  "export vbeg=$vhour" >> run_${modnam}_${verify}_${type}_${metplus_job}.sh
    echo  "export vend=$vhour" >> run_${modnam}_${verify}_${type}_${metplus_job}.sh
    echo  "export valid_increment=21600" >> run_${modnam}_${verify}_${type}_${metplus_job}.sh
    echo  "export modeltail='.nc'" >> run_${modnam}_${verify}_${type}_${metplus_job}.sh
    echo  "export members=$mbrs" >> run_${modnam}_${verify}_${type}_${metplus_job}.sh
    if [ $modnam = cmce ] || [ $modnam = gefs ] ; then
      if [ $type = WEASD ] ; then
          echo "export options='censor_thresh = lt0; censor_val = 0; set_attr_units = \"m\"; convert(x) = x * 0.01' " >> run_${modnam}_${verify}_${type}_${metplus_job}.sh
      elif [ $type = SNOD ] ; then
          echo "export options='censor_thresh = lt0; censor_val = 0 ' " >> run_${modnam}_${verify}_${type}_${metplus_job}.sh
      fi
    fi
    if [ $modnam = cmce ] || [ $modnam = gefs ] ; then
        leads_chk="012 024 036 048 060 072 084 096 108 120 132 144 156 168 180 192 204 216 228 240 252 264 276 288 300 312 324 336 348 360 372 384"
    elif [ $modnam = ecme ] ; then
        leads_chk="012 024 036 048 060 072 084 096 108 120 132 144 156 168 180 192 204 216 228 240 252 264 276 288 300 312 324 336 348 360"
    fi
    typeset -a lead_arr
    for lead_chk in $leads_chk; do
        fcst_time=$($NDATE -$lead_chk ${vday}${vhour})
        fyyyymmdd=${fcst_time:0:8}
        ihour=${fcst_time:8:2}
        if [ $metplus_job = GenEnsProd ] || [ $metplus_job = EnsembleStat ] ; then
            if [ ${modnam} = ecme ] ; then
                chk_path=$COM_IN/atmos.${fyyyymmdd}/$modnam/$modnam.ens*.t${ihour}z.grid4.weasd_24h.f${lead_chk}.nc
            else
                chk_path=$COM_IN/atmos.${fyyyymmdd}/$modnam/$modnam.ens*.t${ihour}z.grid3.${type}_24h.f${lead_chk}.nc
            fi
            nmbrs_lead_check=$(find $chk_path -size +0c 2>/dev/null | wc -l)
            if [ $nmbrs_lead_check -eq $mbrs ]; then
                lead_arr[${#lead_arr[*]}+1]=${lead_chk}
            fi
        elif [ $metplus_job = GridStat ] ; then
            if [ ${modnam} = ecme ] ; then
                chk_file=${WORK}/${verify}/run_${modnam}_${verify}_${type}/stat/$modnam/GenEnsProd_${MODL}_NOHRSC24_FHR${lead_chk}_${vday}_${vhour}0000V_ens.nc
            else
                chk_file=${WORK}/${verify}/run_${modnam}_${verify}_${type}/stat/$modnam/GenEnsProd_${MODL}_${type}24_FHR${lead_chk}_${vday}_${vhour}0000V_ens.nc
            fi
            if [ -s $chk_file ]; then
                lead_arr[${#lead_arr[*]}+1]=${lead_chk}
            fi
        fi
    done

    if [ $modnam = cmce ]; then
        conf_MODEL="GEFS"
    else
        conf_MODEL=$MODL
    fi

    for lead_hr in ${lead_arr[@]}; do
      # Check for restart: check if the single sub-task is completed in the previous run
      # If this task has been completed in the previous run, then skip it
      if [ ! -e $COMOUTsmall/completed/run_${modnam}_${verify}_${type}_${metplus_job}_f${lead_hr}.completed ] ; then
        echo "export lead=${lead_hr}" >> run_${modnam}_${verify}_${type}_${metplus_job}.sh

        if [ $metplus_job = GridStat ]; then
          echo  "${METPLUS_PATH}/ush/run_metplus.py -c ${PARMevs}/metplus_config/machine.conf -c ${GRID2GRID_CONF}/${metplus_job}_fcst${conf_MODEL}_obsNOHRSC24h_mean.conf" >> run_${modnam}_${verify}_${type}_${metplus_job}.sh
          echo  "export err=\$?; err_chk" >> run_${modnam}_${verify}_${type}_${metplus_job}.sh
          echo  "${METPLUS_PATH}/ush/run_metplus.py -c ${PARMevs}/metplus_config/machine.conf -c ${GRID2GRID_CONF}/${metplus_job}_fcst${conf_MODEL}_obsNOHRSC24h_prob.conf" >> run_${modnam}_${verify}_${type}_${metplus_job}.sh
          echo  "export err=\$?; err_chk" >> run_${modnam}_${verify}_${type}_${metplus_job}.sh
        else
          echo  "${METPLUS_PATH}/ush/run_metplus.py -c ${PARMevs}/metplus_config/machine.conf -c ${GRID2GRID_CONF}/${metplus_job}_fcst${conf_MODEL}_obsNOHRSC24h.conf" >> run_${modnam}_${verify}_${type}_${metplus_job}.sh
          echo  "export err=\$?; err_chk" >> run_${modnam}_${verify}_${type}_${metplus_job}.sh
        fi

        # Indicate sub-task is completed for restart
        echo ">$WORK/completed/run_${modnam}_${verify}_${type}_${metplus_job}_f${lead_hr}.completed" >> run_${modnam}_${verify}_${type}_${metplus_job}.sh
        echo "echo "${modnam}_${verify}_${type}_${metplus_job}_f${lead_hr} task is completed" >> $WORK/completed/run_${modnam}_${verify}_${type}_${metplus_job}_f${lead_hr}.completed" >> run_${modnam}_${verify}_${type}_${metplus_job}.sh

        # Save files for restart
        echo "if [ $SENDCOM = YES ] ; then" >> run_${modnam}_${verify}_${type}_${metplus_job}.sh
        echo "  if [ -d $WORK/${verify}/run_${modnam}_${verify}_${type}/stat/${modnam} ] ; then" >> run_${modnam}_${verify}_${type}_${metplus_job}.sh
        echo "    mkdir -p $COMOUTsmall/restart/${verify}/run_${modnam}_${verify}_${type}/stat" >> run_${modnam}_${verify}_${type}_${metplus_job}.sh
        echo "    cp -f $WORK/completed/run_${modnam}_${verify}_${type}_${metplus_job}_f${lead_hr}.completed $COMOUTsmall/completed" >> run_${modnam}_${verify}_${type}_${metplus_job}.sh
        echo "    cp -rfu $WORK/${verify}/run_${modnam}_${verify}_${type}/stat/${modnam} $COMOUTsmall/restart/${verify}/run_${modnam}_${verify}_${type}/stat" >> run_${modnam}_${verify}_${type}_${metplus_job}.sh
        echo "  fi" >> run_${modnam}_${verify}_${type}_${metplus_job}.sh
        echo "fi" >> run_${modnam}_${verify}_${type}_${metplus_job}.sh
      fi # end of check restart for sub-task
    done # end of lead_arr loop
    unset lead_arr

    if [ $metplus_job = EnsembleStat ]; then
      if [ $SENDCOM="YES" ] ; then
        echo "for FILE in \$output_base/stat/${modnam}/ensemble_stat_*.stat ; do" >> run_${modnam}_${verify}_${type}_${metplus_job}.sh
        echo "  if [ -s \$FILE ]; then" >> run_${modnam}_${verify}_${type}_${metplus_job}.sh
        echo "    cp -v \$FILE $COMOUTsmall" >> run_${modnam}_${verify}_${type}_${metplus_job}.sh
        echo "  fi" >> run_${modnam}_${verify}_${type}_${metplus_job}.sh
        echo "done" >> run_${modnam}_${verify}_${type}_${metplus_job}.sh
      fi
    fi

    if [ $metplus_job = GridStat ]; then
      if [ $SENDCOM="YES" ] ; then
        echo "for FILE in \$output_base/stat/${modnam}/grid_stat_*.stat ; do" >> run_${modnam}_${verify}_${type}_${metplus_job}.sh
        echo "  if [ -s \$FILE ]; then" >> run_${modnam}_${verify}_${type}_${metplus_job}.sh
        echo "    cp -v \$FILE $COMOUTsmall" >> run_${modnam}_${verify}_${type}_${metplus_job}.sh
        echo "  fi" >> run_${modnam}_${verify}_${type}_${metplus_job}.sh
        echo "done" >> run_${modnam}_${verify}_${type}_${metplus_job}.sh
      fi
    fi

    chmod +x run_${modnam}_${verify}_${type}_${metplus_job}.sh
    echo "${DATA}/run_${modnam}_${verify}_${type}_${metplus_job}.sh" >> run_all_gens_snowfall_${metplus_job}_poe.sh
  done # end of types loop

  #***************************
  # Run poe script in sequence
  #***************************
  if [ -s run_all_gens_snowfall_${metplus_job}_poe.sh ] ; then
    chmod 755 ${DATA}/run_all_gens_snowfall_${metplus_job}_poe.sh
    ${DATA}/run_all_gens_snowfall_${metplus_job}_poe.sh
    export err=$?; err_chk
  fi
done # end of metplus_jobs loop

# Indicate all tasks are completed
>$WORK/completed/stats_completed
echo "All stats are completed" >> $WORK/completed/stats_completed

if [ $SENDCOM = YES ] ; then
  cp -f $WORK/completed/stats_completed $COMOUTsmall/completed
fi

fi # end of check restart for all tasks

#*******************************************************
# Combine small stat files to form a final big stat file
#*******************************************************
if [ $gather = yes ] ; then
  $USHevs/global_ens/evs_global_ens_atmos_gather.sh $MODELNAME $verify 12 12
  export err=$?; err_chk
fi
