#!/bin/ksh
#  JOB card cerated for running METPlus-based Global enesmble verifications
#   By Binbin Zhou, IMSG@EMC/NCEP
#   Feb 2, 2022
#
set -xa
#######################################################
#######################################################


export RUN_ENVIR=${RUN_ENVIR:-nco}
export SENDECF=${SENDECF:-YES}

###############################
# Specify RUN name
###############################
export NET=evs
export RUN=narre


#####################################################################################
# This block is for Developer's test run:
# Run config file to get input parameters
# This config file should define the following variables
# DATA_IN: Location of working directory, default to $DATAROOT
# SENDECF: If the job is to be running using ecFlow, default to YES
# SENDDBN: Set to NO for developers, default to YES
# COM_IN:  Directory for input files, default to /com/$NET/${envir}
# COM_OUT: Directory for output file, default to /com/$NET/${envir}
# gespath: Directory for the guess or restart files, default to /nwges/${envir}
#####################################################################################
if [ "$RUN_ENVIR" = dev ] ; then   ### For Developers
  . $HOMEevs/parm/evs_config_dev/narre/config.evs.standalone
else
  . $HOMEevs/parm/evs_config/narre/config.evs.prod
fi

# ###################################
# SET SHELL PROCESSING VARIABLES
# ###################################
export PS4='$SECONDS + '
date

###########################################################
# obtain unique process id (pid) and make temp directories
###########################################################
export pid=$$
export COM_IN=${COM_IN:-$COMROOT/evs/${evs_ver}}
export COM_OUT=${COM_IN}
export DATA_IN=${DATA_IN:-$DATAROOT}
export DATA=$DATA_IN/evs-narre-g2o_plots_${envir}.$$

mkdir -p $DATA
cd $DATA




export ush_dir=$USHevs/narre
export prune_dir=$DATA/data
export save_dir=$DATA/out
export output_base_dir=$DATA/stat_archive
export log_metplus=$DATA/logs/NARRE_verif_plotting_job.out
mkdir -p $prune_dir
mkdir -p $save_dir
mkdir -p $output_base_dir
mkdir -p $DATA/logs

####################################
# File To Log Msgs
####################################
export jlogfile=${jlogfile:-${DATA}/jlogfile}

####################################
# Determine Job Output Name on System
####################################
export outid="LL$job"
export jobid="${outid}.o${pid}"
export pgmout="OUTPUT.${pid}"

export cycle=t${cyc}z

##################################################
# SAVEGES  - Copy Files From TMPDIR to $GESdir
# SENDECF  - Flag Events on ECF
# SENDCOM  - Copy Files From TMPDIR to $COMOUT
# SENDDBN  - Issue DBNet Client Calls
##################################################
export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-YES}
export SENDECF=${SENDECF:-YES}

####################################
# Specify codes and scripts locaton
####################################

# Run setpdy and initialize PDY variables
setpdy.sh
. $DATA/PDY

export vday=${vday:-$PDYm1}

export eval_period='TEST'
export past_days=12

export init_end=$vday
export valid_end=$vday

n=0
while [ $n -le $past_days ] ; do
    hrs=$((n*24))
    first_day=`$NDATE -$hrs ${vday}00|cut -c1-8`
    n=$((n+1))
done

export init_beg=$first_day
export valid_beg=$first_day



##################################
# Define COMIN/COMOUT variables
##################################

export GATHER_STAT=${COM_OUT}/stats/narre/narre.${vday}
export SMALL_STAT=${COM_OUT}/stats/narre/grid2obs.${vday}/
export PLOTS=${COM_OUT}/plots/narre/narre.${vday}

mkdir -p $GATHER_STAT $SMALL_STAT $PLOTS

export GRID2OBS_CONF=$PARMevs/metplus_config/narre/grid2obs/stats
export MET_CONFIG=${METPLUS_BASE}/parm/met_config


export JLOGFILE="${output_base}/logs/metplus_jlogfile_narre"
export maskpath=$MASKS


sh $HOMEevs/scripts/narre/plots/exevs_narre_plots.sh 

msg="JOB $job HAS COMPLETED NORMALLY."
postmsg "$jlogfile" "$msg"

#if [ "$KEEPDATA" != "YES" ] ; then
#  cd $DATAROOT
#  rm -rf $DATA
#fi

#date

