#!/bin/ksh

set -xa
#######################################################
#######################################################

export cycle=t${cyc}z

export SENDCOM=${SENDCOM:-YES}
export SENDDBN=${SENDDBN:-YES}
export SENDECF=${SENDECF:-YES}

export COMIN=${COMIN:-$(compath.py  $envir/com/$NET/$evs_ver)}/stats/$COMPONENT/$MODELNAME.$VDATE
export COMOUT=${COMOUT:-$(compath.py -o $envir/com/$NET/${evs_ver})}/$STEP/$COMPONENT/$RUN.$VDATE
export DATA_IN=${DATA_IN:-$DATAROOT}
mkdir $COMOUT

export HOMEevs=${HOMEevs:-${PACKAGEROOT}/evs_gens.${evs_ver}}
export EXECevs=$HOMEevs/exec
export PARMevs=$HOMEevs/parm
export USHevs=$HOMEevs/ush
export SCRIPTerf=$HOMEevs/scripts
export FIXevs=${FIXevs:-/lfs/h1/ops/prod/packages/evs.${evs_ver}/fix}

export ush_dir=/lfs/h2/emc/vpppg/noscrub/binbin.zhou/EVS_plots/verif_plotting/ush

export pid=$$
jobid=evs_${RUN}_${COMPONENT}_${VERIF_CASE}_${STEP}.$$
export DATA=$DATA_IN/$jobid
mkdir -p $DATA
cd $DATA

####################################
# Determine Job Output Name on System
####################################
export outid="LL$job"
export jobid="${outid}.o${pid}"
export pgmout="OUTPUT.${pid}"

# Run setpdy and initialize PDY variables
setpdy.sh
. $DATA/PDY

if [ $RUN = atmos ] ; then
  export INITDATE=${INITDATE:-$PDYm2}
fi

if [ $valid_time = separate ] ; then
  sh $HOMEevs/scripts/${COMPONENT}/${STEP}/exevs_${COMPONENT}_${RUN}_${VERIF_CASE}_separate_${STEP}.sh
else
  sh $HOMEevs/scripts/${COMPONENT}/${STEP}/exevs_${COMPONENT}_${RUN}_${VERIF_CASE}_${STEP}.sh
fi

msg="JOB $job HAS COMPLETED NORMALLY."
postmsg "$msg"

if [ "$KEEPDATA" != "YES" ] ; then
  cd $DATAROOT
  rm -rf $DATA
fi

date

